IEEE1609dot2-Peer2Peer$(OBJ): IEEE1609dot2-Peer2Peer.cpp \
 IEEE1609dot2-Peer2Peer.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h IEEE1609dot2.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2-Peer2PeerDec$(OBJ): IEEE1609dot2-Peer2PeerDec.cpp \
 IEEE1609dot2-Peer2Peer.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h IEEE1609dot2.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtxsrc/rtxBitDecode.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2-Peer2PeerEnc$(OBJ): IEEE1609dot2-Peer2PeerEnc.cpp \
 IEEE1609dot2-Peer2Peer.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h IEEE1609dot2.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtxsrc/rtxStreamMemory.h ../../../rtxsrc/rtxStream.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2-Peer2PeerPrint$(OBJ): IEEE1609dot2-Peer2PeerPrint.cpp \
 IEEE1609dot2-Peer2Peer.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h IEEE1609dot2.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/rtPrint.h ../../../rtxsrc/rtxPrint.h \
 ../../../rtsrc/rtBCD.h ../../../rtxsrc/rtxTBCD.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2$(OBJ): IEEE1609dot2.cpp IEEE1609dot2.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CBitStr.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2BaseTypes$(OBJ): IEEE1609dot2BaseTypes.cpp \
 IEEE1609dot2BaseTypes.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2BaseTypesDec$(OBJ): IEEE1609dot2BaseTypesDec.cpp \
 IEEE1609dot2BaseTypes.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxBitDecode.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2BaseTypesEnc$(OBJ): IEEE1609dot2BaseTypesEnc.cpp \
 IEEE1609dot2BaseTypes.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxStreamMemory.h ../../../rtxsrc/rtxStream.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2BaseTypesPrint$(OBJ): IEEE1609dot2BaseTypesPrint.cpp \
 IEEE1609dot2BaseTypes.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtsrc/rtPrint.h ../../../rtxsrc/rtxPrint.h \
 ../../../rtsrc/rtBCD.h ../../../rtxsrc/rtxTBCD.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2Crl$(OBJ): IEEE1609dot2Crl.cpp IEEE1609dot2Crl.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 IEEE1609dot2.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 IEEE1609dot2CrlBaseTypes.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlBaseTypes$(OBJ): IEEE1609dot2CrlBaseTypes.cpp \
 IEEE1609dot2CrlBaseTypes.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlBaseTypesDec$(OBJ): IEEE1609dot2CrlBaseTypesDec.cpp \
 IEEE1609dot2CrlBaseTypes.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxBitDecode.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlBaseTypesEnc$(OBJ): IEEE1609dot2CrlBaseTypesEnc.cpp \
 IEEE1609dot2CrlBaseTypes.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxStreamMemory.h \
 ../../../rtxsrc/rtxStream.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlBaseTypesPrint$(OBJ): IEEE1609dot2CrlBaseTypesPrint.cpp \
 IEEE1609dot2CrlBaseTypes.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtsrc/rtPrint.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlDec$(OBJ): IEEE1609dot2CrlDec.cpp IEEE1609dot2Crl.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 IEEE1609dot2.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 IEEE1609dot2CrlBaseTypes.h ../../../rtxsrc/rtxBitDecode.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlEnc$(OBJ): IEEE1609dot2CrlEnc.cpp IEEE1609dot2Crl.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 IEEE1609dot2.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 IEEE1609dot2CrlBaseTypes.h ../../../rtxsrc/rtxStreamMemory.h \
 ../../../rtxsrc/rtxStream.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlPrint$(OBJ): IEEE1609dot2CrlPrint.cpp IEEE1609dot2Crl.h \
 rtkey.h ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 IEEE1609dot2.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 IEEE1609dot2CrlBaseTypes.h ../../../rtsrc/rtPrint.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlSsp$(OBJ): IEEE1609dot2CrlSsp.cpp IEEE1609dot2CrlSsp.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 IEEE1609dot2BaseTypes.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlSspDec$(OBJ): IEEE1609dot2CrlSspDec.cpp IEEE1609dot2CrlSsp.h \
 rtkey.h ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 IEEE1609dot2BaseTypes.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxBitDecode.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlSspEnc$(OBJ): IEEE1609dot2CrlSspEnc.cpp IEEE1609dot2CrlSsp.h \
 rtkey.h ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 IEEE1609dot2BaseTypes.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxStreamMemory.h ../../../rtxsrc/rtxStream.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2CrlSspPrint$(OBJ): IEEE1609dot2CrlSspPrint.cpp \
 IEEE1609dot2CrlSsp.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h IEEE1609dot2BaseTypes.h \
 ../../../rtsrc/ASN1CSeqOfList.h ../../../rtsrc/rtPrint.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2Dec$(OBJ): IEEE1609dot2Dec.cpp IEEE1609dot2.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CBitStr.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxBitDecode.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2Enc$(OBJ): IEEE1609dot2Enc.cpp IEEE1609dot2.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CBitStr.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxStreamMemory.h \
 ../../../rtxsrc/rtxStream.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2Print$(OBJ): IEEE1609dot2Print.cpp IEEE1609dot2.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CBitStr.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtsrc/rtPrint.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2WsaProtocol$(OBJ): IEEE1609dot2WsaProtocol.cpp \
 IEEE1609dot2WsaProtocol.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2WsaProtocolDec$(OBJ): IEEE1609dot2WsaProtocolDec.cpp \
 IEEE1609dot2WsaProtocol.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxBitDecode.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2WsaProtocolEnc$(OBJ): IEEE1609dot2WsaProtocolEnc.cpp \
 IEEE1609dot2WsaProtocol.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtxsrc/rtxStreamMemory.h \
 ../../../rtxsrc/rtxStream.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2WsaProtocolPrint$(OBJ): IEEE1609dot2WsaProtocolPrint.cpp \
 IEEE1609dot2WsaProtocol.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtsrc/rtPrint.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2WsaSsp$(OBJ): IEEE1609dot2WsaSsp.cpp IEEE1609dot2WsaSsp.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2WsaSspDec$(OBJ): IEEE1609dot2WsaSspDec.cpp IEEE1609dot2WsaSsp.h \
 rtkey.h ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 ../../../rtxsrc/rtxBitDecode.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2WsaSspEnc$(OBJ): IEEE1609dot2WsaSspEnc.cpp IEEE1609dot2WsaSsp.h \
 rtkey.h ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 ../../../rtxsrc/rtxStreamMemory.h ../../../rtxsrc/rtxStream.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
IEEE1609dot2WsaSspPrint$(OBJ): IEEE1609dot2WsaSspPrint.cpp \
 IEEE1609dot2WsaSsp.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 IEEE1609dot2BaseTypes.h ../../../rtsrc/rtPrint.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
reader$(OBJ): reader.cpp IEEE1609dot2.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
writer$(OBJ): writer.cpp IEEE1609dot2.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/ASN1CSeqOfList.h IEEE1609dot2BaseTypes.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h \
 ../../../rtxsrc/rtxPrint.h
