/* 
This benchmark test driver program does the following:

1. Populates a test data record.
2. Executes a benchmark timing loop to encode the record a given number of 
   times and records the results.
3. Executes a benchmark timing loop to decode the record a given number of 
   times and records the results.
4. Prints the results to a CSV file.
*/
#include <stdio.h>
#include <stdlib.h>
#include "Employee.h"
#include "rtxsrc/rtxBench.h"

#define MAXMSGLEN 1024

static void fill_jSmith (OSCTXT* pctxt, PersonnelRecord* pPR);

#define ALL 0
#define ENCODE 1
#define DECODE 2

int main (int argc, char** argv)
{
   PersonnelRecord msgdata;
   OSCTXT	ctxt, ctxt2;
   OSOCTET	msgbuf[MAXMSGLEN];
   int		i, itercnt = 100000, len, stat;
   OSBOOL       aligned = TRUE;
   OSBOOL       trace = FALSE, verbose = FALSE;
   int      action = ALL;    /* 0: encode & decode; 1: encode; 2: decode */
   const char*  resultsFile = "bench.csv";
   clock_t	start, finish;
   OSRTBenchmarkData benchData;
   
   memset (&benchData, 0, sizeof(benchData));
   benchData.program = "employee3";
   benchData.encRules = "per";
      
   /* Process command line arguments */

   if (argc > 1) {
      for (i = 1; i < argc; i++) {
         if (!strcmp (argv[i], "-v")) trace = verbose = TRUE;
         else if (!strcmp (argv[i], "-a")) aligned = TRUE;
         else if (!strcmp (argv[i], "-u")) aligned = FALSE;
         else if (!strcmp (argv[i], "-trace")) trace = TRUE;
	 else if (!strcmp (argv[i], "-iter")) itercnt = atoi (argv[++i]);
	 else if (!strcmp (argv[i], "-resfile")) resultsFile = argv[++i];
    else if (!strcmp (argv[i], "-encode")) action = ENCODE;
    else if (!strcmp (argv[i], "-decode")) action = DECODE;
         else {
            printf ("usage: writer [ options ]\n");
            printf ("   -v  verbose mode: print extended trace info\n");
            printf ("   -a  use PER aligned encoding\n");
            printf ("   -u  use PER unaligned encoding\n");
            printf ("   -trace         display trace info\n");
	    printf ("   -iter <count>  set iteration count\n");
	    printf ("   -resfile <filename> set results filename\n");
       printf ("   -[encode|decode] run encode/decode only\n");
            return 0;
         }
      }
   }

   /* Init context structure */

   if ((stat = rtInitContext (&ctxt)) != 0) {
      printf ("rtInitContext failed\n");
      rtxErrPrint (&ctxt);
      return -1;
   }
   rtxSetDiag (&ctxt, verbose);

   if ((stat = rtInitContext (&ctxt2)) != 0) {
      printf ("rtInitASN1Context failed\n");
      rtxErrPrint (&ctxt2);
      return -1;
   }
   rtxSetDiag (&ctxt2, verbose);

   /* Populate employee structure (note: this is the structure that was */
   /* generated by the compiler)..					*/

   fill_jSmith (&ctxt2, &msgdata);

   /* If decode only, encode just once to get the encoded data */
   if ( action == DECODE ) benchData.itercnt = 1;
   else benchData.itercnt = itercnt;

   /* Encode benchmark test loop */

   start = clock();

   for (i = 0; i < (int)benchData.itercnt; i++) {
      pu_setBuffer (&ctxt, msgbuf, sizeof(msgbuf), aligned);
  
      if ((stat = asn1PE_PersonnelRecord (&ctxt, &msgdata)) != 0) {
         rtxErrPrint (&ctxt);
         return (-1);
      } 
      rtxMemReset (&ctxt);
   }

   finish = clock();

   pe_GetMsgPtr (&ctxt, &len);

   benchData.msgSize = len;
   benchData.encodeMsecs = (unsigned long)
      ((finish - start) * 1000 / CLOCKS_PER_SEC);

   if (trace) {
      printf ("Encoding was successful\n");
      printf ("Hex dump of encoded record:\n");
      pu_hexdump (&ctxt);

      printf ("Encoded record:\n");
      asn1Print_PersonnelRecord ("msgdata", &msgdata);
   }

   benchData.itercnt = itercnt;

   /* Decode benchmark test loop */

   rtxFreeContext (&ctxt);
   if ((stat = rtInitContext (&ctxt)) != 0) {
      printf ("rtInitContext failed\n");
      rtxErrPrint (&ctxt);
      return -1;
   }
   rtxSetDiag (&ctxt, verbose);
   rtSetFastCopy (&ctxt, TRUE);

   if ( action != ENCODE ) {
      start = clock();

      for (i = 0; i < (int)benchData.itercnt; i++) {
         pu_setBuffer (&ctxt, msgbuf, len, aligned);

         if (stat == 0)
            stat = asn1PD_PersonnelRecord (&ctxt, &msgdata);

         if (stat != 0) {
            printf ("decode of PersonnelRecord failed\n");
            rtxErrPrint (&ctxt);
            return -1;
         }
         rtxMemReset (&ctxt);
      }

      finish = clock();

      benchData.decodeMsecs = (unsigned long)
         ((finish - start) * 1000 / CLOCKS_PER_SEC);
   }

   rtxBenchPrintResults (resultsFile, &benchData);

   if (action != ENCODE && trace) {
      printf ("***\n");
      printf ("Decode of PersonnelRecord was successful\n");

      printf ("Hex dump of encoded record:\n");
      pu_hexdump (&ctxt);
      printf ("Binary dump:\n");
      pu_bindump (&ctxt, "msgdata");
     
      printf ("Decoded record:\n");
      asn1Print_PersonnelRecord ("msgdata", &msgdata);
   }

   return 0;
}

/* Routine to fill the employee record with test data */

static void fill_Name (Name* pName, char* fn, char* mi, char* ln);

static void fill_jSmith (OSCTXT* pctxt, PersonnelRecord* pPR)
{
   ChildInformation* pChildInfo;

   asn1Init_PersonnelRecord (pPR);

   fill_Name (&pPR->name, "John", "P", "Smith");

   pPR->title  = "Director";
   pPR->number = 51;
   pPR->dateOfHire = "19710917";

   fill_Name (&pPR->nameOfSpouse, "Mary", "T", "Smith");

   pPR->m.childrenPresent = 1;
   rtxDListInit (&pPR->children);

   /* fill first child record */

   pChildInfo = rtxMemAllocType (pctxt, ChildInformation);
   asn1Init_ChildInformation (pChildInfo);
   fill_Name (&pChildInfo->name, "Ralph", "T", "Smith");
   pChildInfo->dateOfBirth = "19571111";
   rtxDListAppend (pctxt, &pPR->children, pChildInfo);

   /* fill second child record */

   pChildInfo = rtxMemAllocType (pctxt, ChildInformation);
   asn1Init_ChildInformation (pChildInfo);
   fill_Name (&pChildInfo->name, "Susan", "B", "Jones");
   pChildInfo->dateOfBirth = "19590717";

   /* note: the following two fields are only present in the employee3  */
   /* version of the PersonnelRecord..                                  */

   pChildInfo->m.sexPresent = 1;
   pChildInfo->sex = female;

   rtxDListAppend (pctxt, &pPR->children, pChildInfo);
}

/* Routine to fill a name structure */

static void fill_Name (Name* pName, char* fn, char* mi, char* ln)
{
   pName->givenName = fn;
   pName->initial = mi;
   pName->familyName = ln;
}
