#
# This file was generated by the Objective Systems ASN1C Compiler
# (https://obj-sys.com).  Version: 7.6.A, Date: 18-May-2021.
#


import argparse
import sys
import traceback
from osyspyrt.asn1ber import Asn1BerDecodeBuffer
from osyspyrt.ts32297 import TS32297CDRFileHeader, TS32297CDRHeader
from IMS_R8_2009_03 import *


class Reader:
    @staticmethod
    def main(in_filename, trace):
        try:
            decbuf = Asn1BerDecodeBuffer.from_file(in_filename)
            filehdr = TS32297CDRFileHeader()
            cdrhdr = TS32297CDRHeader()

            # decode TS 32.297 file header
            filehdr.decode(decbuf)
            if trace:
                print(str(filehdr))

            for i in range(1, (filehdr.cdr_count + 1)):
                # Decode TS 32.297 record header
                cdrhdr.decode(decbuf)
                if trace:
                    print(str(cdrhdr))

                # Read and decode the CDR.
                imsrecord = IMSRecord()
                imsrecord.ber_decode(decbuf)
                if trace:
                    imsrecord.print_value()

        except Exception:
            print(traceback.format_exc())
            sys.exit(-1)


if __name__ == '__main__':
    my_in_filename = "message.dat"
    mytrace = True

    # Process command line arguments
    parser = argparse.ArgumentParser()

    parser.add_argument('--notrace',
                        action='store_true',
                        help='Do not display trace info')

    parser.add_argument('-i', metavar='<filename>',
                        help='Read encoded msg from <in_filename>')

    args = parser.parse_args()

    if args.notrace:
        mytrace = False
    if args.i:
        my_in_filename = args.i

    Reader.main(my_in_filename, mytrace)
