/* This test driver program encodes a data record and writes the        */
/* encoded result to an output file..                                   */

#include <stdio.h>
#include <stdlib.h>
#include "Employee.h"
#include "rtxsrc/rtxMemLeakCheck.h"
#include "rtxsrc/rtxDiag.h"
#include "rtxsrc/rtxStreamSocket.h"

#define DEFAULT_URL "http://127.0.0.1:9124"
#define MAXMSGLEN 1024

static void fill_jSmith (OSCTXT* pctxt, PersonnelRecord* pPR);

int main (int argc, char** argv)
{
   PersonnelRecord employee;
   OSCTXT	ctxt;
   int		i, numMsgs=2, stat, port;
   const char*  url = DEFAULT_URL;
   char buf[100];
   OSBOOL       aligned = 1, trace = TRUE, verbose = FALSE;

   DECLARE_MEMLEAK_DETECTOR;

   /* Process command line arguments */

   if (argc > 1) {
      for (i = 1; i < argc; i++) {
         if (!strcmp (argv[i], "-a")) aligned = 1;
         else if (!strcmp (argv[i], "-u")) aligned = 0;
         else if (!strcmp (argv[i], "-v")) verbose = TRUE;
         else if (!strcmp (argv[i], "-notrace")) trace = FALSE;
         else if (!strcmp (argv[i], "-url")) url = argv[++i];
         else {
            printf ("usage: writer -a | -u [ -v ] [ -url ]\n");
            printf ("   -a  use PER aligned encoding\n");
            printf ("   -u  use PER unaligned encoding\n");
            printf ("   -v  verbose mode: print trace info\n");
            printf ("   -notrace  do not display trace info\n");
            printf ("   -url       bind URL http://host:port\n");
            return 0;
         }
      }
   }

   {
      char* portStr;

      strcpy (buf, url);
      portStr = strstr (buf, "://");
      if (portStr != 0) {
         url = portStr + 3;
      }
      else
         url = buf;

      portStr = strchr (url, ':');
      if (portStr != 0) {
         *portStr = 0;
         portStr++;
         port = atoi (portStr);
      }
   }

   /* Create a new context structure */
   if (rtInitContext (&ctxt) != 0) return -1;
   rtxSetDiag (&ctxt, verbose);

   stat = rtxSocketsInit();
   if (0 != stat) {
      printf ("Socket initialization failed.\n");
      rtxErrSetData (&ctxt, stat, __FILE__, __LINE__);
      rtxErrPrint (&ctxt);
      return stat;
   }

   stat = rtxStreamSocketCreateWriter (&ctxt, url, port);
   if (0 != stat) {
      printf ("Stream initialization failed.\n");
      rtxErrPrint (&ctxt);
      return stat;
   }

   pu_setTrace (&ctxt, trace);
   ctxt.buffer.aligned = aligned;

   /* Populate employee structure (note: this is the structure that was */
   /* generated by the compiler)..					*/

   fill_jSmith (&ctxt, &employee);

   if (trace) {
      printf ("The following record will be encoded:\n");
      asn1Print_PersonnelRecord ("employee", &employee);
      printf ("\n");
   }

   printf ("sending %d messages..\n", numMsgs);

   for (i = 0; i < numMsgs; i++) {
      /* Encode */

      if ((stat = asn1PE_PersonnelRecord (&ctxt, &employee)) == 0) {
         rtxByteAlign (&ctxt);
         rtxStreamFlush (&ctxt);

         if (trace) {
            printf ("Encoding was successful\n");
            printf ("Hex dump of encoded record:\n");
            pu_hexdump (&ctxt);
            printf ("Binary dump:\n");
            pu_bindump (&ctxt, "employee");
         }
      }
      else {
         printf ("Encoding failed\n");
         rtxErrPrint (&ctxt);
         return -1;
      }
   }

   rtxStreamClose (&ctxt);
   rtFreeContext (&ctxt);
   return 0;

}


/* Routine to fill the employee record with test data */

static void fill_Name (Name* pName, char* fn, char* mi, char* ln);

static void fill_jSmith (OSCTXT* pctxt, PersonnelRecord* pPR)
{
   ChildInformation* pChildInfo;

   asn1Init_PersonnelRecord (pPR);

   fill_Name (&pPR->name, "John", "P", "Smith");

   pPR->title  = "Director";
   pPR->number = 51;
   pPR->dateOfHire = "19710917";

   fill_Name (&pPR->nameOfSpouse, "Mary", "T", "Smith");

   /* fill first child record */
   pPR->m.childrenPresent = TRUE;

   pChildInfo = rtxMemAllocType (pctxt, ChildInformation);
   asn1Init_ChildInformation (pChildInfo);

   fill_Name (&pChildInfo->name, "Ralph", "T", "Smith");
   pChildInfo->dateOfBirth = "19571111";
   rtxDListAppend (pctxt, &pPR->children, pChildInfo);

   /* fill second child record */

   pChildInfo = rtxMemAllocType (pctxt, ChildInformation);
   asn1Init_ChildInformation (pChildInfo);

   fill_Name (&pChildInfo->name, "Susan", "B", "Jones");
   pChildInfo->dateOfBirth = "19590717";
   rtxDListAppend (pctxt, &pPR->children, pChildInfo);
}

/* Routine to fill a name structure */

static void fill_Name (Name* pName, char* fn, char* mi, char* ln)
{
   pName->givenName = fn;
   pName->initial = mi;
   pName->familyName = ln;
}

