/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.6.0, Date: 15-Feb-2022.
 */
#include "TS24008IES.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

/* TS24008IE_IMSI */

EXTERN const char* gs_TS24008IES_IMSI_CharSet =
"0123456789";

/* TS24008IE_IMEI */

EXTERN const char* gs_TS24008IES_IMEI_CharSet =
"0123456789";

/* TS24008IE_IMEISV */

EXTERN const char* gs_TS24008IES_IMEISV_CharSet =
"0123456789";

/* TS24008IE_TBCDString */

EXTERN const char* gs_TS24008IES_TBCDString_CharSet =
"#*0123456789abc";

/* TS24008IE_TBCDString3 */

EXTERN const char* gs_TS24008IES_TBCDString3_CharSet =
"#*0123456789abc";

/* TS24008IE_MCCMNCPair */

int asn1Init_TS24008IE_MCCMNCPair (TS24008IE_MCCMNCPair* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->mcc[0] = '\0';
   pvalue->mnc[0] = '\0';
   return 0;
}

/* TS24008IE_MobileIdentity_TMGI */

int asn1Init_TS24008IE_MobileIdentity_TMGI (
   TS24008IE_MobileIdentity_TMGI* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_MCCMNCPair (&pvalue->mcc_mnc);
   return 0;
}

/* TS24008IE_MobileIdentity */

int asn1Init_TS24008IE_MobileIdentity (TS24008IE_MobileIdentity* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   return 0;
}

/* TS24008IE_RoutingAreaIdent */

int asn1Init_TS24008IE_RoutingAreaIdent (TS24008IE_RoutingAreaIdent* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_MCCMNCPair (&pvalue->mcc_mnc);
   return 0;
}

/* TS24008IE_TMGI */

int asn1Init_TS24008IE_TMGI (TS24008IE_TMGI* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_MCCMNCPair (&pvalue->mcc_mnc);
   return 0;
}

/* TS24008IE_RFPowerCapValues */

const OSEnumItem TS24008IE_RFPowerCapValues_ENUMTAB[] = {
   { OSUTF8("class1"), 0, 6, 0 },
   { OSUTF8("class2"), 1, 6, 1 },
   { OSUTF8("class3"), 2, 6, 2 },
   { OSUTF8("class4"), 3, 6, 3 },
   { OSUTF8("class5"), 4, 6, 4 },
   { OSUTF8("rfMAX"), 7, 5, 5 }
} ;

const OSUTF8CHAR* TS24008IE_RFPowerCapValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_RFPowerCapValues_ENUMTAB, 
      TS24008IE_RFPowerCapValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_RFPowerCapValues_ENUMTABSIZE) {
      return TS24008IE_RFPowerCapValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_RFPowerCapValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_RFPowerCapValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_RFPowerCapValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_RFPowerCapValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_RFPowerCapValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_RFPowerCapValues_ENUMTAB, 
      TS24008IE_RFPowerCapValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_RFPowerCapValues)
         TS24008IE_RFPowerCapValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_MobileStationClassmark1 */

/* TS24008IE_MobileStationClassmark2_octet4 */

/* TS24008IE_MobileStationClassmark2_octet5 */

/* TS24008IE_MobileStationClassmark2 */

int asn1Init_TS24008IE_MobileStationClassmark2 (
   TS24008IE_MobileStationClassmark2* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   return 0;
}

/* TS24008IE_MBSEnum */

const OSEnumItem TS24008IE_MBSEnum_ENUMTAB[] = {
   { OSUTF8("mbs0"), 0, 4, 0 },
   { OSUTF8("mbs1"), 1, 4, 1 },
   { OSUTF8("mbs2"), 2, 4, 2 },
   { OSUTF8("mbs4"), 4, 4, 3 },
   { OSUTF8("mbs5"), 5, 4, 4 },
   { OSUTF8("mbs6"), 6, 4, 5 }
} ;

const OSUTF8CHAR* TS24008IE_MBSEnum_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_MBSEnum_ENUMTAB, 
      TS24008IE_MBSEnum_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_MBSEnum_ENUMTABSIZE) {
      return TS24008IE_MBSEnum_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_MBSEnum_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_MBSEnum* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_MBSEnum_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_MBSEnum_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_MBSEnum* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, TS24008IE_MBSEnum_ENUMTAB, 
      TS24008IE_MBSEnum_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_MBSEnum)TS24008IE_MBSEnum_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_A5Bits */

/* TS24008IE_MultibandSupported */

int asn1Init_TS24008IE_MultibandSupported (
   TS24008IE_MultibandSupported* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   return 0;
}

/* TS24008IE_RSupport */

/* TS24008IE_HSCSDMultiSlotCap */

/* TS24008IE_MSMeasurementCap */

/* TS24008IE_Type8PSKStruct */

int asn1Init_TS24008IE_Type8PSKStruct (TS24008IE_Type8PSKStruct* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   return 0;
}

/* TS24008IE_GSM400Struct_bandsSupported */

const OSEnumItem TS24008IE_GSM400Struct_bandsSupported_ENUMTAB[] = {
   { OSUTF8("band1"), 1, 5, 0 },
   { OSUTF8("band2"), 2, 5, 1 },
   { OSUTF8("band3"), 3, 5, 2 }
} ;

const OSUTF8CHAR* TS24008IE_GSM400Struct_bandsSupported_ToString (OSINT32 value)
{
   OSINT32 idx = value - 1;

   if (idx >= 0 && idx < TS24008IE_GSM400Struct_bandsSupported_ENUMTABSIZE) {
      return TS24008IE_GSM400Struct_bandsSupported_ENUMTAB
         [TS24008IE_GSM400Struct_bandsSupported_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_GSM400Struct_bandsSupported_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_GSM400Struct_bandsSupported* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_GSM400Struct_bandsSupported_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_GSM400Struct_bandsSupported_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_GSM400Struct_bandsSupported* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_GSM400Struct_bandsSupported_ENUMTAB, 
      TS24008IE_GSM400Struct_bandsSupported_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_GSM400Struct_bandsSupported)
         TS24008IE_GSM400Struct_bandsSupported_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_GSM400Struct */

/* TS24008IE_DTMGPRSStruct */

int asn1Init_TS24008IE_DTMGPRSStruct (TS24008IE_DTMGPRSStruct* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   return 0;
}

/* TS24008IE_MobileStationClassmark3_extDtmGPRSStruct */

/* TS24008IE_GERANIuModeCap */

int asn1Init_TS24008IE_GERANIuModeCap (TS24008IE_GERANIuModeCap* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spareBits.numbits = 0;
   return 0;
}

/* TS24008IE_MobileStationClassmark3_dtmGPRSStruct2 */

int asn1Init_TS24008IE_MobileStationClassmark3_dtmGPRSStruct2 (
   TS24008IE_MobileStationClassmark3_dtmGPRSStruct2* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   return 0;
}

/* TS24008IE_MobileStationClassmark3 */

int asn1Init_TS24008IE_MobileStationClassmark3 (
   TS24008IE_MobileStationClassmark3* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_MultibandSupported (&pvalue->multiband);
   asn1Init_TS24008IE_Type8PSKStruct (&pvalue->an_8_PSKStruct);
   asn1Init_TS24008IE_DTMGPRSStruct (&pvalue->dtmGPRSStruct);
   asn1Init_TS24008IE_GERANIuModeCap (&pvalue->geranIuModeCap);
   pvalue->zerobit = FALSE;
   asn1Init_TS24008IE_MobileStationClassmark3_dtmGPRSStruct2 (&pvalue->dtmGPRSStruct2);
   pvalue->spareBits.numbits = 0;
   pvalue->spareBits.data = 0;
   return 0;
}

/* TS24008IE_DescrGroupOrBcastCallRef */

int asn1Init_TS24008IE_DescrGroupOrBcastCallRef (
   TS24008IE_DescrGroupOrBcastCallRef* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_AddnUpdateParams */

int asn1Init_TS24008IE_AddnUpdateParams (TS24008IE_AddnUpdateParams* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_CiphKeySeqNum */

/* TS24008IE_CellIdentityValue */

/* TS24008IE_LocAreaIdent */

int asn1Init_TS24008IE_LocAreaIdent (TS24008IE_LocAreaIdent* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_MCCMNCPair (&pvalue->mcc_mnc);
   return 0;
}

/* TS24008IE_GSMString */

/* TS24008IE_GroupCipherKeyNumber */

/* TS24008IE_CNCommonGSM_MAPNASSystemInformation */

/* TS24008IE_AuthParamRAND */

/* TS24008IE_AuthRespParam */

/* TS24008IE_AuthRespParamExt */

int asn1Init_TS24008IE_AuthRespParamExt (TS24008IE_AuthRespParamExt* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* TS24008IE_CMServiceType */

const OSEnumItem TS24008IE_CMServiceType_ENUMTAB[] = {
   { OSUTF8("cmServiceTypeMAX"), 15, 16, 3 },
   { OSUTF8("emerCallEstab"), 2, 13, 1 },
   { OSUTF8("locationSvcs"), 11, 12, 4 },
   { OSUTF8("mobOrigCallEstab"), 1, 16, 5 },
   { OSUTF8("sms"), 4, 3, 7 },
   { OSUTF8("suplSvcActv"), 8, 11, 6 },
   { OSUTF8("voiceBcastCallEstab"), 10, 19, 2 },
   { OSUTF8("voiceGrpCallEstab"), 9, 17, 0 }
} ;

const OSUTF8CHAR* TS24008IE_CMServiceType_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_CMServiceType_ENUMTAB, 
      TS24008IE_CMServiceType_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_CMServiceType_ENUMTABSIZE) {
      return TS24008IE_CMServiceType_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_CMServiceType_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_CMServiceType* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_CMServiceType_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_CMServiceType_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_CMServiceType* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_CMServiceType_ENUMTAB, TS24008IE_CMServiceType_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_CMServiceType)
         TS24008IE_CMServiceType_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_RejectCauseValue */

const OSEnumItem TS24008IE_RejectCauseValue_ENUMTAB[] = {
   { OSUTF8("callNotIdent"), 38, 12, 9 },
   { OSUTF8("condIEErr"), 100, 9, 7 },
   { OSUTF8("congestion"), 22, 10, 10 },
   { OSUTF8("csgNotAuth"), 25, 10, 8 },
   { OSUTF8("gsmAuthUnaccept"), 23, 15, 6 },
   { OSUTF8("ieNotExist"), 99, 10, 21 },
   { OSUTF8("illegalME"), 6, 9, 12 },
   { OSUTF8("illegalMS"), 3, 9, 24 },
   { OSUTF8("imeiNotAcc"), 5, 10, 18 },
   { OSUTF8("imsiUnkInHLR"), 2, 12, 17 },
   { OSUTF8("imsiUnkInVLR"), 4, 12, 13 },
   { OSUTF8("invMandInfo"), 96, 11, 27 },
   { OSUTF8("locNotAllow"), 12, 11, 2 },
   { OSUTF8("macFail"), 20, 7, 4 },
   { OSUTF8("msgNotCompat"), 101, 12, 3 },
   { OSUTF8("msgTypeNotCompat"), 98, 16, 26 },
   { OSUTF8("msgTypeNotExist"), 97, 15, 19 },
   { OSUTF8("networkFail"), 17, 11, 20 },
   { OSUTF8("noCellsInLoc"), 15, 12, 0 },
   { OSUTF8("notSubscribed"), 33, 13, 25 },
   { OSUTF8("outOfOrder"), 34, 10, 11 },
   { OSUTF8("plmnNotAllow"), 11, 12, 16 },
   { OSUTF8("protocolErr"), 111, 11, 15 },
   { OSUTF8("rejectCauseValueMAX"), 255, 19, 5 },
   { OSUTF8("roamNotAllow"), 13, 12, 1 },
   { OSUTF8("semIncorrectMsg"), 95, 15, 14 },
   { OSUTF8("svcOptNotSupp"), 32, 13, 22 },
   { OSUTF8("synchFail"), 21, 9, 23 }
} ;

const OSUTF8CHAR* TS24008IE_RejectCauseValue_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_RejectCauseValue_ENUMTAB, 
      TS24008IE_RejectCauseValue_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_RejectCauseValue_ENUMTABSIZE) {
      return TS24008IE_RejectCauseValue_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_RejectCauseValue_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_RejectCauseValue* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_RejectCauseValue_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_RejectCauseValue_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_RejectCauseValue* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_RejectCauseValue_ENUMTAB, 
      TS24008IE_RejectCauseValue_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_RejectCauseValue)
         TS24008IE_RejectCauseValue_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_TimeZone */

/* TS24008IE_LSAIdentifier */

int asn1Init_TS24008IE_LSAIdentifier (TS24008IE_LSAIdentifier* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* TS24008IE_LockingShiftCodesetID */

/* TS24008IE_NonLockingShiftCodesetID */

/* TS24008IE_InfoXferCap */

const OSEnumItem TS24008IE_InfoXferCap_ENUMTAB[] = {
   { OSUTF8("audio"), 2, 5, 5 },
   { OSUTF8("digital"), 1, 7, 1 },
   { OSUTF8("fax"), 3, 3, 0 },
   { OSUTF8("otherITC"), 5, 8, 2 },
   { OSUTF8("reserved"), 7, 8, 3 },
   { OSUTF8("speech"), 0, 6, 4 }
} ;

const OSUTF8CHAR* TS24008IE_InfoXferCap_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_InfoXferCap_ENUMTAB, 
      TS24008IE_InfoXferCap_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_InfoXferCap_ENUMTABSIZE) {
      return TS24008IE_InfoXferCap_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_InfoXferCap_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_InfoXferCap* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_InfoXferCap_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_InfoXferCap_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_InfoXferCap* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_InfoXferCap_ENUMTAB, TS24008IE_InfoXferCap_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_InfoXferCap)
         TS24008IE_InfoXferCap_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_CodingStandard */

const OSEnumItem TS24008IE_CodingStandard_ENUMTAB[] = {
   { OSUTF8("national"), 2, 8, 1 },
   { OSUTF8("q931"), 0, 4, 2 },
   { OSUTF8("rsvdForIntl"), 1, 11, 0 },
   { OSUTF8("stdDefForGSMPLMS"), 3, 16, 3 }
} ;

const OSUTF8CHAR* TS24008IE_CodingStandard_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_CodingStandard_ENUMTABSIZE) {
      return TS24008IE_CodingStandard_ENUMTAB
         [TS24008IE_CodingStandard_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_CodingStandard_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_CodingStandard* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_CodingStandard_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_CodingStandard_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_CodingStandard* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_CodingStandard_ENUMTAB, TS24008IE_CodingStandard_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_CodingStandard)
         TS24008IE_CodingStandard_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_NumberTypes */

const OSEnumItem TS24008IE_NumberTypes_ENUMTAB[] = {
   { OSUTF8("international"), 1, 13, 5 },
   { OSUTF8("national"), 2, 8, 0 },
   { OSUTF8("network"), 3, 7, 1 },
   { OSUTF8("ntMAX"), 7, 5, 2 },
   { OSUTF8("shortCode"), 4, 9, 4 },
   { OSUTF8("unk"), 0, 3, 3 }
} ;

const OSUTF8CHAR* TS24008IE_NumberTypes_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_NumberTypes_ENUMTAB, 
      TS24008IE_NumberTypes_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_NumberTypes_ENUMTABSIZE) {
      return TS24008IE_NumberTypes_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_NumberTypes_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_NumberTypes* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_NumberTypes_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_NumberTypes_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_NumberTypes* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_NumberTypes_ENUMTAB, TS24008IE_NumberTypes_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_NumberTypes)
         TS24008IE_NumberTypes_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_NumberPlans */

const OSEnumItem TS24008IE_NumberPlans_ENUMTAB[] = {
   { OSUTF8("data"), 3, 4, 7 },
   { OSUTF8("isdn"), 1, 4, 1 },
   { OSUTF8("national"), 8, 8, 0 },
   { OSUTF8("private"), 9, 7, 6 },
   { OSUTF8("reservedCTS"), 11, 11, 2 },
   { OSUTF8("reservedExt"), 15, 11, 3 },
   { OSUTF8("telex"), 4, 5, 4 },
   { OSUTF8("unk"), 0, 3, 5 }
} ;

const OSUTF8CHAR* TS24008IE_NumberPlans_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_NumberPlans_ENUMTAB, 
      TS24008IE_NumberPlans_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_NumberPlans_ENUMTABSIZE) {
      return TS24008IE_NumberPlans_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_NumberPlans_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_NumberPlans* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_NumberPlans_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_NumberPlans_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_NumberPlans* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_NumberPlans_ENUMTAB, TS24008IE_NumberPlans_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_NumberPlans)
         TS24008IE_NumberPlans_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_SubAddressTypes */

const OSEnumItem TS24008IE_SubAddressTypes_ENUMTAB[] = {
   { OSUTF8("nsap"), 0, 4, 0 },
   { OSUTF8("subAddrMAX"), 7, 10, 2 },
   { OSUTF8("userSpecified"), 2, 13, 1 }
} ;

const OSUTF8CHAR* TS24008IE_SubAddressTypes_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_SubAddressTypes_ENUMTAB, 
      TS24008IE_SubAddressTypes_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_SubAddressTypes_ENUMTABSIZE) {
      return TS24008IE_SubAddressTypes_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_SubAddressTypes_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_SubAddressTypes* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_SubAddressTypes_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_SubAddressTypes_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_SubAddressTypes* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_SubAddressTypes_ENUMTAB, 
      TS24008IE_SubAddressTypes_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_SubAddressTypes)
         TS24008IE_SubAddressTypes_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_Location */

const OSEnumItem TS24008IE_Location_ENUMTAB[] = {
   { OSUTF8("intlNetwork"), 7, 11, 8 },
   { OSUTF8("locationMAX"), 15, 11, 3 },
   { OSUTF8("netBeyondIntworkPt"), 10, 18, 5 },
   { OSUTF8("prvNWServLclUser"), 1, 16, 7 },
   { OSUTF8("prvNWServRemUser"), 5, 16, 6 },
   { OSUTF8("pubNWServLclUser"), 2, 16, 4 },
   { OSUTF8("pubNWServRemUser"), 4, 16, 0 },
   { OSUTF8("transit"), 3, 7, 2 },
   { OSUTF8("user"), 0, 4, 1 }
} ;

const OSUTF8CHAR* TS24008IE_Location_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_Location_ENUMTAB, 
      TS24008IE_Location_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_Location_ENUMTABSIZE) {
      return TS24008IE_Location_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_Location_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_Location* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_Location_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_Location_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_Location* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, TS24008IE_Location_ENUMTAB, 
      TS24008IE_Location_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_Location)TS24008IE_Location_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_CongestionLevel */

const OSEnumItem TS24008IE_CongestionLevel_ENUMTAB[] = {
   { OSUTF8("rcvrNotReady"), 15, 12, 1 },
   { OSUTF8("rcvrReady"), 0, 9, 0 }
} ;

const OSUTF8CHAR* TS24008IE_CongestionLevel_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_CongestionLevel_ENUMTAB, 
      TS24008IE_CongestionLevel_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_CongestionLevel_ENUMTABSIZE) {
      return TS24008IE_CongestionLevel_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_CongestionLevel_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_CongestionLevel* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_CongestionLevel_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_CongestionLevel_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_CongestionLevel* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_CongestionLevel_ENUMTAB, 
      TS24008IE_CongestionLevel_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_CongestionLevel)
         TS24008IE_CongestionLevel_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_CallingPartyBCDNumber_octet3 */

/* TS24008IE_CallingPartyBCDNumber_octet3a */

int asn1Init_TS24008IE_CallingPartyBCDNumber_octet3a (
   TS24008IE_CallingPartyBCDNumber_octet3a* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_CallingPartyBCDNumber */

int asn1Init_TS24008IE_CallingPartyBCDNumber (
   TS24008IE_CallingPartyBCDNumber* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_CallingPartyBCDNumber_octet3a (&pvalue->octet3a);
   pvalue->number = 0;
   return 0;
}

/* TS24008IE_ConnectedNumber */

int asn1Init_TS24008IE_ConnectedNumber (TS24008IE_ConnectedNumber* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_CallingPartyBCDNumber (pvalue);
   return 0;
}

/* TS24008IE_PartySubaddress_octet3 */

int asn1Init_TS24008IE_PartySubaddress_octet3 (
   TS24008IE_PartySubaddress_octet3* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_PartySubaddress */

int asn1Init_TS24008IE_PartySubaddress (TS24008IE_PartySubaddress* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_PartySubaddress_octet3 (&pvalue->octet3);
   pvalue->subaddrInfo.numocts = 0;
   return 0;
}

/* TS24008IE_ConnectedSubaddress */

int asn1Init_TS24008IE_ConnectedSubaddress (
   TS24008IE_ConnectedSubaddress* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_PartySubaddress (pvalue);
   return 0;
}

/* TS24008IE_Facility */

int asn1Init_TS24008IE_Facility (TS24008IE_Facility* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

/* TS24008IE_LowLayerCompatibility */

int asn1Init_TS24008IE_LowLayerCompatibility (
   TS24008IE_LowLayerCompatibility* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* TS24008IE_NotifIndValues */

const OSEnumItem TS24008IE_NotifIndValues_ENUMTAB[] = {
   { OSUTF8("bearerChg"), 2, 9, 3 },
   { OSUTF8("notifIndMAX"), 127, 11, 2 },
   { OSUTF8("userResumed"), 1, 11, 0 },
   { OSUTF8("userSuspended"), 0, 13, 1 }
} ;

const OSUTF8CHAR* TS24008IE_NotifIndValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_NotifIndValues_ENUMTAB, TS24008IE_NotifIndValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_NotifIndValues_ENUMTABSIZE) {
      return TS24008IE_NotifIndValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_NotifIndValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_NotifIndValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_NotifIndValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_NotifIndValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_NotifIndValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_NotifIndValues_ENUMTAB, TS24008IE_NotifIndValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_NotifIndValues)
         TS24008IE_NotifIndValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_PILocation */

const OSEnumItem TS24008IE_PILocation_ENUMTAB[] = {
   { OSUTF8("beyond"), 10, 6, 6 },
   { OSUTF8("locMAX"), 15, 6, 2 },
   { OSUTF8("privLocal"), 1, 9, 4 },
   { OSUTF8("privRemote"), 5, 10, 5 },
   { OSUTF8("pubLocal"), 2, 8, 3 },
   { OSUTF8("pubRemote"), 4, 9, 0 },
   { OSUTF8("user"), 0, 4, 1 }
} ;

const OSUTF8CHAR* TS24008IE_PILocation_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_PILocation_ENUMTAB, 
      TS24008IE_PILocation_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_PILocation_ENUMTABSIZE) {
      return TS24008IE_PILocation_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_PILocation_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_PILocation* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_PILocation_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_PILocation_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_PILocation* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, TS24008IE_PILocation_ENUMTAB, 
      TS24008IE_PILocation_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_PILocation)TS24008IE_PILocation_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_RedirectingPartyBCDNumber */

int asn1Init_TS24008IE_RedirectingPartyBCDNumber (
   TS24008IE_RedirectingPartyBCDNumber* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_CallingPartyBCDNumber (pvalue);
   return 0;
}

/* TS24008IE_RedirectingPartySubaddress */

int asn1Init_TS24008IE_RedirectingPartySubaddress (
   TS24008IE_RedirectingPartySubaddress* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_ConnectedSubaddress (pvalue);
   return 0;
}

/* TS24008IE_RepeatIndicator */

const OSEnumItem TS24008IE_RepeatIndicator_ENUMTAB[] = {
   { OSUTF8("circular"), 1, 8, 0 },
   { OSUTF8("fallbackSupp"), 2, 12, 1 },
   { OSUTF8("repeatIndMAX"), 15, 12, 3 },
   { OSUTF8("svcChgFallback"), 4, 14, 2 }
} ;

const OSUTF8CHAR* TS24008IE_RepeatIndicator_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_RepeatIndicator_ENUMTAB, 
      TS24008IE_RepeatIndicator_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_RepeatIndicator_ENUMTABSIZE) {
      return TS24008IE_RepeatIndicator_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_RepeatIndicator_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_RepeatIndicator* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_RepeatIndicator_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_RepeatIndicator_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_RepeatIndicator* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_RepeatIndicator_ENUMTAB, 
      TS24008IE_RepeatIndicator_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_RepeatIndicator)
         TS24008IE_RepeatIndicator_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_Setup_Container */

int asn1Init_TS24008IE_Setup_Container (TS24008IE_Setup_Container* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

/* TS24008IE_Signal */

const OSEnumItem TS24008IE_Signal_ENUMTAB[] = {
   { OSUTF8("alertOff"), 79, 8, 5 },
   { OSUTF8("answerOn"), 6, 8, 9 },
   { OSUTF8("busyOn"), 4, 6, 6 },
   { OSUTF8("callwaitOn"), 7, 10, 7 },
   { OSUTF8("confirmOn"), 5, 9, 2 },
   { OSUTF8("dialOn"), 0, 6, 4 },
   { OSUTF8("interceptOn"), 2, 11, 1 },
   { OSUTF8("netCongestionOn"), 3, 15, 3 },
   { OSUTF8("offhookWarnOn"), 8, 13, 8 },
   { OSUTF8("ringbackOn"), 1, 10, 11 },
   { OSUTF8("signalMAX"), 255, 9, 0 },
   { OSUTF8("tonesOff"), 63, 8, 10 }
} ;

const OSUTF8CHAR* TS24008IE_Signal_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_Signal_ENUMTAB, 
      TS24008IE_Signal_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_Signal_ENUMTABSIZE) {
      return TS24008IE_Signal_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_Signal_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_Signal* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_Signal_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_Signal_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_Signal* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, TS24008IE_Signal_ENUMTAB, 
      TS24008IE_Signal_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_Signal)TS24008IE_Signal_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_SSVersionIndicator */

int asn1Init_TS24008IE_SSVersionIndicator (
   TS24008IE_SSVersionIndicator* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

/* TS24008IE_AlertingValues */

const OSEnumItem TS24008IE_AlertingValues_ENUMTAB[] = {
   { OSUTF8("alertValMAX"), 15, 11, 1 },
   { OSUTF8("pattern1"), 0, 8, 2 },
   { OSUTF8("pattern2"), 1, 8, 3 },
   { OSUTF8("pattern3"), 2, 8, 4 },
   { OSUTF8("pattern5"), 4, 8, 5 },
   { OSUTF8("pattern6"), 5, 8, 6 },
   { OSUTF8("pattern7"), 6, 8, 7 },
   { OSUTF8("pattern8"), 7, 8, 8 },
   { OSUTF8("pattern9"), 8, 8, 0 }
} ;

const OSUTF8CHAR* TS24008IE_AlertingValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_AlertingValues_ENUMTAB, TS24008IE_AlertingValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_AlertingValues_ENUMTABSIZE) {
      return TS24008IE_AlertingValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_AlertingValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_AlertingValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_AlertingValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_AlertingValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_AlertingValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_AlertingValues_ENUMTAB, TS24008IE_AlertingValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_AlertingValues)
         TS24008IE_AlertingValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_AttachResultValues */

const OSEnumItem TS24008IE_AttachResultValues_ENUMTAB[] = {
   { OSUTF8("attachResultValMAX"), 7, 18, 2 },
   { OSUTF8("gprsAndImsi"), 3, 11, 1 },
   { OSUTF8("gprsOnly"), 1, 8, 0 }
} ;

const OSUTF8CHAR* TS24008IE_AttachResultValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_AttachResultValues_ENUMTAB, 
      TS24008IE_AttachResultValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_AttachResultValues_ENUMTABSIZE) {
      return TS24008IE_AttachResultValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_AttachResultValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_AttachResultValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_AttachResultValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_AttachResultValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_AttachResultValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_AttachResultValues_ENUMTAB, 
      TS24008IE_AttachResultValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_AttachResultValues)
         TS24008IE_AttachResultValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_IntegrityTypes */

const OSEnumItem TS24008IE_IntegrityTypes_ENUMTAB[] = {
   { OSUTF8("gia4"), 0, 4, 0 },
   { OSUTF8("gia5"), 1, 4, 1 },
   { OSUTF8("gia6"), 2, 4, 2 },
   { OSUTF8("gia7"), 3, 4, 3 },
   { OSUTF8("integrityMAX"), 7, 12, 4 }
} ;

const OSUTF8CHAR* TS24008IE_IntegrityTypes_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_IntegrityTypes_ENUMTAB, TS24008IE_IntegrityTypes_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_IntegrityTypes_ENUMTABSIZE) {
      return TS24008IE_IntegrityTypes_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_IntegrityTypes_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_IntegrityTypes* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_IntegrityTypes_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_IntegrityTypes_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_IntegrityTypes* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_IntegrityTypes_ENUMTAB, TS24008IE_IntegrityTypes_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_IntegrityTypes)
         TS24008IE_IntegrityTypes_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_IdentityTypeValue_typeOfIdent */

const OSEnumItem TS24008IE_IdentityTypeValue_typeOfIdent_ENUMTAB[] = {
   { OSUTF8("idTypeValueMAX"), 7, 14, 3 },
   { OSUTF8("imei"), 2, 4, 1 },
   { OSUTF8("imeisv"), 3, 6, 2 },
   { OSUTF8("imsi"), 1, 4, 5 },
   { OSUTF8("p-tmsi"), 5, 6, 4 },
   { OSUTF8("tmsi"), 4, 4, 0 }
} ;

const OSUTF8CHAR* TS24008IE_IdentityTypeValue_typeOfIdent_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_IdentityTypeValue_typeOfIdent_ENUMTAB, 
      TS24008IE_IdentityTypeValue_typeOfIdent_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_IdentityTypeValue_typeOfIdent_ENUMTABSIZE) {
      return TS24008IE_IdentityTypeValue_typeOfIdent_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_IdentityTypeValue_typeOfIdent_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_IdentityTypeValue_typeOfIdent* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_IdentityTypeValue_typeOfIdent_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_IdentityTypeValue_typeOfIdent_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_IdentityTypeValue_typeOfIdent* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_IdentityTypeValue_typeOfIdent_ENUMTAB, 
      TS24008IE_IdentityTypeValue_typeOfIdent_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_IdentityTypeValue_typeOfIdent)
         TS24008IE_IdentityTypeValue_typeOfIdent_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_IdentityTypeValue */

int asn1Init_TS24008IE_IdentityTypeValue (TS24008IE_IdentityTypeValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_IdentityType2Value */

int asn1Init_TS24008IE_IdentityType2Value (
   TS24008IE_IdentityType2Value* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_IdentityTypeValue (pvalue);
   return 0;
}

/* TS24008IE_DLMCNonContigIntraBandRecep */

const OSEnumItem TS24008IE_DLMCNonContigIntraBandRecep_ENUMTAB[] = {
   { OSUTF8("band-DCS1800-PCS1900"), 2, 20, 3 },
   { OSUTF8("band-EGSM-GSM850"), 1, 16, 1 },
   { OSUTF8("band-EGSM-GSM850-DCS1800-PCS1900"), 3, 32, 0 },
   { OSUTF8("nonContigIntraBandRecepNotSupp"), 0, 30, 2 }
} ;

const OSUTF8CHAR* TS24008IE_DLMCNonContigIntraBandRecep_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_DLMCNonContigIntraBandRecep_ENUMTABSIZE) {
      return TS24008IE_DLMCNonContigIntraBandRecep_ENUMTAB
         [TS24008IE_DLMCNonContigIntraBandRecep_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_DLMCNonContigIntraBandRecep_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_DLMCNonContigIntraBandRecep* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_DLMCNonContigIntraBandRecep_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_DLMCNonContigIntraBandRecep_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_DLMCNonContigIntraBandRecep* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_DLMCNonContigIntraBandRecep_ENUMTAB, 
      TS24008IE_DLMCNonContigIntraBandRecep_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_DLMCNonContigIntraBandRecep)
         TS24008IE_DLMCNonContigIntraBandRecep_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_GMMCauseValue */

/* TS24008IE_UpdateResultValues */

const OSEnumItem TS24008IE_UpdateResultValues_ENUMTAB[] = {
   { OSUTF8("raLaUpdated"), 1, 11, 2 },
   { OSUTF8("raLaUpdatedIsrActive"), 5, 20, 0 },
   { OSUTF8("raUpdated"), 0, 9, 3 },
   { OSUTF8("raUpdatedIsrActive"), 4, 18, 1 },
   { OSUTF8("updateResultValMAX"), 7, 18, 4 }
} ;

const OSUTF8CHAR* TS24008IE_UpdateResultValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_UpdateResultValues_ENUMTAB, 
      TS24008IE_UpdateResultValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_UpdateResultValues_ENUMTABSIZE) {
      return TS24008IE_UpdateResultValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_UpdateResultValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_UpdateResultValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_UpdateResultValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_UpdateResultValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_UpdateResultValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_UpdateResultValues_ENUMTAB, 
      TS24008IE_UpdateResultValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_UpdateResultValues)
         TS24008IE_UpdateResultValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_UpdateTypeValues */

const OSEnumItem TS24008IE_UpdateTypeValues_ENUMTAB[] = {
   { OSUTF8("periodicUpdating"), 3, 16, 3 },
   { OSUTF8("raLaUpdating"), 1, 12, 1 },
   { OSUTF8("raLaUpdatingImsiAttach"), 2, 22, 2 },
   { OSUTF8("raUpdating"), 0, 10, 0 },
   { OSUTF8("updateTypeValMAX"), 7, 16, 4 }
} ;

const OSUTF8CHAR* TS24008IE_UpdateTypeValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_UpdateTypeValues_ENUMTAB, 
      TS24008IE_UpdateTypeValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_UpdateTypeValues_ENUMTABSIZE) {
      return TS24008IE_UpdateTypeValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_UpdateTypeValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_UpdateTypeValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_UpdateTypeValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_UpdateTypeValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_UpdateTypeValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_UpdateTypeValues_ENUMTAB, 
      TS24008IE_UpdateTypeValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_UpdateTypeValues)
         TS24008IE_UpdateTypeValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_AC_Reference_Number */

/* TS24008IE_ServiceTypeValues */

const OSEnumItem TS24008IE_ServiceTypeValues_ENUMTAB[] = {
   { OSUTF8("broadcast"), 4, 9, 5 },
   { OSUTF8("data"), 1, 4, 1 },
   { OSUTF8("multicast"), 3, 9, 3 },
   { OSUTF8("pagingResp"), 2, 10, 2 },
   { OSUTF8("serviceTypeValMAX"), 7, 17, 0 },
   { OSUTF8("signaling"), 0, 9, 4 }
} ;

const OSUTF8CHAR* TS24008IE_ServiceTypeValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_ServiceTypeValues_ENUMTAB, 
      TS24008IE_ServiceTypeValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_ServiceTypeValues_ENUMTABSIZE) {
      return TS24008IE_ServiceTypeValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_ServiceTypeValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_ServiceTypeValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_ServiceTypeValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_ServiceTypeValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_ServiceTypeValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_ServiceTypeValues_ENUMTAB, 
      TS24008IE_ServiceTypeValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_ServiceTypeValues)
         TS24008IE_ServiceTypeValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_InterRATInfoContainer */

int asn1Init_TS24008IE_InterRATInfoContainer (
   TS24008IE_InterRATInfoContainer* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* TS24008IE_E_UTRANInterRATInfoContainer */

int asn1Init_TS24008IE_E_UTRANInterRATInfoContainer (
   TS24008IE_E_UTRANInterRATInfoContainer* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

/* TS24008IE_MsgAuthCode */

/* TS24008IE_DcnID */

/* TS24008IE_AccessPointName */

/* TS24008IE_NSAPIValues */

const OSEnumItem TS24008IE_NSAPIValues_ENUMTAB[] = {
   { OSUTF8("nsapi10"), 10, 7, 6 },
   { OSUTF8("nsapi11"), 11, 7, 7 },
   { OSUTF8("nsapi12"), 12, 7, 8 },
   { OSUTF8("nsapi13"), 13, 7, 9 },
   { OSUTF8("nsapi14"), 14, 7, 10 },
   { OSUTF8("nsapi15"), 15, 7, 0 },
   { OSUTF8("nsapi5"), 5, 6, 1 },
   { OSUTF8("nsapi6"), 6, 6, 2 },
   { OSUTF8("nsapi7"), 7, 6, 3 },
   { OSUTF8("nsapi8"), 8, 6, 4 },
   { OSUTF8("nsapi9"), 9, 6, 5 }
} ;

const OSUTF8CHAR* TS24008IE_NSAPIValues_ToString (OSINT32 value)
{
   OSINT32 idx = value - 5;

   if (idx >= 0 && idx < TS24008IE_NSAPIValues_ENUMTABSIZE) {
      return TS24008IE_NSAPIValues_ENUMTAB
         [TS24008IE_NSAPIValues_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_NSAPIValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_NSAPIValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_NSAPIValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_NSAPIValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_NSAPIValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_NSAPIValues_ENUMTAB, TS24008IE_NSAPIValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_NSAPIValues)
         TS24008IE_NSAPIValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_SMCauseValue */

/* TS24008IE_SMCause2Value */

/* TS24008IE_SAPIValues */

const OSEnumItem TS24008IE_SAPIValues_ENUMTAB[] = {
   { OSUTF8("sapi11"), 11, 6, 5 },
   { OSUTF8("sapi3"), 3, 5, 1 },
   { OSUTF8("sapi5"), 5, 5, 2 },
   { OSUTF8("sapi9"), 9, 5, 3 },
   { OSUTF8("sapiMAX"), 15, 7, 0 },
   { OSUTF8("unassigned"), 0, 10, 4 }
} ;

const OSUTF8CHAR* TS24008IE_SAPIValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_SAPIValues_ENUMTAB, 
      TS24008IE_SAPIValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_SAPIValues_ENUMTABSIZE) {
      return TS24008IE_SAPIValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_SAPIValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_SAPIValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_SAPIValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_SAPIValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_SAPIValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, TS24008IE_SAPIValues_ENUMTAB, 
      TS24008IE_SAPIValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_SAPIValues)TS24008IE_SAPIValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_TFTPacketFilterComponentType */

const OSEnumItem TS24008IE_TFTPacketFilterComponentType_ENUMTAB[] = {
   { OSUTF8("flowLabel"), 128, 9, 2 },
   { OSUTF8("ipv4Local"), 17, 9, 1 },
   { OSUTF8("ipv4Remote"), 16, 10, 4 },
   { OSUTF8("ipv6LocalAddrPrefixLen"), 35, 22, 5 },
   { OSUTF8("ipv6Remote"), 32, 10, 3 },
   { OSUTF8("ipv6RemoteAddrPrefixLen"), 33, 23, 7 },
   { OSUTF8("localPortRange"), 65, 14, 10 },
   { OSUTF8("protoIdNextHdr"), 48, 14, 6 },
   { OSUTF8("remotePortRange"), 81, 15, 11 },
   { OSUTF8("secParamIndex"), 96, 13, 8 },
   { OSUTF8("singleLocalPort"), 64, 15, 9 },
   { OSUTF8("singleRemotePort"), 80, 16, 13 },
   { OSUTF8("typeMax"), 255, 7, 0 },
   { OSUTF8("typeOfSvcTrafficClass"), 112, 21, 12 }
} ;

const OSUTF8CHAR* TS24008IE_TFTPacketFilterComponentType_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_TFTPacketFilterComponentType_ENUMTAB, 
      TS24008IE_TFTPacketFilterComponentType_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_TFTPacketFilterComponentType_ENUMTABSIZE) {
      return TS24008IE_TFTPacketFilterComponentType_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_TFTPacketFilterComponentType_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_TFTPacketFilterComponentType* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_TFTPacketFilterComponentType_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_TFTPacketFilterComponentType_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_TFTPacketFilterComponentType* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_TFTPacketFilterComponentType_ENUMTAB, 
      TS24008IE_TFTPacketFilterComponentType_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_TFTPacketFilterComponentType)
         TS24008IE_TFTPacketFilterComponentType_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_TFTParamId */

const OSEnumItem TS24008IE_TFTParamId_ENUMTAB[] = {
   { OSUTF8("authToken"), 1, 9, 0 },
   { OSUTF8("flowId"), 2, 6, 1 },
   { OSUTF8("packetFilterId"), 3, 14, 2 },
   { OSUTF8("tftParamIdMax"), 255, 13, 3 }
} ;

const OSUTF8CHAR* TS24008IE_TFTParamId_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_TFTParamId_ENUMTAB, 
      TS24008IE_TFTParamId_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_TFTParamId_ENUMTABSIZE) {
      return TS24008IE_TFTParamId_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_TFTParamId_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_TFTParamId* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_TFTParamId_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_TFTParamId_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_TFTParamId* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, TS24008IE_TFTParamId_ENUMTAB, 
      TS24008IE_TFTParamId_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_TFTParamId)TS24008IE_TFTParamId_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_MBMS_PCO */

int asn1Init_TS24008IE_MBMS_PCO (TS24008IE_MBMS_PCO* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

/* TS24008IE_EnhancedNSAPIValue */

/* TS24008IE_ReqTypeValues */

const OSEnumItem TS24008IE_ReqTypeValues_ENUMTAB[] = {
   { OSUTF8("emergency"), 4, 9, 3 },
   { OSUTF8("handover"), 2, 8, 1 },
   { OSUTF8("handoverEmerSvcs"), 6, 16, 5 },
   { OSUTF8("initialReq"), 1, 10, 0 },
   { OSUTF8("reqTypeMAX"), 7, 10, 2 },
   { OSUTF8("rlos"), 3, 4, 4 }
} ;

const OSUTF8CHAR* TS24008IE_ReqTypeValues_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, TS24008IE_ReqTypeValues_ENUMTAB, 
      TS24008IE_ReqTypeValues_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_ReqTypeValues_ENUMTABSIZE) {
      return TS24008IE_ReqTypeValues_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_ReqTypeValues_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_ReqTypeValues* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_ReqTypeValues_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_ReqTypeValues_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_ReqTypeValues* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_ReqTypeValues_ENUMTAB, TS24008IE_ReqTypeValues_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_ReqTypeValues)
         TS24008IE_ReqTypeValues_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_SM_NotificationIndicator */

/* TS24008IE_ConnectivityType */

/* TS24008IE_NBIFOMContainer */

int asn1Init_TS24008IE_NBIFOMContainer (TS24008IE_NBIFOMContainer* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

/* TS24008IE_RadioPriority */

int asn1Init_TS24008IE_RadioPriority (TS24008IE_RadioPriority* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_RadioPriority2 */

int asn1Init_TS24008IE_RadioPriority2 (TS24008IE_RadioPriority2* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_RadioPriority (pvalue);
   return 0;
}

/* TS24008IE_MBMSContextStatus */

int asn1Init_TS24008IE_MBMSContextStatus (TS24008IE_MBMSContextStatus* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* TS24008IE_LocationUpdatingType_lut */

const OSEnumItem TS24008IE_LocationUpdatingType_lut_ENUMTAB[] = {
   { OSUTF8("imsiAttach"), 2, 10, 1 },
   { OSUTF8("normLocUpdate"), 0, 13, 2 },
   { OSUTF8("periodicUpdate"), 1, 14, 0 },
   { OSUTF8("reserved"), 3, 8, 3 }
} ;

const OSUTF8CHAR* TS24008IE_LocationUpdatingType_lut_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_LocationUpdatingType_lut_ENUMTABSIZE) {
      return TS24008IE_LocationUpdatingType_lut_ENUMTAB
         [TS24008IE_LocationUpdatingType_lut_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_LocationUpdatingType_lut_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_LocationUpdatingType_lut* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_LocationUpdatingType_lut_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_LocationUpdatingType_lut_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_LocationUpdatingType_lut* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_LocationUpdatingType_lut_ENUMTAB, 
      TS24008IE_LocationUpdatingType_lut_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_LocationUpdatingType_lut)
         TS24008IE_LocationUpdatingType_lut_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_NetworkName_codingScheme */

const OSEnumItem TS24008IE_NetworkName_codingScheme_ENUMTAB[] = {
   { OSUTF8("callBcastData"), 0, 13, 0 },
   { OSUTF8("codingSchemeMAX"), 7, 15, 2 },
   { OSUTF8("ucs2"), 1, 4, 1 }
} ;

const OSUTF8CHAR* TS24008IE_NetworkName_codingScheme_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, 
      TS24008IE_NetworkName_codingScheme_ENUMTAB, 
      TS24008IE_NetworkName_codingScheme_ENUMTABSIZE);

   if (idx >= 0 && idx < TS24008IE_NetworkName_codingScheme_ENUMTABSIZE) {
      return TS24008IE_NetworkName_codingScheme_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_NetworkName_codingScheme_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_NetworkName_codingScheme* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_NetworkName_codingScheme_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_NetworkName_codingScheme_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_NetworkName_codingScheme* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_NetworkName_codingScheme_ENUMTAB, 
      TS24008IE_NetworkName_codingScheme_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_NetworkName_codingScheme)
         TS24008IE_NetworkName_codingScheme_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_DaylightSavingTime_dst */

const OSEnumItem TS24008IE_DaylightSavingTime_dst_ENUMTAB[] = {
   { OSUTF8("dstNoAdjust"), 0, 11, 0 },
   { OSUTF8("dstPlus1"), 1, 8, 1 },
   { OSUTF8("dstPlus2"), 2, 8, 2 },
   { OSUTF8("dstReserved"), 3, 11, 3 }
} ;

const OSUTF8CHAR* TS24008IE_DaylightSavingTime_dst_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_DaylightSavingTime_dst_ENUMTABSIZE) {
      return TS24008IE_DaylightSavingTime_dst_ENUMTAB
         [TS24008IE_DaylightSavingTime_dst_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_DaylightSavingTime_dst_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_DaylightSavingTime_dst* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_DaylightSavingTime_dst_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_DaylightSavingTime_dst_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_DaylightSavingTime_dst* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_DaylightSavingTime_dst_ENUMTAB, 
      TS24008IE_DaylightSavingTime_dst_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_DaylightSavingTime_dst)
         TS24008IE_DaylightSavingTime_dst_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_SupportedCodec_codecBitmap */

int asn1Init_TS24008IE_SupportedCodec_codecBitmap (
   TS24008IE_SupportedCodec_codecBitmap* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* TS24008IE_AccessCapability_ec_pchMonSupp */

const OSEnumItem TS24008IE_AccessCapability_ec_pchMonSupp_ENUMTAB[] = {
   { OSUTF8("ec-pchMonReserved"), 3, 17, 3 },
   { OSUTF8("ecPchSupported"), 1, 14, 1 },
   { OSUTF8("pchAndEcPchSupported"), 2, 20, 2 },
   { OSUTF8("pchSupported"), 0, 12, 0 }
} ;

const OSUTF8CHAR* TS24008IE_AccessCapability_ec_pchMonSupp_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_AccessCapability_ec_pchMonSupp_ENUMTABSIZE) {
      return TS24008IE_AccessCapability_ec_pchMonSupp_ENUMTAB
         [TS24008IE_AccessCapability_ec_pchMonSupp_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_AccessCapability_ec_pchMonSupp_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_AccessCapability_ec_pchMonSupp* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_AccessCapability_ec_pchMonSupp_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_AccessCapability_ec_pchMonSupp_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_AccessCapability_ec_pchMonSupp* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_AccessCapability_ec_pchMonSupp_ENUMTAB, 
      TS24008IE_AccessCapability_ec_pchMonSupp_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_AccessCapability_ec_pchMonSupp)
         TS24008IE_AccessCapability_ec_pchMonSupp_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_DLMCCapability_maxBandwidth */

const OSEnumItem TS24008IE_DLMCCapability_maxBandwidth_ENUMTAB[] = {
   { OSUTF8("bw10MHz"), 1, 7, 3 },
   { OSUTF8("bw15MHz"), 2, 7, 0 },
   { OSUTF8("bw20MHz"), 3, 7, 1 },
   { OSUTF8("bw5MHz"), 0, 6, 2 }
} ;

const OSUTF8CHAR* TS24008IE_DLMCCapability_maxBandwidth_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_DLMCCapability_maxBandwidth_ENUMTABSIZE) {
      return TS24008IE_DLMCCapability_maxBandwidth_ENUMTAB
         [TS24008IE_DLMCCapability_maxBandwidth_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_DLMCCapability_maxBandwidth_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_DLMCCapability_maxBandwidth* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_DLMCCapability_maxBandwidth_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_DLMCCapability_maxBandwidth_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_DLMCCapability_maxBandwidth* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_DLMCCapability_maxBandwidth_ENUMTAB, 
      TS24008IE_DLMCCapability_maxBandwidth_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_DLMCCapability_maxBandwidth)
         TS24008IE_DLMCCapability_maxBandwidth_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_VoiceDomainPref_enumValue */

const OSEnumItem TS24008IE_VoiceDomainPref_enumValue_ENUMTAB[] = {
   { OSUTF8("csVoiceOnly"), 0, 11, 0 },
   { OSUTF8("csVoicePref"), 2, 11, 2 },
   { OSUTF8("imsPsVoiceOnly"), 1, 14, 1 },
   { OSUTF8("imsPsVoicePref"), 3, 14, 3 }
} ;

const OSUTF8CHAR* TS24008IE_VoiceDomainPref_enumValue_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_VoiceDomainPref_enumValue_ENUMTABSIZE) {
      return TS24008IE_VoiceDomainPref_enumValue_ENUMTAB
         [TS24008IE_VoiceDomainPref_enumValue_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_VoiceDomainPref_enumValue_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_VoiceDomainPref_enumValue* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_VoiceDomainPref_enumValue_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_VoiceDomainPref_enumValue_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_VoiceDomainPref_enumValue* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_VoiceDomainPref_enumValue_ENUMTAB, 
      TS24008IE_VoiceDomainPref_enumValue_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_VoiceDomainPref_enumValue)
         TS24008IE_VoiceDomainPref_enumValue_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_TFTOctet1_tftOperationCode */

const OSEnumItem TS24008IE_TFTOctet1_tftOperationCode_ENUMTAB[] = {
   { OSUTF8("addPktFilters"), 3, 13, 4 },
   { OSUTF8("createTFT"), 1, 9, 1 },
   { OSUTF8("delPktFilters"), 5, 13, 3 },
   { OSUTF8("deleteTFT"), 2, 9, 0 },
   { OSUTF8("ignoreThisIE"), 0, 12, 6 },
   { OSUTF8("noTFTOp"), 6, 7, 2 },
   { OSUTF8("replPktFilters"), 4, 14, 5 }
} ;

const OSUTF8CHAR* TS24008IE_TFTOctet1_tftOperationCode_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_TFTOctet1_tftOperationCode_ENUMTABSIZE) {
      return TS24008IE_TFTOctet1_tftOperationCode_ENUMTAB
         [TS24008IE_TFTOctet1_tftOperationCode_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_TFTOctet1_tftOperationCode_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_TFTOctet1_tftOperationCode* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_TFTOctet1_tftOperationCode_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_TFTOctet1_tftOperationCode_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      TS24008IE_TFTOctet1_tftOperationCode* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_TFTOctet1_tftOperationCode_ENUMTAB, 
      TS24008IE_TFTOctet1_tftOperationCode_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_TFTOctet1_tftOperationCode)
         TS24008IE_TFTOctet1_tftOperationCode_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_GPRSTimer3_unit */

const OSEnumItem TS24008IE_GPRSTimer3_unit_ENUMTAB[] = {
   { OSUTF8("timerDeact"), 7, 10, 1 },
   { OSUTF8("valIncrMult10Mins"), 0, 17, 3 },
   { OSUTF8("valIncrMult10hrs"), 2, 16, 2 },
   { OSUTF8("valIncrMult1Hr"), 1, 14, 5 },
   { OSUTF8("valIncrMult1Min"), 5, 15, 6 },
   { OSUTF8("valIncrMult2Secs"), 3, 16, 4 },
   { OSUTF8("valIncrMult30Secs"), 4, 17, 7 },
   { OSUTF8("valIncrMult320Hrs"), 6, 17, 0 }
} ;

const OSUTF8CHAR* TS24008IE_GPRSTimer3_unit_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TS24008IE_GPRSTimer3_unit_ENUMTABSIZE) {
      return TS24008IE_GPRSTimer3_unit_ENUMTAB
         [TS24008IE_GPRSTimer3_unit_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TS24008IE_GPRSTimer3_unit_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TS24008IE_GPRSTimer3_unit* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return TS24008IE_GPRSTimer3_unit_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int TS24008IE_GPRSTimer3_unit_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, TS24008IE_GPRSTimer3_unit* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      TS24008IE_GPRSTimer3_unit_ENUMTAB, 
      TS24008IE_GPRSTimer3_unit_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TS24008IE_GPRSTimer3_unit)
         TS24008IE_GPRSTimer3_unit_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/* TS24008IE_PDAndSAPI */

int asn1Init_TS24008IE_PDAndSAPI (TS24008IE_PDAndSAPI* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_PriorityLevel */

/* TS24008IE_CSDomainSpecificSystemInformation */

int asn1Init_TS24008IE_CSDomainSpecificSystemInformation (
   TS24008IE_CSDomainSpecificSystemInformation* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_PSDomainSpecificSystemInformation */

int asn1Init_TS24008IE_PSDomainSpecificSystemInformation (
   TS24008IE_PSDomainSpecificSystemInformation* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_PLMNList */

int asn1Init_TS24008IE_PLMNList (TS24008IE_PLMNList* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->n = 0;
   return 0;
}

/* TS24008IE_NASContainerForPSHO */

int asn1Init_TS24008IE_NASContainerForPSHO (
   TS24008IE_NASContainerForPSHO* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare1 = 0;
   pvalue->spare2 = FALSE;
   return 0;
}

/* TS24008IE_MSNetFeatureSupport */

int asn1Init_TS24008IE_MSNetFeatureSupport (
   TS24008IE_MSNetFeatureSupport* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_AuthParamAUTN */

int asn1Init_TS24008IE_AuthParamAUTN (TS24008IE_AuthParamAUTN* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->length = 16;
   return 0;
}

/* TS24008IE_AuthFailureParam */

int asn1Init_TS24008IE_AuthFailureParam (TS24008IE_AuthFailureParam* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->length = 14;
   return 0;
}

/* TS24008IE_LocationUpdatingType */

int asn1Init_TS24008IE_LocationUpdatingType (
   TS24008IE_LocationUpdatingType* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_NetworkName */

int asn1Init_TS24008IE_NetworkName (TS24008IE_NetworkName* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->ext = TRUE;
   OSCRTLMEMSET (&pvalue->textString.u, 0, sizeof(pvalue->textString.u));
   return 0;
}

/* TS24008IE_TimeZoneAndTime */

/* TS24008IE_DaylightSavingTime */

int asn1Init_TS24008IE_DaylightSavingTime (
   TS24008IE_DaylightSavingTime* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_EmergencyNumber */

int asn1Init_TS24008IE_EmergencyNumber (TS24008IE_EmergencyNumber* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   pvalue->digits = 0;
   return 0;
}

/* TS24008IE_EmergencyNumberList */

int asn1Init_TS24008IE_EmergencyNumberList (
   TS24008IE_EmergencyNumberList* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numbers.n = 0;
   return 0;
}

/* TS24008IE_MMTimer */

/* TS24008IE_AuxiliaryStates */

int asn1Init_TS24008IE_AuxiliaryStates (TS24008IE_AuxiliaryStates* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->ext = TRUE;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_BearerCapOctet3 */

/* TS24008IE_BearerCapOctet4 */

/* TS24008IE_BearerCapOctet5 */

/* TS24008IE_BearerCapOctet5a */

int asn1Init_TS24008IE_BearerCapOctet5a (TS24008IE_BearerCapOctet5a* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_BearerCapOctet6 */

/* TS24008IE_BearerCapOctet6a */

/* TS24008IE_BearerCapOctet6b */

/* TS24008IE_BearerCapOctet6c */

/* TS24008IE_BearerCapOctet6d */

/* TS24008IE_BearerCapOctet6e */

/* TS24008IE_BearerCapOctet6f */

/* TS24008IE_BearerCapOctet6g */

int asn1Init_TS24008IE_BearerCapOctet6g (TS24008IE_BearerCapOctet6g* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_BearerCapOctet7 */

/* TS24008IE_BackupBearerCapability */

int asn1Init_TS24008IE_BackupBearerCapability (
   TS24008IE_BackupBearerCapability* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_BearerCapOctet5a (&pvalue->octet5a);
   asn1Init_TS24008IE_BearerCapOctet6g (&pvalue->octet6g);
   return 0;
}

/* TS24008IE_BearerCapOctet3a */

int asn1Init_TS24008IE_BearerCapOctet3a (TS24008IE_BearerCapOctet3a* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_BearerCapOctet3b */

int asn1Init_TS24008IE_BearerCapOctet3b (TS24008IE_BearerCapOctet3b* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_BearerCapOctet3bList */

int asn1Init_TS24008IE_BearerCapOctet3bList (
   TS24008IE_BearerCapOctet3bList* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->elem = 0;
   pvalue->n = 0;
   return 0;
}

/* TS24008IE_BearerCapOctet5b */

int asn1Init_TS24008IE_BearerCapOctet5b (TS24008IE_BearerCapOctet5b* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_BearerCapability */

int asn1Init_TS24008IE_BearerCapability (TS24008IE_BearerCapability* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_BearerCapOctet3a (&pvalue->octet3a);
   asn1Init_TS24008IE_BearerCapOctet3bList (&pvalue->octet3b);
   asn1Init_TS24008IE_BearerCapOctet5a (&pvalue->octet5a);
   asn1Init_TS24008IE_BearerCapOctet5b (&pvalue->octet5b);
   asn1Init_TS24008IE_BearerCapOctet6g (&pvalue->octet6g);
   return 0;
}

/* TS24008IE_CallControlCapabilities */

int asn1Init_TS24008IE_CallControlCapabilities (
   TS24008IE_CallControlCapabilities* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->length = 2;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_CallState */

/* TS24008IE_CalledPartyBCDNumber_octet3 */

/* TS24008IE_CalledPartyBCDNumber */

int asn1Init_TS24008IE_CalledPartyBCDNumber (
   TS24008IE_CalledPartyBCDNumber* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->number = 0;
   return 0;
}

/* TS24008IE_Cause_octet3 */

int asn1Init_TS24008IE_Cause_octet3 (TS24008IE_Cause_octet3* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_Cause */

int asn1Init_TS24008IE_Cause (TS24008IE_Cause* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_Cause_octet3 (&pvalue->octet3);
   pvalue->diagnostics.numocts = 0;
   return 0;
}

/* TS24008IE_HighLayerCompatibility_octet3 */

/* TS24008IE_HighLayerCompatibility */

int asn1Init_TS24008IE_HighLayerCompatibility (
   TS24008IE_HighLayerCompatibility* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   return 0;
}

/* TS24008IE_KeypadFacilityInfo */

int asn1Init_TS24008IE_KeypadFacilityInfo (
   TS24008IE_KeypadFacilityInfo* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_NotificationIndicator */

int asn1Init_TS24008IE_NotificationIndicator (
   TS24008IE_NotificationIndicator* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->ext = TRUE;
   return 0;
}

/* TS24008IE_ProgressIndicator_octet3 */

int asn1Init_TS24008IE_ProgressIndicator_octet3 (
   TS24008IE_ProgressIndicator_octet3* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_ProgressIndicator */

int asn1Init_TS24008IE_ProgressIndicator (TS24008IE_ProgressIndicator* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->length = 2;
   asn1Init_TS24008IE_ProgressIndicator_octet3 (&pvalue->octet3);
   return 0;
}

/* TS24008IE_RecallType */

int asn1Init_TS24008IE_RecallType (TS24008IE_RecallType* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_UserUser */

int asn1Init_TS24008IE_UserUser (TS24008IE_UserUser* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->uuInfo.numocts = 0;
   pvalue->uuInfo.data = 0;
   return 0;
}

/* TS24008IE_AlertingPattern */

int asn1Init_TS24008IE_AlertingPattern (TS24008IE_AlertingPattern* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_AllowedActions */

int asn1Init_TS24008IE_AllowedActions (TS24008IE_AllowedActions* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_StreamIdentifierValue */

/* TS24008IE_NetCallCtrlCaps */

int asn1Init_TS24008IE_NetCallCtrlCaps (TS24008IE_NetCallCtrlCaps* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_CauseOfNoCLI */

/* TS24008IE_SupportedCodec */

int asn1Init_TS24008IE_SupportedCodec (TS24008IE_SupportedCodec* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_SupportedCodec_codecBitmap (&pvalue->codecBitmap);
   return 0;
}

/* TS24008IE_SupportedCodecList */

int asn1Init_TS24008IE_SupportedCodecList (
   TS24008IE_SupportedCodecList* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->codecs.n = 0;
   return 0;
}

/* TS24008IE_ServiceCategoryValue */

int asn1Init_TS24008IE_ServiceCategoryValue (
   TS24008IE_ServiceCategoryValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_AddnUpdateType */

/* TS24008IE_AttachResult */

/* TS24008IE_AttachType */

/* TS24008IE_CipheringAlgorithmType */

int asn1Init_TS24008IE_CipheringAlgorithmType (
   TS24008IE_CipheringAlgorithmType* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_IntegrityAlgorithmType */

int asn1Init_TS24008IE_IntegrityAlgorithmType (
   TS24008IE_IntegrityAlgorithmType* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_TMSIStatus */

int asn1Init_TS24008IE_TMSIStatus (TS24008IE_TMSIStatus* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_DetachType */

/* TS24008IE_DRXParameter */

/* TS24008IE_ForceToStandbyValue */

int asn1Init_TS24008IE_ForceToStandbyValue (
   TS24008IE_ForceToStandbyValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_P_TMSISignature */

/* TS24008IE_P_TMSISignature2 */

int asn1Init_TS24008IE_P_TMSISignature2 (TS24008IE_P_TMSISignature2* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->length = 3;
   return 0;
}

/* TS24008IE_IMEISVRequest */

int asn1Init_TS24008IE_IMEISVRequest (TS24008IE_IMEISVRequest* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_ReceiveNPDUNumber */

/* TS24008IE_ReceiveNPDUNumberList */

int asn1Init_TS24008IE_ReceiveNPDUNumberList (
   TS24008IE_ReceiveNPDUNumberList* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->receiveNPDUNumber.elem = 0;
   pvalue->receiveNPDUNumber.n = 0;
   return 0;
}

/* TS24008IE_MSNetworkCapability */

int asn1Init_TS24008IE_MSNetworkCapability (
   TS24008IE_MSNetworkCapability* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->spareBits.numbits = 0;
   pvalue->spareBits.data = 0;
   return 0;
}

/* TS24008IE_MultislotCapability_gprsMSC */

/* TS24008IE_MultislotCapability_egprsMSC */

/* TS24008IE_MultislotCapability */

int asn1Init_TS24008IE_MultislotCapability (
   TS24008IE_MultislotCapability* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_DTMGPRSStruct (&pvalue->dtmGPRSStruct);
   return 0;
}

/* TS24008IE_EnhanFlexTimeSlotAssnStruct */

/* TS24008IE_AddAccessTechStruct */

/* TS24008IE_AddAccessTechStructList */

int asn1Init_TS24008IE_AddAccessTechStructList (
   TS24008IE_AddAccessTechStructList* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->elem = 0;
   pvalue->n = 0;
   return 0;
}

/* TS24008IE_AdditionalAccessTech */

int asn1Init_TS24008IE_AdditionalAccessTech (
   TS24008IE_AdditionalAccessTech* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_AddAccessTechStructList (&pvalue->content);
   pvalue->spareBits.numbits = 0;
   pvalue->spareBits.data = 0;
   return 0;
}

/* TS24008IE_AccessCapability_extGPRSMSC */

/* TS24008IE_AccessCapability_dtmGPRSHighMSC */

int asn1Init_TS24008IE_AccessCapability_dtmGPRSHighMSC (
   TS24008IE_AccessCapability_dtmGPRSHighMSC* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   return 0;
}

/* TS24008IE_AccessCapability_downlinkDualCarrierCap */

/* TS24008IE_DLMCCapability */

int asn1Init_TS24008IE_DLMCCapability (TS24008IE_DLMCCapability* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   return 0;
}

/* TS24008IE_AccessCapability */

int asn1Init_TS24008IE_AccessCapability (TS24008IE_AccessCapability* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24008IE_MultislotCapability (&pvalue->multislotCap);
   asn1Init_TS24008IE_GERANIuModeCap (&pvalue->geranIuModeCap);
   asn1Init_TS24008IE_AccessCapability_dtmGPRSHighMSC (&pvalue->dtmGPRSHighMSC);
   asn1Init_TS24008IE_DLMCCapability (&pvalue->dlmcCap);
   pvalue->spareBits.numbits = 0;
   pvalue->spareBits.data = 0;
   return 0;
}

/* TS24008IE_MSRACapValuePartStruct */

int asn1Init_TS24008IE_MSRACapValuePartStruct (
   TS24008IE_MSRACapValuePartStruct* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->accessCapOrTech.u, 0, sizeof(pvalue->accessCapOrTech.u));
   return 0;
}

/* TS24008IE_MSRadioAccessCapability */

int asn1Init_TS24008IE_MSRadioAccessCapability (
   TS24008IE_MSRadioAccessCapability* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_MSRACapValuePartStruct (&pvalue->firstRec);
   pvalue->additionalRecs.elem = 0;
   pvalue->additionalRecs.n = 0;
   return 0;
}

/* TS24008IE_RoutingAreaIdent2 */

int asn1Init_TS24008IE_RoutingAreaIdent2 (TS24008IE_RoutingAreaIdent2* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_RoutingAreaIdent (&pvalue->value);
   return 0;
}

/* TS24008IE_UpdateResult */

/* TS24008IE_UpdateType */

/* TS24008IE_ServiceType */

int asn1Init_TS24008IE_ServiceType (TS24008IE_ServiceType* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_PS_LCSCapbility */

int asn1Init_TS24008IE_PS_LCSCapbility (TS24008IE_PS_LCSCapbility* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_NetFeatureSupp */

/* TS24008IE_AddnNetFeatureSupport */

int asn1Init_TS24008IE_AddnNetFeatureSupport (
   TS24008IE_AddnNetFeatureSupport* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_RequestedMSInfo */

int asn1Init_TS24008IE_RequestedMSInfo (TS24008IE_RequestedMSInfo* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_VoiceDomainPref */

int asn1Init_TS24008IE_VoiceDomainPref (TS24008IE_VoiceDomainPref* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_P_TMSI_Type */

int asn1Init_TS24008IE_P_TMSI_Type (TS24008IE_P_TMSI_Type* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_LocAreaIdent2 */

int asn1Init_TS24008IE_LocAreaIdent2 (TS24008IE_LocAreaIdent2* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_LocAreaIdent (&pvalue->value);
   return 0;
}

/* TS24008IE_NetResourceIdentContainer */

int asn1Init_TS24008IE_NetResourceIdentContainer (
   TS24008IE_NetResourceIdentContainer* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_ExtDRXParams */

/* TS24008IE_UserPlaneIntegInd */

int asn1Init_TS24008IE_UserPlaneIntegInd (TS24008IE_UserPlaneIntegInd* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare4 = FALSE;
   pvalue->spare3 = FALSE;
   pvalue->spare2 = FALSE;
   return 0;
}

/* TS24008IE_PlmnCnID */

int asn1Init_TS24008IE_PlmnCnID (TS24008IE_PlmnCnID* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_MCCMNCPair (&pvalue->mcc_mnc);
   return 0;
}

/* TS24008IE_Non3GPPNetPolicies */

int asn1Init_TS24008IE_Non3GPPNetPolicies (
   TS24008IE_Non3GPPNetPolicies* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare4 = FALSE;
   pvalue->spare3 = FALSE;
   pvalue->spare2 = FALSE;
   return 0;
}

/* TS24008IE_NSAPIValue */

int asn1Init_TS24008IE_NSAPIValue (TS24008IE_NSAPIValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_PCOUnit */

int asn1Init_TS24008IE_PCOUnit (TS24008IE_PCOUnit* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->contents.numocts = 0;
   pvalue->contents.data = 0;
   return 0;
}

/* TS24008IE_ProtocolConfigOptions_octet3 */

int asn1Init_TS24008IE_ProtocolConfigOptions_octet3 (
   TS24008IE_ProtocolConfigOptions_octet3* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_ProtocolConfigOptions */

int asn1Init_TS24008IE_ProtocolConfigOptions (
   TS24008IE_ProtocolConfigOptions* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_ProtocolConfigOptions_octet3 (&pvalue->octet3);
   pvalue->pcoUnits.elem = 0;
   pvalue->pcoUnits.n = 0;
   return 0;
}

/* TS24008IE_ExtProtoConfigOptions_octet4 */

int asn1Init_TS24008IE_ExtProtoConfigOptions_octet4 (
   TS24008IE_ExtProtoConfigOptions_octet4* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_ExtProtoConfigOptions */

int asn1Init_TS24008IE_ExtProtoConfigOptions (
   TS24008IE_ExtProtoConfigOptions* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_ExtProtoConfigOptions_octet4 (&pvalue->octet4);
   pvalue->pcoUnits.elem = 0;
   pvalue->pcoUnits.n = 0;
   return 0;
}

/* TS24008IE_PacketDataProtoAddr */

int asn1Init_TS24008IE_PacketDataProtoAddr (
   TS24008IE_PacketDataProtoAddr* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   pvalue->addressInfo.numocts = 0;
   return 0;
}

/* TS24008IE_QualityOfService */

int asn1Init_TS24008IE_QualityOfService (TS24008IE_QualityOfService* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare1 = 0;
   pvalue->spare2 = 0;
   pvalue->spare3 = 0;
   pvalue->spare4 = 0;
   pvalue->extBitRate.n = 0;
   return 0;
}

/* TS24008IE_ReattemptInd */

/* TS24008IE_ExtQualityOfService */

/* TS24008IE_LinkedTI */

int asn1Init_TS24008IE_LinkedTI (TS24008IE_LinkedTI* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_LLCSAPIValue */

int asn1Init_TS24008IE_LLCSAPIValue (TS24008IE_LLCSAPIValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_TDIValue */

int asn1Init_TS24008IE_TDIValue (TS24008IE_TDIValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

/* TS24008IE_PacketFlowIdentValue */

int asn1Init_TS24008IE_PacketFlowIdentValue (
   TS24008IE_PacketFlowIdentValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_TFTOctet1 */

/* TS24008IE_IPv4Address */

/* TS24008IE_IPv6Address */

/* TS24008IE_IPv6AddressPrefix */

/* TS24008IE_PortRange */

/* TS24008IE_TFTPacketFilterComponent */

int asn1Init_TS24008IE_TFTPacketFilterComponent (
   TS24008IE_TFTPacketFilterComponent* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->value.u, 0, sizeof(pvalue->value.u));
   return 0;
}

/* TS24008IE_TFTPacketFilterContent */

int asn1Init_TS24008IE_TFTPacketFilterContent (
   TS24008IE_TFTPacketFilterContent* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->components.elem = 0;
   pvalue->components.n = 0;
   return 0;
}

/* TS24008IE_TFTPacketFilterItem */

int asn1Init_TS24008IE_TFTPacketFilterItem (
   TS24008IE_TFTPacketFilterItem* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24008IE_TFTPacketFilterContent (&pvalue->contents);
   return 0;
}

/* TS24008IE_TFTParam */

int asn1Init_TS24008IE_TFTParam (TS24008IE_TFTParam* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->contents.u, 0, sizeof(pvalue->contents.u));
   return 0;
}

/* TS24008IE_TFT */

int asn1Init_TS24008IE_TFT (TS24008IE_TFT* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->packetFilterList.u, 0, sizeof(pvalue->packetFilterList.u));
   pvalue->paramList.elem = 0;
   pvalue->paramList.n = 0;
   return 0;
}

/* TS24008IE_MBMSBearerCaps */

/* TS24008IE_RequestTypeValue */

int asn1Init_TS24008IE_RequestTypeValue (TS24008IE_RequestTypeValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = FALSE;
   return 0;
}

/* TS24008IE_WLANOffloadAccept */

/* TS24008IE_PDPContextStatus */

int asn1Init_TS24008IE_PDPContextStatus (TS24008IE_PDPContextStatus* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->length = 2;
   return 0;
}

/* TS24008IE_GPRSTimer */

/* TS24008IE_GPRSTimer2 */

/* TS24008IE_GPRSTimer3 */

/* TS24008IE_UplinkDataStatus */

int asn1Init_TS24008IE_UplinkDataStatus (TS24008IE_UplinkDataStatus* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->length = 2;
   return 0;
}

/* TS24008IE_DeviceProperties */

int asn1Init_TS24008IE_DeviceProperties (TS24008IE_DeviceProperties* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->spare = 0;
   return 0;
}

