/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.6.0, Date: 15-Feb-2022.
 */
#include "TS24011IES.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

/* TS24011IE_CPUserData */

int asn1Init_TS24011IE_CPUserData (TS24011IE_CPUserData* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* TS24011IE_RPAddress_octet3 */

/* TS24011IE_RPAddress */

int asn1Init_TS24011IE_RPAddress (TS24011IE_RPAddress* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->number = 0;
   return 0;
}

/* TS24011IE_RPOriginatorAddress */

int asn1Init_TS24011IE_RPOriginatorAddress (
   TS24011IE_RPOriginatorAddress* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24011IE_RPAddress (pvalue);
   return 0;
}

/* TS24011IE_RPDestinationAddress */

int asn1Init_TS24011IE_RPDestinationAddress (
   TS24011IE_RPDestinationAddress* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_TS24011IE_RPAddress (pvalue);
   return 0;
}

/* TS24011IE_RPUserData */

int asn1Init_TS24011IE_RPUserData (TS24011IE_RPUserData* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* TS24011IE_CPCauseValue */

int asn1Init_TS24011IE_CPCauseValue (TS24011IE_CPCauseValue* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->ext = FALSE;
   return 0;
}

/* TS24011IE_RPCauseElem */

int asn1Init_TS24011IE_RPCauseElem (TS24011IE_RPCauseElem* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->length = 1;
   pvalue->ext = FALSE;
   pvalue->diagField.n = 0;
   return 0;
}

