SeqOfTest$(OBJ): SeqOfTest.cpp SeqOfTest.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtpersrc/asn1PerCppTypes.h ../../../rtpersrc/asn1per.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxBitDecode.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxsrc/rtxPrintToStream.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h
reader$(OBJ): reader.cpp SeqOfTest.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtpersrc/asn1PerCppTypes.h \
 ../../../rtpersrc/asn1per.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxBitDecode.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtxsrc/rtxPrintToStream.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h
writer$(OBJ): writer.cpp SeqOfTest.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtpersrc/asn1PerCppTypes.h \
 ../../../rtpersrc/asn1per.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxBitDecode.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtxsrc/rtxPrintToStream.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxMemLeakCheck.h
