Canonical$(OBJ): Canonical.cpp Canonical.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CBitStr.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
CanonicalDec$(OBJ): CanonicalDec.cpp Canonical.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CBitStr.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxBitDecode.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
CanonicalEnc$(OBJ): CanonicalEnc.cpp Canonical.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CBitStr.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtxsrc/rtxStreamMemory.h ../../../rtxsrc/rtxStream.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
CanonicalPrint$(OBJ): CanonicalPrint.cpp Canonical.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtoersrc/asn1OerCppTypes.h ../../../rtoersrc/asn1oer.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/asn1CharSet.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtxsrc/rtxBitEncode.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CBitStr.h ../../../rtsrc/ASN1CSeqOfList.h \
 ../../../rtsrc/rtPrint.h ../../../rtxsrc/rtxPrint.h \
 ../../../rtsrc/rtBCD.h ../../../rtxsrc/rtxTBCD.h \
 ../../../rtxsrc/rtxDiagBitTrace.h ../../../rtxsrc/rtxPrintToStream.h
reader$(OBJ): reader.cpp Canonical.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/ASN1CSeqOfList.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h
writer$(OBJ): writer.cpp Canonical.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtoersrc/asn1OerCppTypes.h \
 ../../../rtoersrc/asn1oer.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/asn1CharSet.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtxsrc/rtxBitEncode.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CBitStr.h \
 ../../../rtsrc/ASN1CSeqOfList.h ../../../rtxsrc/rtxDiagBitTrace.h \
 ../../../rtxsrc/rtxPrintToStream.h ../../../rtxsrc/rtxPrint.h
