SNMPv2-PDU$(OBJ): SNMPv2-PDU.cpp SNMPv2-PDU.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtbersrc/asn1BerCppTypes.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtbersrc/asn1ber.h ../../../rtbersrc/berMacros.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CSeqOfList.h SNMPv2-SMI.h
SNMPv2-PDUPrint$(OBJ): SNMPv2-PDUPrint.cpp SNMPv2-PDU.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtbersrc/asn1BerCppTypes.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtbersrc/asn1ber.h ../../../rtbersrc/berMacros.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/ASN1CSeqOfList.h SNMPv2-SMI.h ../../../rtsrc/rtPrint.h \
 ../../../rtsrc/rtBCD.h ../../../rtxsrc/rtxTBCD.h
SNMPv2-SMI$(OBJ): SNMPv2-SMI.cpp SNMPv2-SMI.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtbersrc/asn1BerCppTypes.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtbersrc/asn1ber.h ../../../rtbersrc/berMacros.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtxsrc/rtxHexDump.h
SNMPv2-SMIPrint$(OBJ): SNMPv2-SMIPrint.cpp SNMPv2-SMI.h rtkey.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/osSysTypes.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxExternDefs.h \
 ../../../rtxsrc/rtxBigInt.h ../../../rtxsrc/rtxContext.h \
 ../../../rtxsrc/rtxDList.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/rtxStack.h ../../../rtxsrc/rtxBitString.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxCharStr.h ../../../rtxsrc/rtxDateTime.h \
 ../../../rtxsrc/rtxDiag.h ../../../rtxsrc/rtxEnum.h \
 ../../../rtxsrc/rtxError.h ../../../rtxsrc/rtxErrCodes.h \
 ../../../rtxsrc/rtxFile.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtxsrc/rtxUtil.h \
 ../../../rtbersrc/asn1BerCppTypes.h ../../../rtsrc/asn1CppTypes.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtsrc/asn1CppEvtHndlr64.h \
 ../../../rtsrc/asn1CppEvtHndlr.h ../../../rtsrc/asn1type.h \
 ../../../rtsrc/asn1tag.h ../../../rtsrc/asn1ErrCodes.h \
 ../../../rtsrc/rtExternDefs.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtsrc/ASN1Context.h \
 ../../../rtxsrc/OSRTContext.h ../../../rtxsrc/OSRTMsgBuf.h \
 ../../../rtxsrc/OSRTCtxtHolder.h ../../../rtxsrc/OSRTCtxtHolderIF.h \
 ../../../rtxsrc/OSRTMsgBufIF.h ../../../rtsrc/ASN1TOctStr.h \
 ../../../rtsrc/ASN1TOctStr64.h ../../../rtsrc/ASN1TObjId.h \
 ../../../rtbersrc/asn1ber.h ../../../rtbersrc/berMacros.h \
 ../../../rtxsrc/rtxPrint.h ../../../rtxsrc/rtxHexDump.h \
 ../../../rtsrc/rtPrint.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h
UDP-MIB$(OBJ): UDP-MIB.cpp UDP-MIB.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtbersrc/asn1BerCppTypes.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtbersrc/asn1ber.h \
 ../../../rtbersrc/berMacros.h ../../../rtxsrc/rtxPrint.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 SNMPv2-SMI.h
reader$(OBJ): reader.cpp SNMPv2-PDU.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtbersrc/asn1BerCppTypes.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtbersrc/asn1ber.h \
 ../../../rtbersrc/berMacros.h ../../../rtxsrc/rtxPrint.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 SNMPv2-SMI.h ../../../rtxsrc/rtxMemLeakCheck.h
writer$(OBJ): writer.cpp SNMPv2-PDU.h rtkey.h ../../../rtxsrc/rtxCommon.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/osMacros.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/rtxCommonDefs.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtxsrc/rtxBuffer.h \
 ../../../rtxsrc/rtxSList.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxMemory.h ../../../rtxsrc/rtxPattern.h \
 ../../../rtxsrc/rtxReal.h ../../../rtxsrc/rtxUTF8.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtbersrc/asn1BerCppTypes.h \
 ../../../rtsrc/asn1CppTypes.h ../../../rtxsrc/rtxMemBuf.h \
 ../../../rtsrc/asn1CppEvtHndlr64.h ../../../rtsrc/asn1CppEvtHndlr.h \
 ../../../rtsrc/asn1type.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtsrc/rtContext.h ../../../rtsrc/asn1CEvtHndlr.h \
 ../../../rtsrc/ASN1Context.h ../../../rtxsrc/OSRTContext.h \
 ../../../rtxsrc/OSRTMsgBuf.h ../../../rtxsrc/OSRTCtxtHolder.h \
 ../../../rtxsrc/OSRTCtxtHolderIF.h ../../../rtxsrc/OSRTMsgBufIF.h \
 ../../../rtsrc/ASN1TOctStr.h ../../../rtsrc/ASN1TOctStr64.h \
 ../../../rtsrc/ASN1TObjId.h ../../../rtbersrc/asn1ber.h \
 ../../../rtbersrc/berMacros.h ../../../rtxsrc/rtxPrint.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/ASN1CSeqOfList.h \
 SNMPv2-SMI.h UDP-MIB.h ../../../rtxsrc/rtxMemLeakCheck.h
