/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.A, Date: 20-Sep-2012.
 */
package sample_json.InfoObject;

import com.objsys.asn1j.runtime.*;
import java.util.*;

public class Writer {

   /* PDU: Test.OID */
   public static void main(String args[]) {

      String filename = new String ("message.json");
      boolean trace = true;
      
      if (args.length > 0) {
         for (int i = 0; i < args.length; i++) {
            if (args[i].equals ("-v"))
               Diag.instance().setEnabled (true);
            else if (args[i].equals ("-o"))
               filename = new String (args[++i]);
            else if (args[i].equals ("-notrace")) trace = false;
            else {
               System.out.println("usage: Writer [-v] [-o <filename>]");
               System.out.println("   -v  verbose mode: print trace info");
               System.out.println("   -o <filename>  " +
                                          "write encoded msg to <filename>");
               System.out.println("   -notrace  do not display trace info");
               System.exit(1);
            }
         }
      }
      
      // Encode a format type

      Asn1Boolean b = new Asn1Boolean (true);
      java.io.CharArrayWriter buffer = new java.io.CharArrayWriter();
      Asn1JsonOutputStream encodeBuffer = new Asn1JsonOutputStream (buffer);
      try {
         b.encode (encodeBuffer);

         if (trace) {
            System.out.println ("Encoding of FormatType was successful");
            System.out.println(buffer.toString());
            System.out.println ("");
         }
      }
      catch (Exception e) {
          System.out.println (e.getMessage());
          e.printStackTrace();           
          System.exit(-1);
      }

      // Create a data object and populate it with the data to be encoded

      BIOMETRIC_IDENTIFIER bioID = new BIOMETRIC_IDENTIFIER();
      bioID.set_id (new Asn1RelativeOID (_TestValues.id_ibia_SecuGen));

      Format format = new Format (bioID, new Asn1OpenType(buffer.toCharArray(), Asn1OpenType.JSON));


      // Create an encoding stream
      Asn1JsonOutputStream encodeStream = null;
      try {
         encodeStream = new Asn1JsonOutputStream (new java.io.OutputStreamWriter( new java.io.FileOutputStream(filename), "UTF-8") );
         format.encode(encodeStream);

         if (trace) {
            System.out.println("Encoding was successful");
         }
      }
      catch (Exception e) {
         System.out.println(e.getMessage());
         e.printStackTrace();
         System.exit(1);
      }
      finally {
         try {
            if (encodeStream != null) encodeStream.close ();
         }
         catch (Exception e) {
         }
      }
   }
}
