/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2.3, Date: 13-Jul-2020.
 */
#include "TS24301IES.h"
#include "TS24008IES.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

/*
 * Randomly generated test file: seed = 1594610319
 */
TS24301IE_AuthRespParam* asn1Test_TS24301IE_AuthRespParam (OSCTXT* pctxt)
{
   TS24301IE_AuthRespParam* pvalue = rtxMemAllocType (pctxt, TS24301IE_AuthRespParam);
   asn1Init_TS24301IE_AuthRespParam (pvalue);

   {
      static const OSOCTET testdata[] = { 
      0x95, 0xb9, 0x7a, 0x5d };
      pvalue->numocts = 4;
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 4, testdata, 4);
   }
   return (pvalue);
}

TS24301IE_EMMCause* asn1Test_TS24301IE_EMMCause (OSCTXT* pctxt)
{
   TS24301IE_EMMCause* pvalue = rtxMemAllocType (pctxt, TS24301IE_EMMCause);

   *pvalue = TS24301IE_EMMCause_imsiUnkInHSS;
   return (pvalue);
}

TS24301IE_ESMMessageContainer*
    asn1Test_TS24301IE_ESMMessageContainer (OSCTXT* pctxt)
{
   TS24301IE_ESMMessageContainer* pvalue = rtxMemAllocType (pctxt, TS24301IE_ESMMessageContainer);
   asn1Init_TS24301IE_ESMMessageContainer (pvalue);

   pvalue->numocts = 0;
   pvalue->data = (OSOCTET*) 0;
   return (pvalue);
}

TS24301IE_NASMessageContainer*
    asn1Test_TS24301IE_NASMessageContainer (OSCTXT* pctxt)
{
   TS24301IE_NASMessageContainer* pvalue = rtxMemAllocType (pctxt, TS24301IE_NASMessageContainer);
   asn1Init_TS24301IE_NASMessageContainer (pvalue);

   {
      static const OSOCTET testdata[] = { 
      0xeb, 0x21 };
      pvalue->numocts = 2;
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 2, testdata, 2);
   }
   return (pvalue);
}

TS24301IE_Nonce* asn1Test_TS24301IE_Nonce (OSCTXT* pctxt)
{
   TS24301IE_Nonce* pvalue = rtxMemAllocType (pctxt, TS24301IE_Nonce);

   {
      static const OSOCTET testdata[] = { 
      0xa9, 0x75, 0xb8, 0x94 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 4, testdata, 4);
   }
   return (pvalue);
}

TS24301IE_ServiceType* asn1Test_TS24301IE_ServiceType (OSCTXT* pctxt)
{
   TS24301IE_ServiceType* pvalue = rtxMemAllocType (pctxt, TS24301IE_ServiceType);

   *pvalue = 9;
   return (pvalue);
}

TS24301IE_ShortMAC* asn1Test_TS24301IE_ShortMAC (OSCTXT* pctxt)
{
   TS24301IE_ShortMAC* pvalue = rtxMemAllocType (pctxt, TS24301IE_ShortMAC);

   {
      static const OSOCTET testdata[] = { 
      0x97, 0x7 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 2, testdata, 2);
   }
   return (pvalue);
}

TS24301IE_TrackingAreaCode* asn1Test_TS24301IE_TrackingAreaCode (OSCTXT* pctxt)
{
   TS24301IE_TrackingAreaCode* pvalue = rtxMemAllocType (pctxt, TS24301IE_TrackingAreaCode);

   {
      static const OSOCTET testdata[] = { 
      0x33, 0x28 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 2, testdata, 2);
   }
   return (pvalue);
}

TS24301IE_SSCode* asn1Test_TS24301IE_SSCode (OSCTXT* pctxt)
{
   TS24301IE_SSCode* pvalue = rtxMemAllocType (pctxt, TS24301IE_SSCode);

   *pvalue = 129;
   return (pvalue);
}

TS24301IE_LCSIndicator* asn1Test_TS24301IE_LCSIndicator (OSCTXT* pctxt)
{
   TS24301IE_LCSIndicator* pvalue = rtxMemAllocType (pctxt, TS24301IE_LCSIndicator);

   *pvalue = 164;
   return (pvalue);
}

TS24301IE_LCSClientIdentity*
    asn1Test_TS24301IE_LCSClientIdentity (OSCTXT* pctxt)
{
   TS24301IE_LCSClientIdentity* pvalue = rtxMemAllocType (pctxt, TS24301IE_LCSClientIdentity);
   asn1Init_TS24301IE_LCSClientIdentity (pvalue);

   {
      static const OSOCTET testdata[] = { 
      0x0 };
      pvalue->numocts = 1;
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 1, testdata, 1);
   }
   return (pvalue);
}

TS24301IE_GenMsgContainerType*
    asn1Test_TS24301IE_GenMsgContainerType (OSCTXT* pctxt)
{
   TS24301IE_GenMsgContainerType* pvalue = rtxMemAllocType (pctxt, TS24301IE_GenMsgContainerType);

   *pvalue = TS24301IE_GenMsgContainerType_lppMsgCont;
   return (pvalue);
}

TS24301IE_GenMessageContainer*
    asn1Test_TS24301IE_GenMessageContainer (OSCTXT* pctxt)
{
   TS24301IE_GenMessageContainer* pvalue = rtxMemAllocType (pctxt, TS24301IE_GenMessageContainer);
   asn1Init_TS24301IE_GenMessageContainer (pvalue);

   pvalue->numocts = 0;
   pvalue->data = (OSOCTET*) 0;
   return (pvalue);
}

TS24301IE_InformationType* asn1Test_TS24301IE_InformationType (OSCTXT* pctxt)
{
   TS24301IE_InformationType* pvalue = rtxMemAllocType (pctxt, TS24301IE_InformationType);

   *pvalue = TS24301IE_InformationType_itUEPagingProbInfo;
   return (pvalue);
}

TS24301IE_ESMCause* asn1Test_TS24301IE_ESMCause (OSCTXT* pctxt)
{
   TS24301IE_ESMCause* pvalue = rtxMemAllocType (pctxt, TS24301IE_ESMCause);

   *pvalue = TS24301IE_ESMCause_operDeterBarring;
   return (pvalue);
}

TS24301IE_LinkedEPSBearerIdent*
    asn1Test_TS24301IE_LinkedEPSBearerIdent (OSCTXT* pctxt)
{
   TS24301IE_LinkedEPSBearerIdent* pvalue = rtxMemAllocType (pctxt, TS24301IE_LinkedEPSBearerIdent);

   *pvalue = 14;
   return (pvalue);
}

TS24301IE_PDNTypeValue* asn1Test_TS24301IE_PDNTypeValue (OSCTXT* pctxt)
{
   TS24301IE_PDNTypeValue* pvalue = rtxMemAllocType (pctxt, TS24301IE_PDNTypeValue);

   *pvalue = TS24301IE_PDNTypeValue_ipv4;
   return (pvalue);
}

TS24301IE_RemoteUEAddrType* asn1Test_TS24301IE_RemoteUEAddrType (OSCTXT* pctxt)
{
   TS24301IE_RemoteUEAddrType* pvalue = rtxMemAllocType (pctxt, TS24301IE_RemoteUEAddrType);

   *pvalue = TS24301IE_RemoteUEAddrType_remUENoIp;
   return (pvalue);
}

TS24301IE_ServPLMNRateCtrl* asn1Test_TS24301IE_ServPLMNRateCtrl (OSCTXT* pctxt)
{
   TS24301IE_ServPLMNRateCtrl* pvalue = rtxMemAllocType (pctxt, TS24301IE_ServPLMNRateCtrl);

   {
      static const OSOCTET testdata[] = { 
      0x09, 0x2a };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 2, testdata, 2);
   }
   return (pvalue);
}

TS24301IE_EPSBearerContextStatus*
    asn1Test_TS24301IE_EPSBearerContextStatus (OSCTXT* pctxt)
{
   TS24301IE_EPSBearerContextStatus* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSBearerContextStatus);
   asn1Init_TS24301IE_EPSBearerContextStatus (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->ebi7 = 1;

   pvalue->ebi6 = 0;

   pvalue->ebi5 = 0;

   pvalue->ebi4 = 0;

   pvalue->ebi3 = 1;

   pvalue->ebi2 = 1;

   pvalue->ebi1 = 1;

   pvalue->ebi0 = 1;

   pvalue->ebi15 = 1;

   pvalue->ebi14 = 0;

   pvalue->ebi13 = 0;

   pvalue->ebi12 = 0;

   pvalue->ebi11 = 0;

   pvalue->ebi10 = 1;

   pvalue->ebi9 = 0;

   pvalue->ebi8 = 1;
   return (pvalue);
}

TS24301IE_NASSecParamsFromEUTRA*
    asn1Test_TS24301IE_NASSecParamsFromEUTRA (OSCTXT* pctxt)
{
   TS24301IE_NASSecParamsFromEUTRA* pvalue = rtxMemAllocType (pctxt, TS24301IE_NASSecParamsFromEUTRA);
   asn1Init_TS24301IE_NASSecParamsFromEUTRA (pvalue);

   pvalue->spare = 13;

   pvalue->dlNASCount = 0;
   return (pvalue);
}

TS24301IE_NASSecParamsToEUTRA*
    asn1Test_TS24301IE_NASSecParamsToEUTRA (OSCTXT* pctxt)
{
   TS24301IE_NASSecParamsToEUTRA* pvalue = rtxMemAllocType (pctxt, TS24301IE_NASSecParamsToEUTRA);
   asn1Init_TS24301IE_NASSecParamsToEUTRA (pvalue);

   {
      static const OSOCTET testdata[] = { 
      0x9c, 0xc6, 0x55, 0x34 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->nonceMMEValue, 4, testdata, 4);
   }

   pvalue->spare1 = 0;

   pvalue->typeOfCiphAlg = 6;

   pvalue->spare2 = 0;

   pvalue->typeOfProtAlg = 1;

   pvalue->spare3 = 8;

   pvalue->tsc = 1;

   pvalue->nasKeySetIdent = 4;
   return (pvalue);
}

TS24301IE_AddnUpdateResult* asn1Test_TS24301IE_AddnUpdateResult (OSCTXT* pctxt)
{
   TS24301IE_AddnUpdateResult* pvalue = rtxMemAllocType (pctxt, TS24301IE_AddnUpdateResult);
   asn1Init_TS24301IE_AddnUpdateResult (pvalue);

   pvalue->spare = 0;

   pvalue->value = TS24301IE_AddnUpdateResult_value_noInfo;
   return (pvalue);
}

TS24301IE_AddnUpdateType* asn1Test_TS24301IE_AddnUpdateType (OSCTXT* pctxt)
{
   TS24301IE_AddnUpdateType* pvalue = rtxMemAllocType (pctxt, TS24301IE_AddnUpdateType);

   pvalue->pnb_CIoT = TS24301IE_AddnUpdateType_pnb_CIoT_noAddInfo;

   pvalue->saf = 0;

   pvalue->autv = 1;
   return (pvalue);
}

TS24301IE_SMSServicesStatus*
    asn1Test_TS24301IE_SMSServicesStatus (OSCTXT* pctxt)
{
   TS24301IE_SMSServicesStatus* pvalue = rtxMemAllocType (pctxt, TS24301IE_SMSServicesStatus);
   asn1Init_TS24301IE_SMSServicesStatus (pvalue);

   pvalue->spare = 0;

   pvalue->value = 2;
   return (pvalue);
}

TS24301IE_CSFBResponse* asn1Test_TS24301IE_CSFBResponse (OSCTXT* pctxt)
{
   TS24301IE_CSFBResponse* pvalue = rtxMemAllocType (pctxt, TS24301IE_CSFBResponse);
   asn1Init_TS24301IE_CSFBResponse (pvalue);

   pvalue->spare = 0;

   pvalue->value = 2;
   return (pvalue);
}

TS24301IE_DetachType* asn1Test_TS24301IE_DetachType (OSCTXT* pctxt)
{
   TS24301IE_DetachType* pvalue = rtxMemAllocType (pctxt, TS24301IE_DetachType);

   pvalue->switchOff = 1;

   pvalue->typeOfDetach = 1;
   return (pvalue);
}

TS24301IE_EPSAttachResult* asn1Test_TS24301IE_EPSAttachResult (OSCTXT* pctxt)
{
   TS24301IE_EPSAttachResult* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSAttachResult);
   asn1Init_TS24301IE_EPSAttachResult (pvalue);

   pvalue->spare = 0;

   pvalue->result = 5;
   return (pvalue);
}

TS24301IE_EPSAttachType* asn1Test_TS24301IE_EPSAttachType (OSCTXT* pctxt)
{
   TS24301IE_EPSAttachType* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSAttachType);
   asn1Init_TS24301IE_EPSAttachType (pvalue);

   pvalue->spare = 0;

   pvalue->value = 5;
   return (pvalue);
}

TS24301IE_EPSMobileIdentity_GUTI*
    asn1Test_TS24301IE_EPSMobileIdentity_GUTI (OSCTXT* pctxt)
{
   TS24301IE_EPSMobileIdentity_GUTI* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSMobileIdentity_GUTI);
   asn1Init_TS24301IE_EPSMobileIdentity_GUTI (pvalue);

   rtxStrncpy (pvalue->mcc_mnc.mcc, 4, "240", 3);
   rtxStrncpy (pvalue->mcc_mnc.mnc, 4, "02", 3);

   {
      static const OSOCTET testdata[] = { 
      0xcc, 0x3b };
      OSCRTLSAFEMEMCPY ((void*)pvalue->mmeGroupID, 2, testdata, 2);
   }

   pvalue->mmeCode = 35;

   {
      static const OSOCTET testdata[] = { 
      0x91, 0x7e, 0xab, 0x42 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->tmsi, 4, testdata, 4);
   }
   return (pvalue);
}

TS24301IE_EPSMobileIdentity*
    asn1Test_TS24301IE_EPSMobileIdentity (OSCTXT* pctxt)
{
   TS24301IE_EPSMobileIdentity* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSMobileIdentity);
   asn1Init_TS24301IE_EPSMobileIdentity (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->filler = 7;

   pvalue->oddEvenInd = 1;

   pvalue->typeOfIdent = TS24301IE_EPSMobileIdentity_typeOfIdent_imsi;

   switch (pvalue->typeOfIdent) {
      /* guti */
      case 6:

         rtxStrncpy (pvalue->content.u.guti.mcc_mnc.mcc, 4, "250", 3);
         rtxStrncpy (pvalue->content.u.guti.mcc_mnc.mnc, 4, "04", 3);

         {
            static const OSOCTET testdata[] = { 
            0xfd, 0x25 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->content.u.guti.mmeGroupID, 2, testdata, 2);
         }

         pvalue->content.u.guti.mmeCode = 188;

         {
            static const OSOCTET testdata[] = { 
            0xb1, 0x72, 0xc5, 0x8d };
            OSCRTLSAFEMEMCPY ((void*)pvalue->content.u.guti.tmsi, 4, testdata, 4);
         }
         break;

      /* imsi */
      case 1:
         rtxStrncpy (pvalue->content.u.imsi, sizeof(pvalue->content.u.imsi), "43407123456789", 15);
         break;

      /* imei */
      case 3:
         OSCRTLSTRNCPY_S (pvalue->content.u.imei, 16, "513694101353768", 16);
         break;

      default: break;
   }
   return (pvalue);
}

TS24301IE_EPSNetworkFeatureSupport*
    asn1Test_TS24301IE_EPSNetworkFeatureSupport (OSCTXT* pctxt)
{
   TS24301IE_EPSNetworkFeatureSupport* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSNetworkFeatureSupport);
   asn1Init_TS24301IE_EPSNetworkFeatureSupport (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->cpCIoT = 0;

   pvalue->erNoPDN = 0;

   pvalue->esr = 1;

   pvalue->csLCS = 2;

   pvalue->epcLCS = 0;

   pvalue->emcBS = 1;

   pvalue->imsVoPS = 1;

   pvalue->m.octet4Present = 1;

   pvalue->octet4.sigEPSBC = 1;

   pvalue->octet4.iwkN26 = 1;

   pvalue->octet4.rDCNR = 1;

   pvalue->octet4.rEC = 0;

   pvalue->octet4.ePCO = 0;

   pvalue->octet4.hcCpCIoT = 1;

   pvalue->octet4.s1DT = 0;

   pvalue->octet4.upCIot = 0;
   return (pvalue);
}

TS24301IE_EPSUpdateResult* asn1Test_TS24301IE_EPSUpdateResult (OSCTXT* pctxt)
{
   TS24301IE_EPSUpdateResult* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSUpdateResult);
   asn1Init_TS24301IE_EPSUpdateResult (pvalue);

   pvalue->spare = 0;

   pvalue->result = 5;
   return (pvalue);
}

TS24301IE_EPSUpdateType* asn1Test_TS24301IE_EPSUpdateType (OSCTXT* pctxt)
{
   TS24301IE_EPSUpdateType* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSUpdateType);

   pvalue->active = 1;

   pvalue->value = 5;
   return (pvalue);
}

TS24301IE_KSIAndSequenceNumber*
    asn1Test_TS24301IE_KSIAndSequenceNumber (OSCTXT* pctxt)
{
   TS24301IE_KSIAndSequenceNumber* pvalue = rtxMemAllocType (pctxt, TS24301IE_KSIAndSequenceNumber);

   pvalue->ksi = 6;

   pvalue->seqNo = 6;
   return (pvalue);
}

TS24301IE_NASKeySetIdentifier*
    asn1Test_TS24301IE_NASKeySetIdentifier (OSCTXT* pctxt)
{
   TS24301IE_NASKeySetIdentifier* pvalue = rtxMemAllocType (pctxt, TS24301IE_NASKeySetIdentifier);

   pvalue->tsc = 0;

   pvalue->ident = 4;
   return (pvalue);
}

TS24301IE_NASSecurityAlgorithms*
    asn1Test_TS24301IE_NASSecurityAlgorithms (OSCTXT* pctxt)
{
   TS24301IE_NASSecurityAlgorithms* pvalue = rtxMemAllocType (pctxt, TS24301IE_NASSecurityAlgorithms);
   asn1Init_TS24301IE_NASSecurityAlgorithms (pvalue);

   pvalue->spare1 = 0;

   pvalue->typeOfCiph = TS24301IE_NASSecurityAlgorithms_typeOfCiph_eea0;

   pvalue->spare2 = 1;

   pvalue->typeOfProt = TS24301IE_NASSecurityAlgorithms_typeOfProt_eia0;
   return (pvalue);
}

TS24301IE_PagingIdentity* asn1Test_TS24301IE_PagingIdentity (OSCTXT* pctxt)
{
   TS24301IE_PagingIdentity* pvalue = rtxMemAllocType (pctxt, TS24301IE_PagingIdentity);
   asn1Init_TS24301IE_PagingIdentity (pvalue);

   pvalue->spare = 112;

   pvalue->ident = TS24301IE_PagingIdentity_ident_imsi;
   return (pvalue);
}

TS24301IE_ExtEMMCause* asn1Test_TS24301IE_ExtEMMCause (OSCTXT* pctxt)
{
   TS24301IE_ExtEMMCause* pvalue = rtxMemAllocType (pctxt, TS24301IE_ExtEMMCause);
   asn1Init_TS24301IE_ExtEMMCause (pvalue);

   pvalue->spare = 0;

   pvalue->nbiotAllowed = 0;

   pvalue->epsOptInfo = 0;

   pvalue->e_UTRAN_NotAllowed = 0;
   return (pvalue);
}

TS24301IE_TrackingAreaIdent*
    asn1Test_TS24301IE_TrackingAreaIdent (OSCTXT* pctxt)
{
   TS24301IE_TrackingAreaIdent* pvalue = rtxMemAllocType (pctxt, TS24301IE_TrackingAreaIdent);
   asn1Init_TS24301IE_TrackingAreaIdent (pvalue);

   rtxStrncpy (pvalue->mcc_mnc.mcc, 4, "452", 3);
   rtxStrncpy (pvalue->mcc_mnc.mnc, 4, "01", 3);

   {
      static const OSOCTET testdata[] = { 
      0x1d, 0xfa };
      OSCRTLSAFEMEMCPY ((void*)pvalue->tac.data, 2, testdata, 2);
   }
   return (pvalue);
}

TS24301IE_TrackingAreaIdentListItem*
    asn1Test_TS24301IE_TrackingAreaIdentListItem (OSCTXT* pctxt)
{
   TS24301IE_TrackingAreaIdentListItem* pvalue = rtxMemAllocType (pctxt, TS24301IE_TrackingAreaIdentListItem);
   asn1Init_TS24301IE_TrackingAreaIdentListItem (pvalue);

   pvalue->spare = 0;

   pvalue->typeOfList = 1;

   pvalue->numElements = 6;

   switch (pvalue->typeOfList) {
      /* partTrkIdentList0 */
      case 0:

         rtxStrncpy (pvalue->elements.u.partTrkIdentList0.mcc_mnc.mcc, 4, "651", 3);
         rtxStrncpy (pvalue->elements.u.partTrkIdentList0.mcc_mnc.mnc, 4, "02", 3);

         pvalue->elements.u.partTrkIdentList0.tacs.n = 6;
         {
            static const OSOCTET testdata[] = { 
            0xde, 0x46 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->elements.u.partTrkIdentList0.tacs.elem[0].data, 2, testdata, 2);
         }

         {
            static const OSOCTET testdata[] = { 
            0x3e, 0x48 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->elements.u.partTrkIdentList0.tacs.elem[1].data, 2, testdata, 2);
         }

         {
            static const OSOCTET testdata[] = { 
            0x9a, 0xcb };
            OSCRTLSAFEMEMCPY ((void*)pvalue->elements.u.partTrkIdentList0.tacs.elem[2].data, 2, testdata, 2);
         }

         {
            static const OSOCTET testdata[] = { 
            0x6f, 0x20 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->elements.u.partTrkIdentList0.tacs.elem[3].data, 2, testdata, 2);
         }

         {
            static const OSOCTET testdata[] = { 
            0xcc, 0x5b };
            OSCRTLSAFEMEMCPY ((void*)pvalue->elements.u.partTrkIdentList0.tacs.elem[4].data, 2, testdata, 2);
         }

         {
            static const OSOCTET testdata[] = { 
            0x34, 0x10 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->elements.u.partTrkIdentList0.tacs.elem[5].data, 2, testdata, 2);
         }

         break;

      /* partTrkIdentList1 */
      case 1:

         rtxStrncpy (pvalue->elements.u.partTrkIdentList1.mcc_mnc.mcc, 4, "612", 3);
         rtxStrncpy (pvalue->elements.u.partTrkIdentList1.mcc_mnc.mnc, 4, "05", 3);

         {
            static const OSOCTET testdata[] = { 
            0xb2, 0x47 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->elements.u.partTrkIdentList1.tac.data, 2, testdata, 2);
         }
         break;

      /* partTrkIdentList2 */
      case 2:
         pvalue->elements.u.partTrkIdentList2.n = 1;

         rtxStrncpy (pvalue->elements.u.partTrkIdentList2.elem[0].mcc_mnc.mcc, 4, "268", 3);
         rtxStrncpy (pvalue->elements.u.partTrkIdentList2.elem[0].mcc_mnc.mnc, 4, "01", 3);

         {
            static const OSOCTET testdata[] = { 
            0x22, 0xca };
            OSCRTLSAFEMEMCPY ((void*)pvalue->elements.u.partTrkIdentList2.elem[0].tac.data, 2, testdata, 2);
         }

         break;

      default: break;
   }
   return (pvalue);
}

TS24301IE_TrackingAreaIdentList*
    asn1Test_TS24301IE_TrackingAreaIdentList (OSCTXT* pctxt)
{
   TS24301IE_TrackingAreaIdentList* pvalue = rtxMemAllocType (pctxt, TS24301IE_TrackingAreaIdentList);
   asn1Init_TS24301IE_TrackingAreaIdentList (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->idents.n = 1;

   pvalue->idents.elem[0].spare = 0;

   pvalue->idents.elem[0].typeOfList = 1;

   pvalue->idents.elem[0].numElements = 12;

   switch (pvalue->idents.elem[0].typeOfList) {
      /* partTrkIdentList0 */
      case 0:

         rtxStrncpy (pvalue->idents.elem[0].elements.u.partTrkIdentList0.mcc_mnc.mcc, 4, "310", 3);
         rtxStrncpy (pvalue->idents.elem[0].elements.u.partTrkIdentList0.mcc_mnc.mnc, 4, "94", 3);

         pvalue->idents.elem[0].elements.u.partTrkIdentList0.tacs.n = 2;
         {
            static const OSOCTET testdata[] = { 
            0x1e, 0x99 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->idents.elem[0].elements.u.partTrkIdentList0.tacs.elem[0].data, 2, testdata, 2);
         }

         {
            static const OSOCTET testdata[] = { 
            0xc8, 0xba };
            OSCRTLSAFEMEMCPY ((void*)pvalue->idents.elem[0].elements.u.partTrkIdentList0.tacs.elem[1].data, 2, testdata, 2);
         }

         break;

      /* partTrkIdentList1 */
      case 1:

         rtxStrncpy (pvalue->idents.elem[0].elements.u.partTrkIdentList1.mcc_mnc.mcc, 4, "206", 3);
         rtxStrncpy (pvalue->idents.elem[0].elements.u.partTrkIdentList1.mcc_mnc.mnc, 4, "10", 3);

         {
            static const OSOCTET testdata[] = { 
            0x14, 0x97 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->idents.elem[0].elements.u.partTrkIdentList1.tac.data, 2, testdata, 2);
         }
         break;

      /* partTrkIdentList2 */
      case 2:
         pvalue->idents.elem[0].elements.u.partTrkIdentList2.n = 1;

         rtxStrncpy (pvalue->idents.elem[0].elements.u.partTrkIdentList2.elem[0].mcc_mnc.mcc, 4, "706", 3);
         rtxStrncpy (pvalue->idents.elem[0].elements.u.partTrkIdentList2.elem[0].mcc_mnc.mnc, 4, "01", 3);

         {
            static const OSOCTET testdata[] = { 
            0x69, 0xf6 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->idents.elem[0].elements.u.partTrkIdentList2.elem[0].tac.data, 2, testdata, 2);
         }

         break;

      default: break;
   }

   return (pvalue);
}

TS24301IE_EPSEncryptAlgsSupported*
    asn1Test_TS24301IE_EPSEncryptAlgsSupported (OSCTXT* pctxt)
{
   TS24301IE_EPSEncryptAlgsSupported* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSEncryptAlgsSupported);

   pvalue->eea0 = 0;

   pvalue->x128_eea1 = 0;

   pvalue->x128_eea2 = 0;

   pvalue->eea3 = 0;

   pvalue->eea4 = 1;

   pvalue->eea5 = 1;

   pvalue->eea6 = 1;

   pvalue->eea7 = 0;
   return (pvalue);
}

TS24301IE_EPSIntegAlgsSupported*
    asn1Test_TS24301IE_EPSIntegAlgsSupported (OSCTXT* pctxt)
{
   TS24301IE_EPSIntegAlgsSupported* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSIntegAlgsSupported);

   pvalue->eia0 = 1;

   pvalue->eia1 = 1;

   pvalue->eia2 = 0;

   pvalue->eia3 = 0;

   pvalue->eia4 = 1;

   pvalue->eia5 = 0;

   pvalue->eia6 = 0;

   pvalue->eia7 = 1;
   return (pvalue);
}

TS24301IE_UMTSEncryptAlgsSupported*
    asn1Test_TS24301IE_UMTSEncryptAlgsSupported (OSCTXT* pctxt)
{
   TS24301IE_UMTSEncryptAlgsSupported* pvalue = rtxMemAllocType (pctxt, TS24301IE_UMTSEncryptAlgsSupported);

   pvalue->uea0 = 0;

   pvalue->uea1 = 1;

   pvalue->uea2 = 0;

   pvalue->uea3 = 1;

   pvalue->uea4 = 0;

   pvalue->uea5 = 1;

   pvalue->uea6 = 1;

   pvalue->uea7 = 1;
   return (pvalue);
}

TS24301IE_UMTSIntegAlgsSupported*
    asn1Test_TS24301IE_UMTSIntegAlgsSupported (OSCTXT* pctxt)
{
   TS24301IE_UMTSIntegAlgsSupported* pvalue = rtxMemAllocType (pctxt, TS24301IE_UMTSIntegAlgsSupported);

   pvalue->uia1 = 0;

   pvalue->uia2 = 1;

   pvalue->uia3 = 1;

   pvalue->uia4 = 1;

   pvalue->uia5 = 0;

   pvalue->uia6 = 0;

   pvalue->uia7 = 1;
   return (pvalue);
}

TS24301IE_UENetworkCapability*
    asn1Test_TS24301IE_UENetworkCapability (OSCTXT* pctxt)
{
   TS24301IE_UENetworkCapability* pvalue = rtxMemAllocType (pctxt, TS24301IE_UENetworkCapability);
   asn1Init_TS24301IE_UENetworkCapability (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->epsEncryptAlgs.eea0 = 1;

   pvalue->epsEncryptAlgs.x128_eea1 = 0;

   pvalue->epsEncryptAlgs.x128_eea2 = 1;

   pvalue->epsEncryptAlgs.eea3 = 1;

   pvalue->epsEncryptAlgs.eea4 = 0;

   pvalue->epsEncryptAlgs.eea5 = 1;

   pvalue->epsEncryptAlgs.eea6 = 0;

   pvalue->epsEncryptAlgs.eea7 = 0;

   pvalue->epsIntegAlgs.eia0 = 0;

   pvalue->epsIntegAlgs.eia1 = 0;

   pvalue->epsIntegAlgs.eia2 = 1;

   pvalue->epsIntegAlgs.eia3 = 0;

   pvalue->epsIntegAlgs.eia4 = 1;

   pvalue->epsIntegAlgs.eia5 = 1;

   pvalue->epsIntegAlgs.eia6 = 0;

   pvalue->epsIntegAlgs.eia7 = 0;

   pvalue->m.umtsEncryptAlgsPresent = 1;

   pvalue->umtsEncryptAlgs.uea0 = 0;

   pvalue->umtsEncryptAlgs.uea1 = 0;

   pvalue->umtsEncryptAlgs.uea2 = 0;

   pvalue->umtsEncryptAlgs.uea3 = 1;

   pvalue->umtsEncryptAlgs.uea4 = 0;

   pvalue->umtsEncryptAlgs.uea5 = 1;

   pvalue->umtsEncryptAlgs.uea6 = 0;

   pvalue->umtsEncryptAlgs.uea7 = 1;

   pvalue->m.octet6Present = 1;

   pvalue->octet6.ucs2 = 1;

   pvalue->octet6.umtsIntegAlgs.uia1 = 1;

   pvalue->octet6.umtsIntegAlgs.uia2 = 0;

   pvalue->octet6.umtsIntegAlgs.uia3 = 0;

   pvalue->octet6.umtsIntegAlgs.uia4 = 0;

   pvalue->octet6.umtsIntegAlgs.uia5 = 1;

   pvalue->octet6.umtsIntegAlgs.uia6 = 1;

   pvalue->octet6.umtsIntegAlgs.uia7 = 1;

   pvalue->m.octet7Present = 1;

   pvalue->octet7.proSedd = 1;

   pvalue->octet7.proSe = 1;

   pvalue->octet7.h245_ash = 0;

   pvalue->octet7.acc_csfb = 1;

   pvalue->octet7.lpp = 0;

   pvalue->octet7.lcs = 1;

   pvalue->octet7.x1xSR_VCC = 0;

   pvalue->octet7.nf = 0;

   pvalue->m.octet8Present = 1;

   pvalue->octet8.ePCO = 1;

   pvalue->octet8.hc_CP_CIoT = 1;

   pvalue->octet8.erwoPDN = 0;

   pvalue->octet8.s1_Udata = 0;

   pvalue->octet8.upCIoT = 0;

   pvalue->octet8.cpCIoT = 0;

   pvalue->octet8.prose_relay = 0;

   pvalue->octet8.proSedc = 0;

   pvalue->m.octet9Present = 1;

   pvalue->octet9.bearers = 0;

   pvalue->octet9.sgc = 0;

   pvalue->octet9.n1Mode = 0;

   pvalue->octet9.dcnr = 1;

   pvalue->octet9.cpBackoff = 1;

   pvalue->octet9.restrictEC = 0;

   pvalue->octet9.v2xPC5 = 0;

   pvalue->octet9.multDRB = 0;

   pvalue->m.octet10Present = 1;

   pvalue->octet10.spare = 49;

   pvalue->octet10.wusa = 1;

   pvalue->octet10.racs = 1;

   pvalue->m.spare4Present = 1;
   pvalue->spare4.numocts = 5;
   pvalue->spare4.data = (OSOCTET*) rtxMemAlloc (pctxt, 5);
   {
      static const OSOCTET testdata[] = {
      0x5e, 0x8e, 0x05, 0x45, 0xd };
      OSCRTLSAFEMEMCPY ((void*)pvalue->spare4.data, 5, testdata, 5);
   }
   return (pvalue);
}

TS24301IE_GPRSIntegAlgsSupported*
    asn1Test_TS24301IE_GPRSIntegAlgsSupported (OSCTXT* pctxt)
{
   TS24301IE_GPRSIntegAlgsSupported* pvalue = rtxMemAllocType (pctxt, TS24301IE_GPRSIntegAlgsSupported);

   pvalue->gea1 = 1;

   pvalue->gea2 = 1;

   pvalue->gea3 = 1;

   pvalue->gea4 = 0;

   pvalue->gea5 = 1;

   pvalue->gea6 = 1;

   pvalue->gea7 = 1;
   return (pvalue);
}

TS24301IE_UERadioCapInfoUpdateNeeded*
    asn1Test_TS24301IE_UERadioCapInfoUpdateNeeded (OSCTXT* pctxt)
{
   TS24301IE_UERadioCapInfoUpdateNeeded* pvalue = rtxMemAllocType (pctxt, TS24301IE_UERadioCapInfoUpdateNeeded);

   pvalue->spare = 3;

   pvalue->value = 1;
   return (pvalue);
}

TS24301IE_UESecurityCapability*
    asn1Test_TS24301IE_UESecurityCapability (OSCTXT* pctxt)
{
   TS24301IE_UESecurityCapability* pvalue = rtxMemAllocType (pctxt, TS24301IE_UESecurityCapability);
   asn1Init_TS24301IE_UESecurityCapability (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->epsEncryptAlgs.eea0 = 1;

   pvalue->epsEncryptAlgs.x128_eea1 = 0;

   pvalue->epsEncryptAlgs.x128_eea2 = 0;

   pvalue->epsEncryptAlgs.eea3 = 1;

   pvalue->epsEncryptAlgs.eea4 = 1;

   pvalue->epsEncryptAlgs.eea5 = 0;

   pvalue->epsEncryptAlgs.eea6 = 1;

   pvalue->epsEncryptAlgs.eea7 = 1;

   pvalue->epsIntegAlgs.eia0 = 1;

   pvalue->epsIntegAlgs.eia1 = 0;

   pvalue->epsIntegAlgs.eia2 = 1;

   pvalue->epsIntegAlgs.eia3 = 0;

   pvalue->epsIntegAlgs.eia4 = 1;

   pvalue->epsIntegAlgs.eia5 = 1;

   pvalue->epsIntegAlgs.eia6 = 1;

   pvalue->epsIntegAlgs.eia7 = 0;

   pvalue->m.umtsEncryptAlgsPresent = 1;

   pvalue->umtsEncryptAlgs.uea0 = 1;

   pvalue->umtsEncryptAlgs.uea1 = 1;

   pvalue->umtsEncryptAlgs.uea2 = 0;

   pvalue->umtsEncryptAlgs.uea3 = 0;

   pvalue->umtsEncryptAlgs.uea4 = 0;

   pvalue->umtsEncryptAlgs.uea5 = 0;

   pvalue->umtsEncryptAlgs.uea6 = 0;

   pvalue->umtsEncryptAlgs.uea7 = 1;

   pvalue->m.octet6Present = 1;

   pvalue->octet6.spare = 0;

   pvalue->octet6.umtsIntegAlgs.uia1 = 1;

   pvalue->octet6.umtsIntegAlgs.uia2 = 0;

   pvalue->octet6.umtsIntegAlgs.uia3 = 0;

   pvalue->octet6.umtsIntegAlgs.uia4 = 1;

   pvalue->octet6.umtsIntegAlgs.uia5 = 0;

   pvalue->octet6.umtsIntegAlgs.uia6 = 0;

   pvalue->octet6.umtsIntegAlgs.uia7 = 0;

   pvalue->m.octet7Present = 1;

   pvalue->octet7.spare = 0;

   pvalue->octet7.gprsIntegAlgs.gea1 = 1;

   pvalue->octet7.gprsIntegAlgs.gea2 = 1;

   pvalue->octet7.gprsIntegAlgs.gea3 = 0;

   pvalue->octet7.gprsIntegAlgs.gea4 = 1;

   pvalue->octet7.gprsIntegAlgs.gea5 = 0;

   pvalue->octet7.gprsIntegAlgs.gea6 = 1;

   pvalue->octet7.gprsIntegAlgs.gea7 = 0;
   return (pvalue);
}

TS24301IE_ExtEmergencyNumberInfo*
    asn1Test_TS24301IE_ExtEmergencyNumberInfo (OSCTXT* pctxt)
{
   TS24301IE_ExtEmergencyNumberInfo* pvalue = rtxMemAllocType (pctxt, TS24301IE_ExtEmergencyNumberInfo);
   asn1Init_TS24301IE_ExtEmergencyNumberInfo (pvalue);

   pvalue->number.length = 0; /* length will be calculated */

   pvalue->number.digits = "1a637771#0";

   pvalue->subservices.subservicesLen = 0; /* length will be calculated */

   pvalue->subservices.subservices.numocts = 15;
   pvalue->subservices.subservices.data = (OSOCTET*) rtxMemAlloc (pctxt, 15);
   {
      static const OSOCTET testdata[] = {
      0x48, 0x66, 0xf4, 0x57, 0xfc, 0x14, 0x91, 0x4f, 
      0x03, 0x15, 0x79, 0x55, 0x84, 0x3a, 0x8c };
      OSCRTLSAFEMEMCPY ((void*)pvalue->subservices.subservices.data, 15, testdata, 15);
   }
   return (pvalue);
}

TS24301IE_ExtEmergencyNumberList*
    asn1Test_TS24301IE_ExtEmergencyNumberList (OSCTXT* pctxt)
{
   TS24301IE_ExtEmergencyNumberList* pvalue = rtxMemAllocType (pctxt, TS24301IE_ExtEmergencyNumberList);
   asn1Init_TS24301IE_ExtEmergencyNumberList (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->spare = 21;

   pvalue->catValue = 0;

   /* zero elements */
   return (pvalue);
}

TS24301IE_CLI* asn1Test_TS24301IE_CLI (OSCTXT* pctxt)
{
   TS24301IE_CLI* pvalue = rtxMemAllocType (pctxt, TS24301IE_CLI);
   asn1Init_TS24301IE_CLI (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->value = "0504*6#0";
   return (pvalue);
}

TS24301IE_GUTIType* asn1Test_TS24301IE_GUTIType (OSCTXT* pctxt)
{
   TS24301IE_GUTIType* pvalue = rtxMemAllocType (pctxt, TS24301IE_GUTIType);
   asn1Init_TS24301IE_GUTIType (pvalue);

   pvalue->spare = 5;

   pvalue->mapped = 0;
   return (pvalue);
}

TS24301IE_CtrlPlaneSvcType* asn1Test_TS24301IE_CtrlPlaneSvcType (OSCTXT* pctxt)
{
   TS24301IE_CtrlPlaneSvcType* pvalue = rtxMemAllocType (pctxt, TS24301IE_CtrlPlaneSvcType);

   pvalue->activeFlag = 1;

   pvalue->svcTypeValue = 3;
   return (pvalue);
}

TS24301IE_HashMME* asn1Test_TS24301IE_HashMME (OSCTXT* pctxt)
{
   TS24301IE_HashMME* pvalue = rtxMemAllocType (pctxt, TS24301IE_HashMME);

   pvalue->length = 38;

   {
      static const OSOCTET testdata[] = { 
      0xef, 0x01, 0x9a, 0xc6, 0x7d, 0x2e, 0x59, 0xcc };
      OSCRTLSAFEMEMCPY ((void*)pvalue->hashValue, 8, testdata, 8);
   }
   return (pvalue);
}

TS24301IE_ReplayedNASMsgContainer*
    asn1Test_TS24301IE_ReplayedNASMsgContainer (OSCTXT* pctxt)
{
   TS24301IE_ReplayedNASMsgContainer* pvalue = rtxMemAllocType (pctxt, TS24301IE_ReplayedNASMsgContainer);
   asn1Init_TS24301IE_ReplayedNASMsgContainer (pvalue);

   pvalue->length = 56404;

   pvalue->contents.numocts = 1;
   pvalue->contents.data = (OSOCTET*) rtxMemAlloc (pctxt, 1);
   {
      static const OSOCTET testdata[] = {
      0xed };
      OSCRTLSAFEMEMCPY ((void*)pvalue->contents.data, 1, testdata, 1);
   }
   return (pvalue);
}

TS24301IE_NetworkPolicy* asn1Test_TS24301IE_NetworkPolicy (OSCTXT* pctxt)
{
   TS24301IE_NetworkPolicy* pvalue = rtxMemAllocType (pctxt, TS24301IE_NetworkPolicy);
   asn1Init_TS24301IE_NetworkPolicy (pvalue);

   pvalue->spare = 4;

   pvalue->redirPolicy = 0;
   return (pvalue);
}

TS24301IE_UEAddlSecurityCapability*
    asn1Test_TS24301IE_UEAddlSecurityCapability (OSCTXT* pctxt)
{
   TS24301IE_UEAddlSecurityCapability* pvalue = rtxMemAllocType (pctxt, TS24301IE_UEAddlSecurityCapability);

   pvalue->length = 241;

   pvalue->contents.elem[0] = 0;

   pvalue->contents.elem[1] = 0;

   pvalue->contents.elem[2] = 1;

   pvalue->contents.elem[3] = 1;

   pvalue->contents.elem[4] = 1;

   pvalue->contents.elem[5] = 1;

   pvalue->contents.elem[6] = 0;

   pvalue->contents.elem[7] = 0;

   pvalue->contents.elem[8] = 1;

   pvalue->contents.elem[9] = 0;

   pvalue->contents.elem[10] = 0;

   pvalue->contents.elem[11] = 0;

   pvalue->contents.elem[12] = 0;

   pvalue->contents.elem[13] = 0;

   pvalue->contents.elem[14] = 0;

   pvalue->contents.elem[15] = 0;

   pvalue->contents.elem[16] = 0;

   pvalue->contents.elem[17] = 1;

   pvalue->contents.elem[18] = 1;

   pvalue->contents.elem[19] = 1;

   pvalue->contents.elem[20] = 1;

   pvalue->contents.elem[21] = 1;

   pvalue->contents.elem[22] = 0;

   pvalue->contents.elem[23] = 0;

   pvalue->contents.elem[24] = 1;

   pvalue->contents.elem[25] = 1;

   pvalue->contents.elem[26] = 1;

   pvalue->contents.elem[27] = 1;

   pvalue->contents.elem[28] = 1;

   pvalue->contents.elem[29] = 1;

   pvalue->contents.elem[30] = 0;

   pvalue->contents.elem[31] = 1;

   return (pvalue);
}

TS24301IE_UEStatus* asn1Test_TS24301IE_UEStatus (OSCTXT* pctxt)
{
   TS24301IE_UEStatus* pvalue = rtxMemAllocType (pctxt, TS24301IE_UEStatus);
   asn1Init_TS24301IE_UEStatus (pvalue);

   pvalue->length = 141;

   pvalue->spare = 25;

   pvalue->n1RegStatus = 0;

   pvalue->s1RegStatus = 0;
   return (pvalue);
}

TS24301IE_AdditionalInfoReq*
    asn1Test_TS24301IE_AdditionalInfoReq (OSCTXT* pctxt)
{
   TS24301IE_AdditionalInfoReq* pvalue = rtxMemAllocType (pctxt, TS24301IE_AdditionalInfoReq);
   asn1Init_TS24301IE_AdditionalInfoReq (pvalue);

   pvalue->spare = 13;

   pvalue->dataRequested = 1;
   return (pvalue);
}

TS24301IE_CipherDataSet* asn1Test_TS24301IE_CipherDataSet (OSCTXT* pctxt)
{
   TS24301IE_CipherDataSet* pvalue = rtxMemAllocType (pctxt, TS24301IE_CipherDataSet);
   asn1Init_TS24301IE_CipherDataSet (pvalue);

   {
      static const OSOCTET testdata[] = { 
      0x35, 0xbf, 0x87, 0x61, 0x61, 0xca, 0x35, 0xb2, 
      0x35, 0x23, 0x2b, 0x8f, 0x12, 0x3d, 0x31, 0x7e };
      OSCRTLSAFEMEMCPY ((void*)pvalue->cipherKey, 16, testdata, 16);
   }

   pvalue->spare = 1;

   pvalue->c0Len = 27;

   pvalue->c0.numocts = 4;
   pvalue->c0.data = (OSOCTET*) rtxMemAlloc (pctxt, 4);
   {
      static const OSOCTET testdata[] = {
      0x70, 0x15, 0x38, 0x6a };
      OSCRTLSAFEMEMCPY ((void*)pvalue->c0.data, 4, testdata, 4);
   }

   pvalue->posSIBType.elem[0] = 1;

   pvalue->posSIBType.elem[1] = 0;

   pvalue->posSIBType.elem[2] = 0;

   pvalue->posSIBType.elem[3] = 0;

   pvalue->posSIBType.elem[4] = 0;

   pvalue->posSIBType.elem[5] = 0;

   pvalue->posSIBType.elem[6] = 1;

   pvalue->posSIBType.elem[7] = 1;

   pvalue->posSIBType.elem[8] = 1;

   pvalue->posSIBType.elem[9] = 1;

   pvalue->posSIBType.elem[10] = 1;

   pvalue->posSIBType.elem[11] = 0;

   pvalue->posSIBType.elem[12] = 1;

   pvalue->posSIBType.elem[13] = 1;

   pvalue->posSIBType.elem[14] = 1;

   pvalue->posSIBType.elem[15] = 1;

   pvalue->posSIBType.elem[16] = 1;

   pvalue->posSIBType.elem[17] = 0;

   pvalue->posSIBType.elem[18] = 1;

   pvalue->posSIBType.elem[19] = 0;

   pvalue->posSIBType.elem[20] = 0;

   pvalue->posSIBType.elem[21] = 0;

   pvalue->posSIBType.elem[22] = 1;

   pvalue->posSIBType.elem[23] = 0;

   pvalue->posSIBType.elem[24] = 0;

   pvalue->posSIBType.elem[25] = 0;

   pvalue->posSIBType.elem[26] = 0;

   pvalue->spare2 = 10;

   pvalue->validityStartTime.year = 31;

   pvalue->validityStartTime.month = 210;

   pvalue->validityStartTime.day = 53;

   pvalue->validityStartTime.hour = 142;

   pvalue->validityStartTime.minute = 140;

   pvalue->validityStartTime.second = 172;

   pvalue->validityStartTime.timezone = 227;

   pvalue->validityDuration = 30752;

   pvalue->taiList.length = 0; /* length will be calculated */

   pvalue->taiList.idents.n = 1;

   pvalue->taiList.idents.elem[0].spare = 0;

   pvalue->taiList.idents.elem[0].typeOfList = 1;

   pvalue->taiList.idents.elem[0].numElements = 8;

   switch (pvalue->taiList.idents.elem[0].typeOfList) {
      /* partTrkIdentList0 */
      case 0:

         rtxStrncpy (pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList0.mcc_mnc.mcc, 4, "651", 3);
         rtxStrncpy (pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList0.mcc_mnc.mnc, 4, "01", 3);

         pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList0.tacs.n = 3;
         {
            static const OSOCTET testdata[] = { 
            0xe2, 0xcb };
            OSCRTLSAFEMEMCPY ((void*)pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList0.tacs.elem[0].data, 2, testdata, 2);
         }

         {
            static const OSOCTET testdata[] = { 
            0xa4, 0x23 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList0.tacs.elem[1].data, 2, testdata, 2);
         }

         {
            static const OSOCTET testdata[] = { 
            0x34, 0x54 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList0.tacs.elem[2].data, 2, testdata, 2);
         }

         break;

      /* partTrkIdentList1 */
      case 1:

         rtxStrncpy (pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList1.mcc_mnc.mcc, 4, "651", 3);
         rtxStrncpy (pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList1.mcc_mnc.mnc, 4, "02", 3);

         {
            static const OSOCTET testdata[] = { 
            0xd1, 0xa6 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList1.tac.data, 2, testdata, 2);
         }
         break;

      /* partTrkIdentList2 */
      case 2:
         pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList2.n = 1;

         rtxStrncpy (pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList2.elem[0].mcc_mnc.mcc, 4, "244", 3);
         rtxStrncpy (pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList2.elem[0].mcc_mnc.mnc, 4, "09", 3);

         {
            static const OSOCTET testdata[] = { 
            0x7f, 0xb };
            OSCRTLSAFEMEMCPY ((void*)pvalue->taiList.idents.elem[0].elements.u.partTrkIdentList2.elem[0].tac.data, 2, testdata, 2);
         }

         break;

      default: break;
   }

   return (pvalue);
}

TS24301IE_CipherKeyData* asn1Test_TS24301IE_CipherKeyData (OSCTXT* pctxt)
{
   TS24301IE_CipherKeyData* pvalue = rtxMemAllocType (pctxt, TS24301IE_CipherKeyData);
   asn1Init_TS24301IE_CipherKeyData (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->dataSet.n = 1;

   {
      static const OSOCTET testdata[] = { 
      0x10, 0xdd, 0x6d, 0xe9, 0x68, 0x08, 0xb4, 0x08, 
      0xdb, 0xe9, 0x96, 0x68, 0x96, 0xf9, 0x80, 0x27 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->dataSet.elem[0].cipherKey, 16, testdata, 16);
   }

   pvalue->dataSet.elem[0].spare = 6;

   pvalue->dataSet.elem[0].c0Len = 22;

   pvalue->dataSet.elem[0].c0.numocts = 2;
   pvalue->dataSet.elem[0].c0.data = (OSOCTET*) rtxMemAlloc (pctxt, 2);
   {
      static const OSOCTET testdata[] = {
      0xdf, 0x7b };
      OSCRTLSAFEMEMCPY ((void*)pvalue->dataSet.elem[0].c0.data, 2, testdata, 2);
   }

   pvalue->dataSet.elem[0].posSIBType.elem[0] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[1] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[2] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[3] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[4] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[5] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[6] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[7] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[8] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[9] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[10] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[11] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[12] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[13] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[14] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[15] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[16] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[17] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[18] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[19] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[20] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[21] = 0;

   pvalue->dataSet.elem[0].posSIBType.elem[22] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[23] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[24] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[25] = 1;

   pvalue->dataSet.elem[0].posSIBType.elem[26] = 1;

   pvalue->dataSet.elem[0].spare2 = 13;

   pvalue->dataSet.elem[0].validityStartTime.year = 246;

   pvalue->dataSet.elem[0].validityStartTime.month = 62;

   pvalue->dataSet.elem[0].validityStartTime.day = 97;

   pvalue->dataSet.elem[0].validityStartTime.hour = 237;

   pvalue->dataSet.elem[0].validityStartTime.minute = 192;

   pvalue->dataSet.elem[0].validityStartTime.second = 17;

   pvalue->dataSet.elem[0].validityStartTime.timezone = 55;

   pvalue->dataSet.elem[0].validityDuration = 4553;

   pvalue->dataSet.elem[0].taiList.length = 0; /* length will be calculated */

   pvalue->dataSet.elem[0].taiList.idents.n = 1;

   pvalue->dataSet.elem[0].taiList.idents.elem[0].spare = 0;

   pvalue->dataSet.elem[0].taiList.idents.elem[0].typeOfList = 0;

   pvalue->dataSet.elem[0].taiList.idents.elem[0].numElements = 28;

   switch (pvalue->dataSet.elem[0].taiList.idents.elem[0].typeOfList) {
      /* partTrkIdentList0 */
      case 0:

         rtxStrncpy (pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList0.mcc_mnc.mcc, 4, "270", 3);
         rtxStrncpy (pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList0.mcc_mnc.mnc, 4, "01", 3);

         pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList0.tacs.n = 1;
         {
            static const OSOCTET testdata[] = { 
            0x23, 0x89 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList0.tacs.elem[0].data, 2, testdata, 2);
         }

         break;

      /* partTrkIdentList1 */
      case 1:

         rtxStrncpy (pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList1.mcc_mnc.mcc, 4, "244", 3);
         rtxStrncpy (pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList1.mcc_mnc.mnc, 4, "05", 3);

         {
            static const OSOCTET testdata[] = { 
            0x8b, 0xd2 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList1.tac.data, 2, testdata, 2);
         }
         break;

      /* partTrkIdentList2 */
      case 2:
         pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList2.n = 1;

         rtxStrncpy (pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList2.elem[0].mcc_mnc.mcc, 4, "404", 3);
         rtxStrncpy (pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList2.elem[0].mcc_mnc.mnc, 4, "84", 3);

         {
            static const OSOCTET testdata[] = { 
            0x7d, 0xd0 };
            OSCRTLSAFEMEMCPY ((void*)pvalue->dataSet.elem[0].taiList.idents.elem[0].elements.u.partTrkIdentList2.elem[0].tac.data, 2, testdata, 2);
         }

         break;

      default: break;
   }

   return (pvalue);
}

TS24301IE_N1UENetCapability*
    asn1Test_TS24301IE_N1UENetCapability (OSCTXT* pctxt)
{
   TS24301IE_N1UENetCapability* pvalue = rtxMemAllocType (pctxt, TS24301IE_N1UENetCapability);
   asn1Init_TS24301IE_N1UENetCapability (pvalue);

   pvalue->length = 8;

   pvalue->spare = 0;

   pvalue->pnbCIoT = 2;

   pvalue->upCIoT = 0;

   pvalue->hcCpCIoT = 1;

   pvalue->n3Data = 1;

   pvalue->cpCIoT = 1;
   return (pvalue);
}

TS24301IE_UERadioCapIdAvailability*
    asn1Test_TS24301IE_UERadioCapIdAvailability (OSCTXT* pctxt)
{
   TS24301IE_UERadioCapIdAvailability* pvalue = rtxMemAllocType (pctxt, TS24301IE_UERadioCapIdAvailability);
   asn1Init_TS24301IE_UERadioCapIdAvailability (pvalue);

   pvalue->spare = 0;

   pvalue->value = 4;
   return (pvalue);
}

TS24301IE_UERadioCapIdRequest*
    asn1Test_TS24301IE_UERadioCapIdRequest (OSCTXT* pctxt)
{
   TS24301IE_UERadioCapIdRequest* pvalue = rtxMemAllocType (pctxt, TS24301IE_UERadioCapIdRequest);
   asn1Init_TS24301IE_UERadioCapIdRequest (pvalue);

   pvalue->spare = 15;

   pvalue->urcid_A = 0;
   return (pvalue);
}

TS24301IE_UERadioCapId* asn1Test_TS24301IE_UERadioCapId (OSCTXT* pctxt)
{
   TS24301IE_UERadioCapId* pvalue = rtxMemAllocType (pctxt, TS24301IE_UERadioCapId);
   asn1Init_TS24301IE_UERadioCapId (pvalue);

   pvalue->length = 153;

   pvalue->capId.numocts = 12;
   pvalue->capId.data = (OSOCTET*) rtxMemAlloc (pctxt, 12);
   {
      static const OSOCTET testdata[] = {
      0xe9, 0x7b, 0x41, 0xab, 0x8c, 0xf7, 0x06, 0x20, 
      0x20, 0x30, 0xb3, 0xc3 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->capId.data, 12, testdata, 12);
   }
   return (pvalue);
}

TS24301IE_UERadioCapIdDeletionInd*
    asn1Test_TS24301IE_UERadioCapIdDeletionInd (OSCTXT* pctxt)
{
   TS24301IE_UERadioCapIdDeletionInd* pvalue = rtxMemAllocType (pctxt, TS24301IE_UERadioCapIdDeletionInd);
   asn1Init_TS24301IE_UERadioCapIdDeletionInd (pvalue);

   pvalue->spare = 0;

   pvalue->deletionReq = 4;
   return (pvalue);
}

TS24301IE_WUSAssistInfoType*
    asn1Test_TS24301IE_WUSAssistInfoType (OSCTXT* pctxt)
{
   TS24301IE_WUSAssistInfoType* pvalue = rtxMemAllocType (pctxt, TS24301IE_WUSAssistInfoType);

   pvalue->infoType = TS24301IE_InformationType_itUEPagingProbInfo;

   pvalue->infoValue = 22;
   return (pvalue);
}

TS24301IE_WUSAssistanceInfo*
    asn1Test_TS24301IE_WUSAssistanceInfo (OSCTXT* pctxt)
{
   TS24301IE_WUSAssistanceInfo* pvalue = rtxMemAllocType (pctxt, TS24301IE_WUSAssistanceInfo);
   asn1Init_TS24301IE_WUSAssistanceInfo (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->types.n = 1;

   pvalue->types.elem[0].infoType = TS24301IE_InformationType_itUEPagingProbInfo;

   pvalue->types.elem[0].infoValue = 1;

   return (pvalue);
}

TS24301IE_APNAggMaxBitRateExt*
    asn1Test_TS24301IE_APNAggMaxBitRateExt (OSCTXT* pctxt)
{
   TS24301IE_APNAggMaxBitRateExt* pvalue = rtxMemAllocType (pctxt, TS24301IE_APNAggMaxBitRateExt);

   pvalue->apnAmbrforDL = 12;

   pvalue->apnAmbrforUL = 222;
   return (pvalue);
}

TS24301IE_APNAggMaxBitRate* asn1Test_TS24301IE_APNAggMaxBitRate (OSCTXT* pctxt)
{
   TS24301IE_APNAggMaxBitRate* pvalue = rtxMemAllocType (pctxt, TS24301IE_APNAggMaxBitRate);
   asn1Init_TS24301IE_APNAggMaxBitRate (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->apnAmbrforDL = 76;

   pvalue->apnAmbrforUL = 220;

   /* zero elements */
   return (pvalue);
}

TS24301IE_EPSQoSBitRates* asn1Test_TS24301IE_EPSQoSBitRates (OSCTXT* pctxt)
{
   TS24301IE_EPSQoSBitRates* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSQoSBitRates);

   pvalue->maxBitRateforUL = 102;

   pvalue->maxBitRateforDL = 150;

   pvalue->guarBitRateforUL = 21;

   pvalue->guarBitRateforDL = 84;
   return (pvalue);
}

TS24301IE_EPSQualityOfService*
    asn1Test_TS24301IE_EPSQualityOfService (OSCTXT* pctxt)
{
   TS24301IE_EPSQualityOfService* pvalue = rtxMemAllocType (pctxt, TS24301IE_EPSQualityOfService);
   asn1Init_TS24301IE_EPSQualityOfService (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->qci = 21;

   /* zero elements */
   return (pvalue);
}

TS24301IE_ESMInfoXferFlag* asn1Test_TS24301IE_ESMInfoXferFlag (OSCTXT* pctxt)
{
   TS24301IE_ESMInfoXferFlag* pvalue = rtxMemAllocType (pctxt, TS24301IE_ESMInfoXferFlag);
   asn1Init_TS24301IE_ESMInfoXferFlag (pvalue);

   pvalue->spare = 4;

   pvalue->eitValue = 0;
   return (pvalue);
}

TS24301IE_PDNAddress* asn1Test_TS24301IE_PDNAddress (OSCTXT* pctxt)
{
   TS24301IE_PDNAddress* pvalue = rtxMemAllocType (pctxt, TS24301IE_PDNAddress);
   asn1Init_TS24301IE_PDNAddress (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->spare = 19;

   pvalue->pdnTypeValue = TS24301IE_PDNTypeValue_ipv4;

   {
      static const OSOCTET testdata[] = { 
      0x27, 0x4f, 0x65, 0xfa };
      pvalue->pdnAddrInfo.numocts = 4;
      OSCRTLSAFEMEMCPY ((void*)pvalue->pdnAddrInfo.data, 4, testdata, 4);
   }
   return (pvalue);
}

TS24301IE_PDNType* asn1Test_TS24301IE_PDNType (OSCTXT* pctxt)
{
   TS24301IE_PDNType* pvalue = rtxMemAllocType (pctxt, TS24301IE_PDNType);
   asn1Init_TS24301IE_PDNType (pvalue);

   pvalue->spare = 0;

   pvalue->pdnTypeValue = TS24301IE_PDNTypeValue_ipv4;
   return (pvalue);
}

TS24301IE_ReattemptInd* asn1Test_TS24301IE_ReattemptInd (OSCTXT* pctxt)
{
   TS24301IE_ReattemptInd* pvalue = rtxMemAllocType (pctxt, TS24301IE_ReattemptInd);
   asn1Init_TS24301IE_ReattemptInd (pvalue);

   pvalue->spare = 19;

   pvalue->eplmNcValue = 0;

   pvalue->ratcValue = 1;
   return (pvalue);
}

TS24301IE_RemoteUECtxt* asn1Test_TS24301IE_RemoteUECtxt (OSCTXT* pctxt)
{
   TS24301IE_RemoteUECtxt* pvalue = rtxMemAllocType (pctxt, TS24301IE_RemoteUECtxt);
   asn1Init_TS24301IE_RemoteUECtxt (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->numUserIdents = 227;

   pvalue->userIdentLength = 110;

   pvalue->userIdents.n = 6;
   pvalue->userIdents.elem = rtxMemAllocArrayZ (pctxt, 6, OSDynOctStr);
   pvalue->userIdents.elem[0].numocts = 15;
   pvalue->userIdents.elem[0].data = (OSOCTET*) rtxMemAlloc (pctxt, 15);
   {
      static const OSOCTET testdata[] = {
      0x0e, 0x54, 0x9a, 0xc1, 0x97, 0xd3, 0x66, 0x66, 
      0xdf, 0x45, 0x33, 0x3c, 0xac, 0xc9, 0xd0 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->userIdents.elem[0].data, 15, testdata, 15);
   }

   pvalue->userIdents.elem[1].numocts = 14;
   pvalue->userIdents.elem[1].data = (OSOCTET*) rtxMemAlloc (pctxt, 14);
   {
      static const OSOCTET testdata[] = {
      0x5e, 0x9b, 0x24, 0xa9, 0xc2, 0xf2, 0x8e, 0x3d, 
      0xab, 0x6f, 0x78, 0x10, 0xdd, 0xac };
      OSCRTLSAFEMEMCPY ((void*)pvalue->userIdents.elem[1].data, 14, testdata, 14);
   }

   pvalue->userIdents.elem[2].numocts = 13;
   pvalue->userIdents.elem[2].data = (OSOCTET*) rtxMemAlloc (pctxt, 13);
   {
      static const OSOCTET testdata[] = {
      0xeb, 0x80, 0x15, 0x2d, 0x97, 0xe8, 0x14, 0xfd, 
      0x48, 0x59, 0x31, 0x84, 0x85 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->userIdents.elem[2].data, 13, testdata, 13);
   }

   pvalue->userIdents.elem[3].numocts = 13;
   pvalue->userIdents.elem[3].data = (OSOCTET*) rtxMemAlloc (pctxt, 13);
   {
      static const OSOCTET testdata[] = {
      0x55, 0x07, 0xd9, 0x70, 0xaa, 0x03, 0xb3, 0x9d, 
      0x11, 0xf0, 0xc8, 0x80, 0x6a };
      OSCRTLSAFEMEMCPY ((void*)pvalue->userIdents.elem[3].data, 13, testdata, 13);
   }

   pvalue->userIdents.elem[4].numocts = 2;
   pvalue->userIdents.elem[4].data = (OSOCTET*) rtxMemAlloc (pctxt, 2);
   {
      static const OSOCTET testdata[] = {
      0xde, 0x96 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->userIdents.elem[4].data, 2, testdata, 2);
   }

   pvalue->userIdents.elem[5].numocts = 14;
   pvalue->userIdents.elem[5].data = (OSOCTET*) rtxMemAlloc (pctxt, 14);
   {
      static const OSOCTET testdata[] = {
      0x4a, 0x96, 0x68, 0xf7, 0x2e, 0xd0, 0x0c, 0x2c, 
      0x19, 0x65, 0xdd, 0x1d, 0x6b, 0x58 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->userIdents.elem[5].data, 14, testdata, 14);
   }

   return (pvalue);
}

TS24301IE_RemoteUECtxtList* asn1Test_TS24301IE_RemoteUECtxtList (OSCTXT* pctxt)
{
   TS24301IE_RemoteUECtxtList* pvalue = rtxMemAllocType (pctxt, TS24301IE_RemoteUECtxtList);
   asn1Init_TS24301IE_RemoteUECtxtList (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->numRemUECtxts = 83;

   /* zero elements */

   pvalue->spare = 1;

   pvalue->addrType = TS24301IE_RemoteUEAddrType_remUENoIp;

   {
      static const OSOCTET testdata[] = { 
      0xb1, 0xe2, 0x9c, 0x34, 0x96, 0x3a };
      pvalue->addrInfo.numocts = 6;
      OSCRTLSAFEMEMCPY ((void*)pvalue->addrInfo.data, 6, testdata, 6);
   }
   return (pvalue);
}

TS24301IE_PKMFAddressType* asn1Test_TS24301IE_PKMFAddressType (OSCTXT* pctxt)
{
   TS24301IE_PKMFAddressType* pvalue = rtxMemAllocType (pctxt, TS24301IE_PKMFAddressType);
   asn1Init_TS24301IE_PKMFAddressType (pvalue);

   pvalue->spare = 29;

   pvalue->addrType = 0;

   {
      pvalue->addrInfo.numocts = 0;
   }
   return (pvalue);
}

TS24301IE_PKMFAddress* asn1Test_TS24301IE_PKMFAddress (OSCTXT* pctxt)
{
   TS24301IE_PKMFAddress* pvalue = rtxMemAllocType (pctxt, TS24301IE_PKMFAddress);
   asn1Init_TS24301IE_PKMFAddress (pvalue);

   pvalue->length = 0; /* length will be calculated */

   /* zero elements */
   return (pvalue);
}

TS24301IE_HdrCompressConfig*
    asn1Test_TS24301IE_HdrCompressConfig (OSCTXT* pctxt)
{
   TS24301IE_HdrCompressConfig* pvalue = rtxMemAllocType (pctxt, TS24301IE_HdrCompressConfig);
   asn1Init_TS24301IE_HdrCompressConfig (pvalue);

   pvalue->length = 0; /* length will be calculated */

   pvalue->spare1 = 1;

   pvalue->profile104 = 0;

   pvalue->profile103 = 0;

   pvalue->profile102 = 1;

   pvalue->profile006 = 0;

   pvalue->profile004 = 0;

   pvalue->profile003 = 0;

   pvalue->profile002 = 1;

   {
      static const OSOCTET testdata[] = { 
      0x1e, 0x98 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->maxCID, 2, testdata, 2);
   }

   pvalue->addlSetupType.numocts = 4;
   pvalue->addlSetupType.data = (OSOCTET*) rtxMemAlloc (pctxt, 4);
   {
      static const OSOCTET testdata[] = {
      0x4c, 0x69, 0x73, 0x79 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->addlSetupType.data, 4, testdata, 4);
   }

   {
      static const OSOCTET testdata[] = { 
      0x3 };
      pvalue->addlSetupContainer.numocts = 1;
      OSCRTLSAFEMEMCPY ((void*)pvalue->addlSetupContainer.data, 1, testdata, 1);
   }
   return (pvalue);
}

TS24301IE_CtrlPlaneOnlyInd* asn1Test_TS24301IE_CtrlPlaneOnlyInd (OSCTXT* pctxt)
{
   TS24301IE_CtrlPlaneOnlyInd* pvalue = rtxMemAllocType (pctxt, TS24301IE_CtrlPlaneOnlyInd);
   asn1Init_TS24301IE_CtrlPlaneOnlyInd (pvalue);

   pvalue->spare4 = 1;

   pvalue->spare3 = 1;

   pvalue->spare2 = 1;

   pvalue->cpoiValue = 1;
   return (pvalue);
}

TS24301IE_ReleaseAssistInd* asn1Test_TS24301IE_ReleaseAssistInd (OSCTXT* pctxt)
{
   TS24301IE_ReleaseAssistInd* pvalue = rtxMemAllocType (pctxt, TS24301IE_ReleaseAssistInd);
   asn1Init_TS24301IE_ReleaseAssistInd (pvalue);

   pvalue->spare4 = 1;

   pvalue->spare3 = 0;

   pvalue->ddx = TS24301IE_ReleaseAssistInd_ddx_ddxNoInfo;
   return (pvalue);
}

TS24301IE_HdrCompressConfigStat*
    asn1Test_TS24301IE_HdrCompressConfigStat (OSCTXT* pctxt)
{
   TS24301IE_HdrCompressConfigStat* pvalue = rtxMemAllocType (pctxt, TS24301IE_HdrCompressConfigStat);

   pvalue->length = 0; /* length will be calculated */

   {
      static const OSOCTET testdata[] = { 
      0x36, 0x61 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->ebi, 2, testdata, 2);
   }
   return (pvalue);
}

TS24301IE_ExtAPNAggMaxBitRate*
    asn1Test_TS24301IE_ExtAPNAggMaxBitRate (OSCTXT* pctxt)
{
   TS24301IE_ExtAPNAggMaxBitRate* pvalue = rtxMemAllocType (pctxt, TS24301IE_ExtAPNAggMaxBitRate);

   pvalue->extApnAmbrUnitForDL = 244;

   {
      static const OSOCTET testdata[] = { 
      0x52, 0x15 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->extApnAmbrForDL, 2, testdata, 2);
   }

   pvalue->extApnAmbrUnitForUL = 139;

   {
      static const OSOCTET testdata[] = { 
      0x8c, 0xda };
      OSCRTLSAFEMEMCPY ((void*)pvalue->extApnAmbrForUL, 2, testdata, 2);
   }
   return (pvalue);
}

