/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2.3, Date: 13-Jul-2020.
 */
#include "TS24301Msgs.h"
#include "rtsrc/rtPrintToStream.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtsrc/rtBCD.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

int asn1PrtToStrm_TS24301Msg_AttachComplete (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AttachComplete* pvalue)
{
   asn1PrtToStrm_TS24301IE_ESMMessageContainer (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_AuthResponse (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AuthResponse* pvalue)
{
   asn1PrtToStrm_TS24301IE_AuthRespParam (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_DLNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DLNASTransport* pvalue)
{
   asn1PrtToStrm_TS24301IE_NASMessageContainer (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_EMMStatus (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_EMMStatus* pvalue)
{
   asn1PrtToStrm_TS24301IE_EMMCause (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_IdentResp (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_IdentResp* pvalue)
{
   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_SecModeReject (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_SecModeReject* pvalue)
{
   asn1PrtToStrm_TS24301IE_EMMCause (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ULNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ULNASTransport* pvalue)
{
   asn1PrtToStrm_TS24301IE_NASMessageContainer (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_GenNASTransport_addnInfo (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_GenNASTransport_addnInfo* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamHexStr (pctxt, name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_GenNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_GenNASTransport* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_GenMsgContainerType (pctxt, "genMsgContainerType", &pvalue->genMsgContainerType);

   asn1PrtToStrm_TS24301IE_GenMessageContainer (pctxt, "genMsgContainer", &pvalue->genMsgContainer);

   if (pvalue->m.addnInfoPresent) {
      asn1PrtToStrm_TS24301Msg_GenNASTransport_addnInfo (pctxt, "addnInfo", &pvalue->addnInfo);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_DLGenNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DLGenNASTransport* pvalue)
{
   asn1PrtToStrm_TS24301Msg_GenNASTransport (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ULGenNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ULGenNASTransport* pvalue)
{
   asn1PrtToStrm_TS24301Msg_GenNASTransport (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ESMStatus (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ESMStatus* pvalue)
{
   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_RemoteUEReportResp_ (OSCTXT *pctxt, 
   const char* name, const void* pvalue)
{
   OS_UNUSED_ARG (pvalue);
   rtPrintToStreamIndent (pctxt);
   rtxPrintToStreamNull (pctxt, name);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_AttachAccept (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AttachAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_EPSAttachResult (pctxt, "result", &pvalue->result);

   asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "t3412Value", &pvalue->t3412Value);

   asn1PrtToStrm_TS24301IE_TrackingAreaIdentList (pctxt, "taiList", &pvalue->taiList);

   asn1PrtToStrm_TS24301IE_ESMMessageContainer (pctxt, "esmMessageContainer", &pvalue->esmMessageContainer);

   if (pvalue->m.gutiPresent) {
      asn1PrtToStrm_TS24301IE_EPSMobileIdentity (pctxt, "guti", &pvalue->guti);
   }

   if (pvalue->m.locAreaIdentPresent) {
      asn1PrtToStrm_TS24008IE_LocAreaIdent (pctxt, "locAreaIdent", &pvalue->locAreaIdent);
   }

   if (pvalue->m.msIdentityPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "msIdentity", &pvalue->msIdentity);
   }

   if (pvalue->m.emmCausePresent) {
      asn1PrtToStrm_TS24301IE_EMMCause (pctxt, "emmCause", &pvalue->emmCause);
   }

   if (pvalue->m.t3402Present) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "t3402", &pvalue->t3402);
   }

   if (pvalue->m.t3423Present) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "t3423", &pvalue->t3423);
   }

   if (pvalue->m.equivPLMNsPresent) {
      asn1PrtToStrm_TS24008IE_PLMNList (pctxt, "equivPLMNs", &pvalue->equivPLMNs);
   }

   if (pvalue->m.emergNumListPresent) {
      asn1PrtToStrm_TS24008IE_EmergencyNumberList (pctxt, "emergNumList", &pvalue->emergNumList);
   }

   if (pvalue->m.epsNetFeatSuppPresent) {
      asn1PrtToStrm_TS24301IE_EPSNetworkFeatureSupport (pctxt, "epsNetFeatSupp", &pvalue->epsNetFeatSupp);
   }

   if (pvalue->m.addnUpdateResultPresent) {
      asn1PrtToStrm_TS24301IE_AddnUpdateResult (pctxt, "addnUpdateResult", &pvalue->addnUpdateResult);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3412ExtValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3412ExtValue", &pvalue->t3412ExtValue);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.t3324ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3324Value", &pvalue->t3324Value);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extDRXParamsPresent) {
         asn1PrtToStrm_TS24008IE_ExtDRXParams (pctxt, "extDRXParams", &pvalue->extDRXParams);
      }
      if (pvalue->m.dcnIdPresent) {
         asn1PrtToStrm_TS24008IE_DcnID (pctxt, "dcnId", &pvalue->dcnId);
      }
      if (pvalue->m.smsServicesStatusPresent) {
         asn1PrtToStrm_TS24301IE_SMSServicesStatus (pctxt, "smsServicesStatus", &pvalue->smsServicesStatus);
      }
   }

   if (pvalue->m._v14ExtPresent) {
      if (pvalue->m.non3GPPNetPoliciesPresent) {
         asn1PrtToStrm_TS24008IE_Non3GPPNetPolicies (pctxt, "non3GPPNetPolicies", &pvalue->non3GPPNetPolicies);
      }
      if (pvalue->m.t3448ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3448Value", &pvalue->t3448Value);
      }
      if (pvalue->m.networkPolicyPresent) {
         asn1PrtToStrm_TS24301IE_NetworkPolicy (pctxt, "networkPolicy", &pvalue->networkPolicy);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.t3447ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3447Value", &pvalue->t3447Value);
      }
      if (pvalue->m.extEmergencyNumberListPresent) {
         asn1PrtToStrm_TS24301IE_ExtEmergencyNumberList (pctxt, "extEmergencyNumberList", &pvalue->extEmergencyNumberList);
      }
      if (pvalue->m.cipherKeyDataPresent) {
         asn1PrtToStrm_TS24301IE_CipherKeyData (pctxt, "cipherKeyData", &pvalue->cipherKeyData);
      }
   }

   if (pvalue->m._v16ExtPresent) {
      if (pvalue->m.ueradioCapabilityIDPresent) {
         asn1PrtToStrm_TS24301IE_UERadioCapId (pctxt, "ueradioCapabilityID", &pvalue->ueradioCapabilityID);
      }
      if (pvalue->m.ueradioCapIDDeleteIndPresent) {
         asn1PrtToStrm_TS24301IE_UERadioCapIdDeletionInd (pctxt, "ueradioCapIDDeleteInd", &pvalue->ueradioCapIDDeleteInd);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_AttachReject (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AttachReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_EMMCause (pctxt, "emmCause", &pvalue->emmCause);

   if (pvalue->m.esmMsgContPresent) {
      asn1PrtToStrm_TS24301IE_ESMMessageContainer (pctxt, "esmMsgCont", &pvalue->esmMsgCont);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3346ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3346Value", &pvalue->t3346Value);
      }
      if (pvalue->m.t3402ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3402Value", &pvalue->t3402Value);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.extEMMCausePresent) {
         asn1PrtToStrm_TS24301IE_ExtEMMCause (pctxt, "extEMMCause", &pvalue->extEMMCause);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_AttachRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AttachRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_NASKeySetIdentifier (pctxt, "nasKeySetIdentifier", &pvalue->nasKeySetIdentifier);

   asn1PrtToStrm_TS24301IE_EPSAttachType (pctxt, "epsAttachType", &pvalue->epsAttachType);

   asn1PrtToStrm_TS24301IE_EPSMobileIdentity (pctxt, "oldGUTIOrIMSI", &pvalue->oldGUTIOrIMSI);

   asn1PrtToStrm_TS24301IE_UENetworkCapability (pctxt, "ueNetworkCapability", &pvalue->ueNetworkCapability);

   asn1PrtToStrm_TS24301IE_ESMMessageContainer (pctxt, "esmMessageContainer", &pvalue->esmMessageContainer);

   if (pvalue->m.oldP_TMSISignaturePresent) {
      asn1PrtToStrm_TS24008IE_P_TMSISignature (pctxt, "oldP_TMSISignature", &pvalue->oldP_TMSISignature);
   }

   if (pvalue->m.additionalGUTIPresent) {
      asn1PrtToStrm_TS24301IE_EPSMobileIdentity (pctxt, "additionalGUTI", &pvalue->additionalGUTI);
   }

   if (pvalue->m.lastVisitedRegisteredTAIPresent) {
      asn1PrtToStrm_TS24301IE_TrackingAreaIdent (pctxt, "lastVisitedRegisteredTAI", &pvalue->lastVisitedRegisteredTAI);
   }

   if (pvalue->m.drxParameterPresent) {
      asn1PrtToStrm_TS24008IE_DRXParameter (pctxt, "drxParameter", &pvalue->drxParameter);
   }

   if (pvalue->m.msNetworkCapabilityPresent) {
      asn1PrtToStrm_TS24008IE_MSNetworkCapability (pctxt, "msNetworkCapability", &pvalue->msNetworkCapability);
   }

   if (pvalue->m.oldLocAreaIdentPresent) {
      asn1PrtToStrm_TS24008IE_LocAreaIdent (pctxt, "oldLocAreaIdent", &pvalue->oldLocAreaIdent);
   }

   if (pvalue->m.tmsiStatusPresent) {
      asn1PrtToStrm_TS24008IE_TMSIStatus (pctxt, "tmsiStatus", &pvalue->tmsiStatus);
   }

   if (pvalue->m.mobileStationClassmark2Present) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark2 (pctxt, "mobileStationClassmark2", &pvalue->mobileStationClassmark2);
   }

   if (pvalue->m.mobileStationClassmark3Present) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark3 (pctxt, "mobileStationClassmark3", &pvalue->mobileStationClassmark3);
   }

   if (pvalue->m.supportedCodecsPresent) {
      asn1PrtToStrm_TS24008IE_SupportedCodecList (pctxt, "supportedCodecs", &pvalue->supportedCodecs);
   }

   if (pvalue->m.addnUpdateTypePresent) {
      asn1PrtToStrm_TS24301IE_AddnUpdateType (pctxt, "addnUpdateType", &pvalue->addnUpdateType);
   }

   if (pvalue->m._v9ExtPresent) {
      if (pvalue->m.voiceDomainPrefPresent) {
         asn1PrtToStrm_TS24008IE_VoiceDomainPref (pctxt, "voiceDomainPref", &pvalue->voiceDomainPref);
      }
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
      if (pvalue->m.oldGUTITypePresent) {
         asn1PrtToStrm_TS24301IE_GUTIType (pctxt, "oldGUTIType", &pvalue->oldGUTIType);
      }
      if (pvalue->m.msNetFeatureSupportPresent) {
         asn1PrtToStrm_TS24008IE_MSNetFeatureSupport (pctxt, "msNetFeatureSupport", &pvalue->msNetFeatureSupport);
      }
   }

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.tmsiBasedNRIContainerPresent) {
         asn1PrtToStrm_TS24008IE_NetResourceIdentContainer (pctxt, "tmsiBasedNRIContainer", &pvalue->tmsiBasedNRIContainer);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.t3324ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3324Value", &pvalue->t3324Value);
      }
      if (pvalue->m.t3412ExtValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3412ExtValue", &pvalue->t3412ExtValue);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extDRXParamsPresent) {
         asn1PrtToStrm_TS24008IE_ExtDRXParams (pctxt, "extDRXParams", &pvalue->extDRXParams);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.addlSecurityCapabilityPresent) {
         asn1PrtToStrm_TS24301IE_UEAddlSecurityCapability (pctxt, "addlSecurityCapability", &pvalue->addlSecurityCapability);
      }
      if (pvalue->m.ueStatusPresent) {
         asn1PrtToStrm_TS24301IE_UEStatus (pctxt, "ueStatus", &pvalue->ueStatus);
      }
      if (pvalue->m.addlInfoReqPresent) {
         asn1PrtToStrm_TS24301IE_AdditionalInfoReq (pctxt, "addlInfoReq", &pvalue->addlInfoReq);
      }
   }

   if (pvalue->m._v16ExtPresent) {
      if (pvalue->m.n1UENetworkCapabilityPresent) {
         asn1PrtToStrm_TS24301IE_N1UENetCapability (pctxt, "n1UENetworkCapability", &pvalue->n1UENetworkCapability);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_AuthFailure (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AuthFailure* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_EMMCause (pctxt, "emmCause", &pvalue->emmCause);

   if (pvalue->m.authFailureParamPresent) {
      asn1PrtToStrm_TS24008IE_AuthFailureParam (pctxt, "authFailureParam", &pvalue->authFailureParam);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_AuthRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AuthRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_NASKeySetIdentifier (pctxt, "nasKeySetIdent", &pvalue->nasKeySetIdent);

   asn1PrtToStrm_TS24008IE_AuthParamRAND (pctxt, "authParamRAND", &pvalue->authParamRAND);

   asn1PrtToStrm_TS24008IE_AuthParamAUTN (pctxt, "authParamAUTN", &pvalue->authParamAUTN);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_CSServiceNotif (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_CSServiceNotif* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_PagingIdentity (pctxt, "pagingIdentity", &pvalue->pagingIdentity);

   if (pvalue->m.cliPresent) {
      asn1PrtToStrm_TS24301IE_CLI (pctxt, "cli", &pvalue->cli);
   }

   if (pvalue->m.ssCodePresent) {
      asn1PrtToStrm_TS24301IE_SSCode (pctxt, "ssCode", &pvalue->ssCode);
   }

   if (pvalue->m.lcsIndicatorPresent) {
      asn1PrtToStrm_TS24301IE_LCSIndicator (pctxt, "lcsIndicator", &pvalue->lcsIndicator);
   }

   if (pvalue->m.lcsClientIdentityPresent) {
      asn1PrtToStrm_TS24301IE_LCSClientIdentity (pctxt, "lcsClientIdentity", &pvalue->lcsClientIdentity);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_DetachRequestUEOrig (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DetachRequestUEOrig* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_NASKeySetIdentifier (pctxt, "nasKeySetIdent", &pvalue->nasKeySetIdent);

   asn1PrtToStrm_TS24301IE_DetachType (pctxt, "detachType", &pvalue->detachType);

   asn1PrtToStrm_TS24301IE_EPSMobileIdentity (pctxt, "gUTIOrIMSI", &pvalue->gUTIOrIMSI);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_DetachRequestUETerm (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DetachRequestUETerm* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_DetachType (pctxt, "detachType", &pvalue->detachType);

   if (pvalue->m.emmCausePresent) {
      asn1PrtToStrm_TS24301IE_EMMCause (pctxt, "emmCause", &pvalue->emmCause);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_DetachRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DetachRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   switch (pvalue->t)
   {
      /* ueOrig */
      case 1:
      {
         asn1PrtToStrm_TS24301Msg_DetachRequestUEOrig (pctxt, "ueOrig", &pvalue->u.ueOrig);
         break;
      }
      /* ueTerm */
      case 2:
      {
         asn1PrtToStrm_TS24301Msg_DetachRequestUETerm (pctxt, "ueTerm", &pvalue->u.ueTerm);
         break;
      }
      default:;
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_EMMInformation (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_EMMInformation* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.fullNameForNetworkPresent) {
      asn1PrtToStrm_TS24008IE_NetworkName (pctxt, "fullNameForNetwork", &pvalue->fullNameForNetwork);
   }

   if (pvalue->m.shortNameForNetworkPresent) {
      asn1PrtToStrm_TS24008IE_NetworkName (pctxt, "shortNameForNetwork", &pvalue->shortNameForNetwork);
   }

   if (pvalue->m.localTimeZonePresent) {
      asn1PrtToStrm_TS24008IE_TimeZone (pctxt, "localTimeZone", &pvalue->localTimeZone);
   }

   if (pvalue->m.univTimeAndLclTimeZonePresent) {
      asn1PrtToStrm_TS24008IE_TimeZoneAndTime (pctxt, "univTimeAndLclTimeZone", &pvalue->univTimeAndLclTimeZone);
   }

   if (pvalue->m.networkDaylightSavingTimePresent) {
      asn1PrtToStrm_TS24008IE_DaylightSavingTime (pctxt, "networkDaylightSavingTime", &pvalue->networkDaylightSavingTime);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ExtServiceReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ExtServiceReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_NASKeySetIdentifier (pctxt, "nasKeySetIdentifier", &pvalue->nasKeySetIdentifier);

   asn1PrtToStrm_TS24301IE_ServiceType (pctxt, "serviceType", &pvalue->serviceType);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "m_tmsi", &pvalue->m_tmsi);

   if (pvalue->m.csfbResponsePresent) {
      asn1PrtToStrm_TS24301IE_CSFBResponse (pctxt, "csfbResponse", &pvalue->csfbResponse);
   }

   if (pvalue->m._v9ExtPresent) {
      if (pvalue->m.epsBearerContextStatusPresent) {
         asn1PrtToStrm_TS24301IE_EPSBearerContextStatus (pctxt, "epsBearerContextStatus", &pvalue->epsBearerContextStatus);
      }
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_GUTIReallocCmd (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_GUTIReallocCmd* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_EPSMobileIdentity (pctxt, "guti", &pvalue->guti);

   if (pvalue->m.taiListPresent) {
      asn1PrtToStrm_TS24301IE_TrackingAreaIdentList (pctxt, "taiList", &pvalue->taiList);
   }

   if (pvalue->m._v14ExtPresent) {
      if (pvalue->m.dcnIdPresent) {
         asn1PrtToStrm_TS24008IE_DcnID (pctxt, "dcnId", &pvalue->dcnId);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_IdentReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_IdentReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_IdentityType2Value (pctxt, "identType", &pvalue->identType);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_SecModeCmd (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_SecModeCmd* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_NASSecurityAlgorithms (pctxt, "selNASSecurityAlgs", &pvalue->selNASSecurityAlgs);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_NASKeySetIdentifier (pctxt, "nasKeySetIdentifier", &pvalue->nasKeySetIdentifier);

   asn1PrtToStrm_TS24301IE_UESecurityCapability (pctxt, "replayedUESecurityCapabilities", &pvalue->replayedUESecurityCapabilities);

   if (pvalue->m.imeisvRequestPresent) {
      asn1PrtToStrm_TS24008IE_IMEISVRequest (pctxt, "imeisvRequest", &pvalue->imeisvRequest);
   }

   if (pvalue->m.replayedNoncePresent) {
      asn1PrtToStrm_TS24301IE_Nonce (pctxt, "replayedNonce", &pvalue->replayedNonce);
   }

   if (pvalue->m.noncePresent) {
      asn1PrtToStrm_TS24301IE_Nonce (pctxt, "nonce", &pvalue->nonce);
   }

   if (pvalue->m._v14ExtPresent) {
      if (pvalue->m.hashMMEPresent) {
         asn1PrtToStrm_TS24301IE_HashMME (pctxt, "hashMME", &pvalue->hashMME);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.addlSecurityCapabilityPresent) {
         asn1PrtToStrm_TS24301IE_UEAddlSecurityCapability (pctxt, "addlSecurityCapability", &pvalue->addlSecurityCapability);
      }
   }

   if (pvalue->m._v16ExtPresent) {
      if (pvalue->m.ueRadioCapabilityIdRequestPresent) {
         asn1PrtToStrm_TS24301IE_UERadioCapIdRequest (pctxt, "ueRadioCapabilityIdRequest", &pvalue->ueRadioCapabilityIdRequest);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_SecModeCmplt (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_SecModeCmplt* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.imeisvPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "imeisv", &pvalue->imeisv);
   }

   if (pvalue->m._v14ExtPresent) {
      if (pvalue->m.replayedNASMsgContainerPresent) {
         asn1PrtToStrm_TS24301IE_ReplayedNASMsgContainer (pctxt, "replayedNASMsgContainer", &pvalue->replayedNASMsgContainer);
      }
   }

   if (pvalue->m._v16ExtPresent) {
      if (pvalue->m.ueradioCapabilityIDPresent) {
         asn1PrtToStrm_TS24301IE_UERadioCapId (pctxt, "ueradioCapabilityID", &pvalue->ueradioCapabilityID);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ServiceRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ServiceRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "secHdr", pvalue->secHdr);

   asn1PrtToStrm_TS24007L3_ProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

   asn1PrtToStrm_TS24301IE_KSIAndSequenceNumber (pctxt, "ksiAndSequenceNumber", &pvalue->ksiAndSequenceNumber);

   asn1PrtToStrm_TS24301IE_ShortMAC (pctxt, "shortMAC", &pvalue->shortMAC);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ServiceReject (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ServiceReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_EMMCause (pctxt, "emmCause", &pvalue->emmCause);

   if (pvalue->m.t3442ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "t3442Value", &pvalue->t3442Value);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3346ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3346Value", &pvalue->t3346Value);
      }
   }

   if (pvalue->m._v14ExtPresent) {
      if (pvalue->m.t3448ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3448Value", &pvalue->t3448Value);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_TrkAreaUpdAccept (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_TrkAreaUpdAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_EPSUpdateResult (pctxt, "epsUpdateResult", &pvalue->epsUpdateResult);

   if (pvalue->m.t3412ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "t3412Value", &pvalue->t3412Value);
   }

   if (pvalue->m.gutiPresent) {
      asn1PrtToStrm_TS24301IE_EPSMobileIdentity (pctxt, "guti", &pvalue->guti);
   }

   if (pvalue->m.taiListPresent) {
      asn1PrtToStrm_TS24301IE_TrackingAreaIdentList (pctxt, "taiList", &pvalue->taiList);
   }

   if (pvalue->m.epsBearerContextStatusPresent) {
      asn1PrtToStrm_TS24301IE_EPSBearerContextStatus (pctxt, "epsBearerContextStatus", &pvalue->epsBearerContextStatus);
   }

   if (pvalue->m.locAreaIdentPresent) {
      asn1PrtToStrm_TS24008IE_LocAreaIdent (pctxt, "locAreaIdent", &pvalue->locAreaIdent);
   }

   if (pvalue->m.msIdentityPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "msIdentity", &pvalue->msIdentity);
   }

   if (pvalue->m.emmCausePresent) {
      asn1PrtToStrm_TS24301IE_EMMCause (pctxt, "emmCause", &pvalue->emmCause);
   }

   if (pvalue->m.t3402ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "t3402Value", &pvalue->t3402Value);
   }

   if (pvalue->m.t3423ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "t3423Value", &pvalue->t3423Value);
   }

   if (pvalue->m.equivalentPLMNsPresent) {
      asn1PrtToStrm_TS24008IE_PLMNList (pctxt, "equivalentPLMNs", &pvalue->equivalentPLMNs);
   }

   if (pvalue->m.emergencyNumberListPresent) {
      asn1PrtToStrm_TS24008IE_EmergencyNumberList (pctxt, "emergencyNumberList", &pvalue->emergencyNumberList);
   }

   if (pvalue->m.epsNetworkFeatureSupportPresent) {
      asn1PrtToStrm_TS24301IE_EPSNetworkFeatureSupport (pctxt, "epsNetworkFeatureSupport", &pvalue->epsNetworkFeatureSupport);
   }

   if (pvalue->m.addnUpdateResultPresent) {
      asn1PrtToStrm_TS24301IE_AddnUpdateResult (pctxt, "addnUpdateResult", &pvalue->addnUpdateResult);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3412ExtValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3412ExtValue", &pvalue->t3412ExtValue);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.t3324ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3324Value", &pvalue->t3324Value);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extDRXParamsPresent) {
         asn1PrtToStrm_TS24008IE_ExtDRXParams (pctxt, "extDRXParams", &pvalue->extDRXParams);
      }
      if (pvalue->m.hdrCompressConfigStatPresent) {
         asn1PrtToStrm_TS24301IE_HdrCompressConfigStat (pctxt, "hdrCompressConfigStat", &pvalue->hdrCompressConfigStat);
      }
      if (pvalue->m.dcnIdPresent) {
         asn1PrtToStrm_TS24008IE_DcnID (pctxt, "dcnId", &pvalue->dcnId);
      }
      if (pvalue->m.smsServicesStatusPresent) {
         asn1PrtToStrm_TS24301IE_SMSServicesStatus (pctxt, "smsServicesStatus", &pvalue->smsServicesStatus);
      }
   }

   if (pvalue->m._v14ExtPresent) {
      if (pvalue->m.non3GPPNetPoliciesPresent) {
         asn1PrtToStrm_TS24008IE_Non3GPPNetPolicies (pctxt, "non3GPPNetPolicies", &pvalue->non3GPPNetPolicies);
      }
      if (pvalue->m.t3448ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3448Value", &pvalue->t3448Value);
      }
      if (pvalue->m.networkPolicyPresent) {
         asn1PrtToStrm_TS24301IE_NetworkPolicy (pctxt, "networkPolicy", &pvalue->networkPolicy);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.t3447ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3447Value", &pvalue->t3447Value);
      }
      if (pvalue->m.extEmergencyNumberListPresent) {
         asn1PrtToStrm_TS24301IE_ExtEmergencyNumberList (pctxt, "extEmergencyNumberList", &pvalue->extEmergencyNumberList);
      }
      if (pvalue->m.cipherKeyDataPresent) {
         asn1PrtToStrm_TS24301IE_CipherKeyData (pctxt, "cipherKeyData", &pvalue->cipherKeyData);
      }
   }

   if (pvalue->m._v16ExtPresent) {
      if (pvalue->m.ueRadioCapabilityIdPresent) {
         asn1PrtToStrm_TS24301IE_UERadioCapId (pctxt, "ueRadioCapabilityId", &pvalue->ueRadioCapabilityId);
      }
      if (pvalue->m.ueRadioCapIdDeleteIndPresent) {
         asn1PrtToStrm_TS24301IE_UERadioCapIdDeletionInd (pctxt, "ueRadioCapIdDeleteInd", &pvalue->ueRadioCapIdDeleteInd);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_TrkAreaUpdReject (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_TrkAreaUpdReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_EMMCause (pctxt, "cause", &pvalue->cause);

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3346ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3346Value", &pvalue->t3346Value);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.extEMMCausePresent) {
         asn1PrtToStrm_TS24301IE_ExtEMMCause (pctxt, "extEMMCause", &pvalue->extEMMCause);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_TrkAreaUpdRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_TrkAreaUpdRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_NASKeySetIdentifier (pctxt, "nasKeySetIdentifier", &pvalue->nasKeySetIdentifier);

   asn1PrtToStrm_TS24301IE_EPSUpdateType (pctxt, "epsUpdateType", &pvalue->epsUpdateType);

   asn1PrtToStrm_TS24301IE_EPSMobileIdentity (pctxt, "oldGUTI", &pvalue->oldGUTI);

   if (pvalue->m.nonCurrNativeNASKeySetIdentPresent) {
      asn1PrtToStrm_TS24301IE_NASKeySetIdentifier (pctxt, "nonCurrNativeNASKeySetIdent", &pvalue->nonCurrNativeNASKeySetIdent);
   }

   if (pvalue->m.gprsCiphKeySeqNumPresent) {
      asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "gprsCiphKeySeqNum", &pvalue->gprsCiphKeySeqNum);
   }

   if (pvalue->m.oldP_TMSISignaturePresent) {
      asn1PrtToStrm_TS24008IE_P_TMSISignature (pctxt, "oldP_TMSISignature", &pvalue->oldP_TMSISignature);
   }

   if (pvalue->m.additionalGUTIPresent) {
      asn1PrtToStrm_TS24301IE_EPSMobileIdentity (pctxt, "additionalGUTI", &pvalue->additionalGUTI);
   }

   if (pvalue->m.noncePresent) {
      asn1PrtToStrm_TS24301IE_Nonce (pctxt, "nonce", &pvalue->nonce);
   }

   if (pvalue->m.ueNetworkCapabilityPresent) {
      asn1PrtToStrm_TS24301IE_UENetworkCapability (pctxt, "ueNetworkCapability", &pvalue->ueNetworkCapability);
   }

   if (pvalue->m.lastVisitedRegisteredTAIPresent) {
      asn1PrtToStrm_TS24301IE_TrackingAreaIdent (pctxt, "lastVisitedRegisteredTAI", &pvalue->lastVisitedRegisteredTAI);
   }

   if (pvalue->m.drxParameterPresent) {
      asn1PrtToStrm_TS24008IE_DRXParameter (pctxt, "drxParameter", &pvalue->drxParameter);
   }

   if (pvalue->m.ueRadioCapInfoUpdateNeededPresent) {
      asn1PrtToStrm_TS24301IE_UERadioCapInfoUpdateNeeded (pctxt, "ueRadioCapInfoUpdateNeeded", &pvalue->ueRadioCapInfoUpdateNeeded);
   }

   if (pvalue->m.epsBearerContextStatusPresent) {
      asn1PrtToStrm_TS24301IE_EPSBearerContextStatus (pctxt, "epsBearerContextStatus", &pvalue->epsBearerContextStatus);
   }

   if (pvalue->m.msNetworkCapabilityPresent) {
      asn1PrtToStrm_TS24008IE_MSNetworkCapability (pctxt, "msNetworkCapability", &pvalue->msNetworkCapability);
   }

   if (pvalue->m.oldLocAreaIdentPresent) {
      asn1PrtToStrm_TS24008IE_LocAreaIdent (pctxt, "oldLocAreaIdent", &pvalue->oldLocAreaIdent);
   }

   if (pvalue->m.tmsiStatusPresent) {
      asn1PrtToStrm_TS24008IE_TMSIStatus (pctxt, "tmsiStatus", &pvalue->tmsiStatus);
   }

   if (pvalue->m.mobileStationClassmark2Present) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark2 (pctxt, "mobileStationClassmark2", &pvalue->mobileStationClassmark2);
   }

   if (pvalue->m.mobileStationClassmark3Present) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark3 (pctxt, "mobileStationClassmark3", &pvalue->mobileStationClassmark3);
   }

   if (pvalue->m.supportedCodecsPresent) {
      asn1PrtToStrm_TS24008IE_SupportedCodecList (pctxt, "supportedCodecs", &pvalue->supportedCodecs);
   }

   if (pvalue->m.addnUpdateTypePresent) {
      asn1PrtToStrm_TS24301IE_AddnUpdateType (pctxt, "addnUpdateType", &pvalue->addnUpdateType);
   }

   if (pvalue->m._v9ExtPresent) {
      if (pvalue->m.voiceDomainPrefPresent) {
         asn1PrtToStrm_TS24008IE_VoiceDomainPref (pctxt, "voiceDomainPref", &pvalue->voiceDomainPref);
      }
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.oldGUTITypePresent) {
         asn1PrtToStrm_TS24301IE_GUTIType (pctxt, "oldGUTIType", &pvalue->oldGUTIType);
      }
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
      if (pvalue->m.msNetFeatureSupportPresent) {
         asn1PrtToStrm_TS24008IE_MSNetFeatureSupport (pctxt, "msNetFeatureSupport", &pvalue->msNetFeatureSupport);
      }
   }

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.tmsiBasedNRIContainerPresent) {
         asn1PrtToStrm_TS24008IE_NetResourceIdentContainer (pctxt, "tmsiBasedNRIContainer", &pvalue->tmsiBasedNRIContainer);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.t3324ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3324Value", &pvalue->t3324Value);
      }
      if (pvalue->m.t3412ExtValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3412ExtValue", &pvalue->t3412ExtValue);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extDRXParamsPresent) {
         asn1PrtToStrm_TS24008IE_ExtDRXParams (pctxt, "extDRXParams", &pvalue->extDRXParams);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.addlSecurityCapabilityPresent) {
         asn1PrtToStrm_TS24301IE_UEAddlSecurityCapability (pctxt, "addlSecurityCapability", &pvalue->addlSecurityCapability);
      }
      if (pvalue->m.ueStatusPresent) {
         asn1PrtToStrm_TS24301IE_UEStatus (pctxt, "ueStatus", &pvalue->ueStatus);
      }
      if (pvalue->m.addlInfoReqPresent) {
         asn1PrtToStrm_TS24301IE_AdditionalInfoReq (pctxt, "addlInfoReq", &pvalue->addlInfoReq);
      }
   }

   if (pvalue->m._v16ExtPresent) {
      if (pvalue->m.n1UENetworkCapabilityPresent) {
         asn1PrtToStrm_TS24301IE_N1UENetCapability (pctxt, "n1UENetworkCapability", &pvalue->n1UENetworkCapability);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDedEPSBearerCtxtAcc* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDedEPSBearerCtxtRej* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v14ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDedEPSBearerCtxtReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_LinkedEPSBearerIdent (pctxt, "linkedEPSBearerIdent", &pvalue->linkedEPSBearerIdent);

   asn1PrtToStrm_TS24301IE_EPSQualityOfService (pctxt, "epsQoS", &pvalue->epsQoS);

   asn1PrtToStrm_TS24008IE_TFT (pctxt, "tft", &pvalue->tft);

   if (pvalue->m.transIdentPresent) {
      asn1PrtToStrm_TS24008IE_LinkedTI (pctxt, "transIdent", &pvalue->transIdent);
   }

   if (pvalue->m.negotiatedQoSPresent) {
      asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "negotiatedQoS", &pvalue->negotiatedQoS);
   }

   if (pvalue->m.negotiatedLLCSAPIPresent) {
      asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "negotiatedLLCSAPI", &pvalue->negotiatedLLCSAPI);
   }

   if (pvalue->m.radioPriorityPresent) {
      asn1PrtToStrm_TS24008IE_RadioPriorityValue (pctxt, "radioPriority", &pvalue->radioPriority);
   }

   if (pvalue->m.packetFlowIdentifierPresent) {
      asn1PrtToStrm_TS24008IE_PacketFlowIdentValue (pctxt, "packetFlowIdentifier", &pvalue->packetFlowIdentifier);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.wlanOffloadIndPresent) {
         asn1PrtToStrm_TS24008IE_WLANOffloadAccept (pctxt, "wlanOffloadInd", &pvalue->wlanOffloadInd);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.extQOSPresent) {
         asn1PrtToStrm_TS24008IE_ExtQualityOfService (pctxt, "extQOS", &pvalue->extQOS);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDfltEPSBearerCtxtAcc* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDfltEPSBearerCtxtRej* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDfltEPSBearerCtxtReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_EPSQualityOfService (pctxt, "epsQoS", &pvalue->epsQoS);

   asn1PrtToStrm_TS24008IE_AccessPointName (pctxt, "accessPointName", pvalue->accessPointName);

   asn1PrtToStrm_TS24301IE_PDNAddress (pctxt, "pdnAddress", &pvalue->pdnAddress);

   if (pvalue->m.transIdentPresent) {
      asn1PrtToStrm_TS24008IE_LinkedTI (pctxt, "transIdent", &pvalue->transIdent);
   }

   if (pvalue->m.negotiatedQoSPresent) {
      asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "negotiatedQoS", &pvalue->negotiatedQoS);
   }

   if (pvalue->m.negotiatedLLCSAPIPresent) {
      asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "negotiatedLLCSAPI", &pvalue->negotiatedLLCSAPI);
   }

   if (pvalue->m.radioPriorityPresent) {
      asn1PrtToStrm_TS24008IE_RadioPriorityValue (pctxt, "radioPriority", &pvalue->radioPriority);
   }

   if (pvalue->m.packetFlowIdentifierPresent) {
      asn1PrtToStrm_TS24008IE_PacketFlowIdentValue (pctxt, "packetFlowIdentifier", &pvalue->packetFlowIdentifier);
   }

   if (pvalue->m.apn_AMBRPresent) {
      asn1PrtToStrm_TS24301IE_APNAggMaxBitRate (pctxt, "apn_AMBR", &pvalue->apn_AMBR);
   }

   if (pvalue->m.esmCausePresent) {
      asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.connectivityTypePresent) {
         asn1PrtToStrm_TS24008IE_ConnectivityType (pctxt, "connectivityType", &pvalue->connectivityType);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.wlanOffloadIndPresent) {
         asn1PrtToStrm_TS24008IE_WLANOffloadAccept (pctxt, "wlanOffloadInd", &pvalue->wlanOffloadInd);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.hdrCompressConfigStatPresent) {
         asn1PrtToStrm_TS24301IE_HdrCompressConfigStat (pctxt, "hdrCompressConfigStat", &pvalue->hdrCompressConfigStat);
      }
      if (pvalue->m.ctrlPlaneOnlyIndPresent) {
         asn1PrtToStrm_TS24301IE_CtrlPlaneOnlyInd (pctxt, "ctrlPlaneOnlyInd", &pvalue->ctrlPlaneOnlyInd);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
      if (pvalue->m.servPLMNRateCtrlPresent) {
         asn1PrtToStrm_TS24301IE_ServPLMNRateCtrl (pctxt, "servPLMNRateCtrl", &pvalue->servPLMNRateCtrl);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.extAPNAggMaxBitRatePresent) {
         asn1PrtToStrm_TS24301IE_ExtAPNAggMaxBitRate (pctxt, "extAPNAggMaxBitRate", &pvalue->extAPNAggMaxBitRate);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_BearerResAllocRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_BearerResAllocRej* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3396ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3396Value", &pvalue->t3396Value);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.reattemptIndPresent) {
         asn1PrtToStrm_TS24008IE_ReattemptInd (pctxt, "reattemptInd", &pvalue->reattemptInd);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_BearerResAllocReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_BearerResAllocReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_LinkedEPSBearerIdent (pctxt, "linkedEPSBearerIdent", &pvalue->linkedEPSBearerIdent);

   asn1PrtToStrm_TS24008IE_TFT (pctxt, "trafficFlowAgg", &pvalue->trafficFlowAgg);

   asn1PrtToStrm_TS24301IE_EPSQualityOfService (pctxt, "epsQoS", &pvalue->epsQoS);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.extQOSPresent) {
         asn1PrtToStrm_TS24008IE_ExtQualityOfService (pctxt, "extQOS", &pvalue->extQOS);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_BearerResModRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_BearerResModRej* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3396ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3396Value", &pvalue->t3396Value);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.reattemptIndPresent) {
         asn1PrtToStrm_TS24008IE_ReattemptInd (pctxt, "reattemptInd", &pvalue->reattemptInd);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_BearerResModReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_BearerResModReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_LinkedEPSBearerIdent (pctxt, "linkedEPSBearerIdent", &pvalue->linkedEPSBearerIdent);

   asn1PrtToStrm_TS24008IE_TFT (pctxt, "trafficFlowAgg", &pvalue->trafficFlowAgg);

   if (pvalue->m.reqTrafficFlowQoSPresent) {
      asn1PrtToStrm_TS24301IE_EPSQualityOfService (pctxt, "reqTrafficFlowQoS", &pvalue->reqTrafficFlowQoS);
   }

   if (pvalue->m.esmCausePresent) {
      asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.hdrCompressConfigStatPresent) {
         asn1PrtToStrm_TS24301IE_HdrCompressConfigStat (pctxt, "hdrCompressConfigStat", &pvalue->hdrCompressConfigStat);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.extQOSPresent) {
         asn1PrtToStrm_TS24008IE_ExtQualityOfService (pctxt, "extQOS", &pvalue->extQOS);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_DeactEPSBearerCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DeactEPSBearerCtxtAcc* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_DeactEPSBearerCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DeactEPSBearerCtxtReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.t3396ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3396Value", &pvalue->t3396Value);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.wlanOffloadIndPresent) {
         asn1PrtToStrm_TS24008IE_WLANOffloadAccept (pctxt, "wlanOffloadInd", &pvalue->wlanOffloadInd);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ESMInfoResp (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ESMInfoResp* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.accessPointNamePresent) {
      asn1PrtToStrm_TS24008IE_AccessPointName (pctxt, "accessPointName", pvalue->accessPointName);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ModEPSBearerCtxtAcc* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ModEPSBearerCtxtRej* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ModEPSBearerCtxtReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.newEPSQoSPresent) {
      asn1PrtToStrm_TS24301IE_EPSQualityOfService (pctxt, "newEPSQoS", &pvalue->newEPSQoS);
   }

   if (pvalue->m.tftPresent) {
      asn1PrtToStrm_TS24008IE_TFT (pctxt, "tft", &pvalue->tft);
   }

   if (pvalue->m.newQoSPresent) {
      asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "newQoS", &pvalue->newQoS);
   }

   if (pvalue->m.negotiatedLLCSAPIPresent) {
      asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "negotiatedLLCSAPI", &pvalue->negotiatedLLCSAPI);
   }

   if (pvalue->m.radioPriorityPresent) {
      asn1PrtToStrm_TS24008IE_RadioPriorityValue (pctxt, "radioPriority", &pvalue->radioPriority);
   }

   if (pvalue->m.packetFlowIdentifierPresent) {
      asn1PrtToStrm_TS24008IE_PacketFlowIdentValue (pctxt, "packetFlowIdentifier", &pvalue->packetFlowIdentifier);
   }

   if (pvalue->m.apn_AMBRPresent) {
      asn1PrtToStrm_TS24301IE_APNAggMaxBitRate (pctxt, "apn_AMBR", &pvalue->apn_AMBR);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.wlanOffloadIndPresent) {
         asn1PrtToStrm_TS24008IE_WLANOffloadAccept (pctxt, "wlanOffloadInd", &pvalue->wlanOffloadInd);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.hdrCompressConfigStatPresent) {
         asn1PrtToStrm_TS24301IE_HdrCompressConfigStat (pctxt, "hdrCompressConfigStat", &pvalue->hdrCompressConfigStat);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   if (pvalue->m._v15ExtPresent) {
      if (pvalue->m.extAPNAggMaxBitRatePresent) {
         asn1PrtToStrm_TS24301IE_ExtAPNAggMaxBitRate (pctxt, "extAPNAggMaxBitRate", &pvalue->extAPNAggMaxBitRate);
      }
      if (pvalue->m.extQOSPresent) {
         asn1PrtToStrm_TS24008IE_ExtQualityOfService (pctxt, "extQOS", &pvalue->extQOS);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_PDNConnectRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDNConnectRej* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3396ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3396Value", &pvalue->t3396Value);
      }
   }

   if (pvalue->m._v12ExtPresent) {
      if (pvalue->m.reattemptIndPresent) {
         asn1PrtToStrm_TS24008IE_ReattemptInd (pctxt, "reattemptInd", &pvalue->reattemptInd);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_PDNConnectReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDNConnectReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_PDNType (pctxt, "pdnType", &pvalue->pdnType);

   asn1PrtToStrm_TS24008IE_RequestTypeValue (pctxt, "requestType", &pvalue->requestType);

   if (pvalue->m.esmInfoXferFlagPresent) {
      asn1PrtToStrm_TS24301IE_ESMInfoXferFlag (pctxt, "esmInfoXferFlag", &pvalue->esmInfoXferFlag);
   }

   if (pvalue->m.accessPointNamePresent) {
      asn1PrtToStrm_TS24008IE_AccessPointName (pctxt, "accessPointName", pvalue->accessPointName);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.nbifomContainerPresent) {
         asn1PrtToStrm_TS24008IE_NBIFOMContainer (pctxt, "nbifomContainer", &pvalue->nbifomContainer);
      }
      if (pvalue->m.hdrCompressConfigPresent) {
         asn1PrtToStrm_TS24301IE_HdrCompressConfig (pctxt, "hdrCompressConfig", &pvalue->hdrCompressConfig);
      }
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_PDNDisconnRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDNDisconnRej* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_ESMCause (pctxt, "esmCause", &pvalue->esmCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_PDNDisconnReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDNDisconnReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24301IE_LinkedEPSBearerIdent (pctxt, "linkedEPSBearerIdent", &pvalue->linkedEPSBearerIdent);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v13ExtPresent) {
      if (pvalue->m.extProtoConfigOptsPresent) {
         asn1PrtToStrm_TS24008IE_ExtProtoConfigOptions (pctxt, "extProtoConfigOpts", &pvalue->extProtoConfigOpts);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_CtrlPlaneSvcReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_CtrlPlaneSvcReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24301IE_CtrlPlaneSvcType (pctxt, "ctrlPlaneSvcType", &pvalue->ctrlPlaneSvcType);

   asn1PrtToStrm_TS24301IE_NASKeySetIdentifier (pctxt, "nasKeySetId", &pvalue->nasKeySetId);

   if (pvalue->m.esmMsgContPresent) {
      asn1PrtToStrm_TS24301IE_ESMMessageContainer (pctxt, "esmMsgCont", &pvalue->esmMsgCont);
   }

   if (pvalue->m.nasMsgContPresent) {
      asn1PrtToStrm_TS24301IE_NASMessageContainer (pctxt, "nasMsgCont", &pvalue->nasMsgCont);
   }

   if (pvalue->m.epsBearerContextStatusPresent) {
      asn1PrtToStrm_TS24301IE_EPSBearerContextStatus (pctxt, "epsBearerContextStatus", &pvalue->epsBearerContextStatus);
   }

   if (pvalue->m.devicePropertiesPresent) {
      asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ESMDataTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ESMDataTransport* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamHexStr (pctxt, "userDataContainer", pvalue->userDataContainer.numocts, pvalue->userDataContainer.data);

   if (pvalue->m.releaseAssistIndPresent) {
      asn1PrtToStrm_TS24301IE_ReleaseAssistInd (pctxt, "releaseAssistInd", &pvalue->releaseAssistInd);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_ServiceAccept (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ServiceAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.epsBearerContextStatusPresent) {
      asn1PrtToStrm_TS24301IE_EPSBearerContextStatus (pctxt, "epsBearerContextStatus", &pvalue->epsBearerContextStatus);
   }

   if (pvalue->m.t3448ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3448Value", &pvalue->t3448Value);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_PDU (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDU* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.secHdrPresent) {
      asn1PrtToStrm_TS24007L3_SecProtMsgHeader (pctxt, "secHdr", &pvalue->secHdr);
   }

   asn1PrtToStrm_TS24007L3_L3HdrOptions (pctxt, "l3HdrOpts", &pvalue->l3HdrOpts);

   asn1PrtToStrm_TS24007L3_ProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

   rtPrintToStreamOpenBrace (pctxt, "pti");

   switch (pvalue->protoDiscr)
   {
      /* value */
      case 2:
      {
         rtPrintToStreamIndent (pctxt);
         rtPrintToStreamUnsigned (pctxt, "value", pvalue->pti.u.value);
         break;
      }
      /* noValue */
      default:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "noValue");
         break;
      }
   }

   rtPrintToStreamCloseBrace (pctxt);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "msgType", pvalue->msgType);

   rtPrintToStreamOpenBrace (pctxt, "data");

   switch (pvalue->data.t)
   {
      /* obj_AttachAccept */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AttachAccept:
      {
         asn1PrtToStrm_TS24301Msg_AttachAccept (pctxt, "obj_AttachAccept", pvalue->data.u.obj_AttachAccept);
         break;
      }
      /* obj_AttachComplete */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AttachComplete:
      {
         asn1PrtToStrm_TS24301Msg_AttachComplete (pctxt, "obj_AttachComplete", pvalue->data.u.obj_AttachComplete);
         break;
      }
      /* obj_AttachReject */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AttachReject:
      {
         asn1PrtToStrm_TS24301Msg_AttachReject (pctxt, "obj_AttachReject", pvalue->data.u.obj_AttachReject);
         break;
      }
      /* obj_AttachRequest */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AttachRequest:
      {
         asn1PrtToStrm_TS24301Msg_AttachRequest (pctxt, "obj_AttachRequest", pvalue->data.u.obj_AttachRequest);
         break;
      }
      /* obj_AuthFailure */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AuthFailure:
      {
         asn1PrtToStrm_TS24301Msg_AuthFailure (pctxt, "obj_AuthFailure", pvalue->data.u.obj_AuthFailure);
         break;
      }
      /* obj_AuthReject */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AuthReject:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_AuthReject");
         break;
      }
      /* obj_AuthRequest */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AuthRequest:
      {
         asn1PrtToStrm_TS24301Msg_AuthRequest (pctxt, "obj_AuthRequest", pvalue->data.u.obj_AuthRequest);
         break;
      }
      /* obj_AuthResponse */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AuthResponse:
      {
         asn1PrtToStrm_TS24301Msg_AuthResponse (pctxt, "obj_AuthResponse", pvalue->data.u.obj_AuthResponse);
         break;
      }
      /* obj_CSServiceNotif */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_CSServiceNotif:
      {
         asn1PrtToStrm_TS24301Msg_CSServiceNotif (pctxt, "obj_CSServiceNotif", pvalue->data.u.obj_CSServiceNotif);
         break;
      }
      /* obj_DetachAccept */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DetachAccept:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_DetachAccept");
         break;
      }
      /* obj_DetachRequest */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DetachRequest:
      {
         asn1PrtToStrm_TS24301Msg_DetachRequest (pctxt, "obj_DetachRequest", pvalue->data.u.obj_DetachRequest);
         break;
      }
      /* obj_DLNASTransport */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DLNASTransport:
      {
         asn1PrtToStrm_TS24301Msg_DLNASTransport (pctxt, "obj_DLNASTransport", pvalue->data.u.obj_DLNASTransport);
         break;
      }
      /* obj_EMMInformation */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_EMMInformation:
      {
         asn1PrtToStrm_TS24301Msg_EMMInformation (pctxt, "obj_EMMInformation", pvalue->data.u.obj_EMMInformation);
         break;
      }
      /* obj_EMMStatus */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_EMMStatus:
      {
         asn1PrtToStrm_TS24301Msg_EMMStatus (pctxt, "obj_EMMStatus", &pvalue->data.u.obj_EMMStatus);
         break;
      }
      /* obj_ExtServiceReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ExtServiceReq:
      {
         asn1PrtToStrm_TS24301Msg_ExtServiceReq (pctxt, "obj_ExtServiceReq", pvalue->data.u.obj_ExtServiceReq);
         break;
      }
      /* obj_GUTIReallocCmd */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_GUTIReallocCmd:
      {
         asn1PrtToStrm_TS24301Msg_GUTIReallocCmd (pctxt, "obj_GUTIReallocCmd", pvalue->data.u.obj_GUTIReallocCmd);
         break;
      }
      /* obj_GUTIReallocCmplt */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_GUTIReallocCmplt:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_GUTIReallocCmplt");
         break;
      }
      /* obj_IdentReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_IdentReq:
      {
         asn1PrtToStrm_TS24301Msg_IdentReq (pctxt, "obj_IdentReq", pvalue->data.u.obj_IdentReq);
         break;
      }
      /* obj_IdentResp */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_IdentResp:
      {
         asn1PrtToStrm_TS24301Msg_IdentResp (pctxt, "obj_IdentResp", pvalue->data.u.obj_IdentResp);
         break;
      }
      /* obj_SecModeCmd */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_SecModeCmd:
      {
         asn1PrtToStrm_TS24301Msg_SecModeCmd (pctxt, "obj_SecModeCmd", pvalue->data.u.obj_SecModeCmd);
         break;
      }
      /* obj_SecModeCmplt */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_SecModeCmplt:
      {
         asn1PrtToStrm_TS24301Msg_SecModeCmplt (pctxt, "obj_SecModeCmplt", pvalue->data.u.obj_SecModeCmplt);
         break;
      }
      /* obj_SecModeReject */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_SecModeReject:
      {
         asn1PrtToStrm_TS24301Msg_SecModeReject (pctxt, "obj_SecModeReject", &pvalue->data.u.obj_SecModeReject);
         break;
      }
      /* obj_ServiceRequest */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ServiceRequest:
      {
         asn1PrtToStrm_TS24301Msg_ServiceRequest (pctxt, "obj_ServiceRequest", pvalue->data.u.obj_ServiceRequest);
         break;
      }
      /* obj_ServiceReject */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ServiceReject:
      {
         asn1PrtToStrm_TS24301Msg_ServiceReject (pctxt, "obj_ServiceReject", pvalue->data.u.obj_ServiceReject);
         break;
      }
      /* obj_TrkAreaUpdAccept */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_TrkAreaUpdAccept:
      {
         asn1PrtToStrm_TS24301Msg_TrkAreaUpdAccept (pctxt, "obj_TrkAreaUpdAccept", pvalue->data.u.obj_TrkAreaUpdAccept);
         break;
      }
      /* obj_TrkAreaUpdCmplt */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_TrkAreaUpdCmplt:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_TrkAreaUpdCmplt");
         break;
      }
      /* obj_TrkAreaUpdReject */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_TrkAreaUpdReject:
      {
         asn1PrtToStrm_TS24301Msg_TrkAreaUpdReject (pctxt, "obj_TrkAreaUpdReject", pvalue->data.u.obj_TrkAreaUpdReject);
         break;
      }
      /* obj_TrkAreaUpdRequest */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_TrkAreaUpdRequest:
      {
         asn1PrtToStrm_TS24301Msg_TrkAreaUpdRequest (pctxt, "obj_TrkAreaUpdRequest", pvalue->data.u.obj_TrkAreaUpdRequest);
         break;
      }
      /* obj_ULNASTransport */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ULNASTransport:
      {
         asn1PrtToStrm_TS24301Msg_ULNASTransport (pctxt, "obj_ULNASTransport", pvalue->data.u.obj_ULNASTransport);
         break;
      }
      /* obj_ULGenNASTransport */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ULGenNASTransport:
      {
         asn1PrtToStrm_TS24301Msg_ULGenNASTransport (pctxt, "obj_ULGenNASTransport", pvalue->data.u.obj_ULGenNASTransport);
         break;
      }
      /* obj_DLGenNASTransport */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DLGenNASTransport:
      {
         asn1PrtToStrm_TS24301Msg_DLGenNASTransport (pctxt, "obj_DLGenNASTransport", pvalue->data.u.obj_DLGenNASTransport);
         break;
      }
      /* obj_ActvDedEPSBearerCtxtAcc */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDedEPSBearerCtxtAcc:
      {
         asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtAcc (pctxt, "obj_ActvDedEPSBearerCtxtAcc", pvalue->data.u.obj_ActvDedEPSBearerCtxtAcc);
         break;
      }
      /* obj_ActvDedEPSBearerCtxtRej */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDedEPSBearerCtxtRej:
      {
         asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtRej (pctxt, "obj_ActvDedEPSBearerCtxtRej", pvalue->data.u.obj_ActvDedEPSBearerCtxtRej);
         break;
      }
      /* obj_ActvDedEPSBearerCtxtReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDedEPSBearerCtxtReq:
      {
         asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtReq (pctxt, "obj_ActvDedEPSBearerCtxtReq", pvalue->data.u.obj_ActvDedEPSBearerCtxtReq);
         break;
      }
      /* obj_ActvDfltEPSBearerCtxtAcc */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDfltEPSBearerCtxtAcc:
      {
         asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtAcc (pctxt, "obj_ActvDfltEPSBearerCtxtAcc", pvalue->data.u.obj_ActvDfltEPSBearerCtxtAcc);
         break;
      }
      /* obj_ActvDfltEPSBearerCtxtRej */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDfltEPSBearerCtxtRej:
      {
         asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtRej (pctxt, "obj_ActvDfltEPSBearerCtxtRej", pvalue->data.u.obj_ActvDfltEPSBearerCtxtRej);
         break;
      }
      /* obj_ActvDfltEPSBearerCtxtReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDfltEPSBearerCtxtReq:
      {
         asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtReq (pctxt, "obj_ActvDfltEPSBearerCtxtReq", pvalue->data.u.obj_ActvDfltEPSBearerCtxtReq);
         break;
      }
      /* obj_BearerResAllocRej */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_BearerResAllocRej:
      {
         asn1PrtToStrm_TS24301Msg_BearerResAllocRej (pctxt, "obj_BearerResAllocRej", pvalue->data.u.obj_BearerResAllocRej);
         break;
      }
      /* obj_BearerResAllocReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_BearerResAllocReq:
      {
         asn1PrtToStrm_TS24301Msg_BearerResAllocReq (pctxt, "obj_BearerResAllocReq", pvalue->data.u.obj_BearerResAllocReq);
         break;
      }
      /* obj_BearerResModRej */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_BearerResModRej:
      {
         asn1PrtToStrm_TS24301Msg_BearerResModRej (pctxt, "obj_BearerResModRej", pvalue->data.u.obj_BearerResModRej);
         break;
      }
      /* obj_BearerResModReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_BearerResModReq:
      {
         asn1PrtToStrm_TS24301Msg_BearerResModReq (pctxt, "obj_BearerResModReq", pvalue->data.u.obj_BearerResModReq);
         break;
      }
      /* obj_DeactEPSBearerCtxtAcc */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DeactEPSBearerCtxtAcc:
      {
         asn1PrtToStrm_TS24301Msg_DeactEPSBearerCtxtAcc (pctxt, "obj_DeactEPSBearerCtxtAcc", pvalue->data.u.obj_DeactEPSBearerCtxtAcc);
         break;
      }
      /* obj_DeactEPSBearerCtxtReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DeactEPSBearerCtxtReq:
      {
         asn1PrtToStrm_TS24301Msg_DeactEPSBearerCtxtReq (pctxt, "obj_DeactEPSBearerCtxtReq", pvalue->data.u.obj_DeactEPSBearerCtxtReq);
         break;
      }
      /* obj_ESMInfoReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ESMInfoReq:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_ESMInfoReq");
         break;
      }
      /* obj_ESMInfoResp */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ESMInfoResp:
      {
         asn1PrtToStrm_TS24301Msg_ESMInfoResp (pctxt, "obj_ESMInfoResp", pvalue->data.u.obj_ESMInfoResp);
         break;
      }
      /* obj_ESMStatus */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ESMStatus:
      {
         asn1PrtToStrm_TS24301Msg_ESMStatus (pctxt, "obj_ESMStatus", &pvalue->data.u.obj_ESMStatus);
         break;
      }
      /* obj_ModEPSBearerCtxtAcc */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ModEPSBearerCtxtAcc:
      {
         asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtAcc (pctxt, "obj_ModEPSBearerCtxtAcc", pvalue->data.u.obj_ModEPSBearerCtxtAcc);
         break;
      }
      /* obj_ModEPSBearerCtxtRej */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ModEPSBearerCtxtRej:
      {
         asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtRej (pctxt, "obj_ModEPSBearerCtxtRej", pvalue->data.u.obj_ModEPSBearerCtxtRej);
         break;
      }
      /* obj_ModEPSBearerCtxtReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ModEPSBearerCtxtReq:
      {
         asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtReq (pctxt, "obj_ModEPSBearerCtxtReq", pvalue->data.u.obj_ModEPSBearerCtxtReq);
         break;
      }
      /* obj_PDNConnectRej */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_PDNConnectRej:
      {
         asn1PrtToStrm_TS24301Msg_PDNConnectRej (pctxt, "obj_PDNConnectRej", pvalue->data.u.obj_PDNConnectRej);
         break;
      }
      /* obj_PDNConnectReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_PDNConnectReq:
      {
         asn1PrtToStrm_TS24301Msg_PDNConnectReq (pctxt, "obj_PDNConnectReq", pvalue->data.u.obj_PDNConnectReq);
         break;
      }
      /* obj_PDNDisconnRej */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_PDNDisconnRej:
      {
         asn1PrtToStrm_TS24301Msg_PDNDisconnRej (pctxt, "obj_PDNDisconnRej", pvalue->data.u.obj_PDNDisconnRej);
         break;
      }
      /* obj_PDNDisconnReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_PDNDisconnReq:
      {
         asn1PrtToStrm_TS24301Msg_PDNDisconnReq (pctxt, "obj_PDNDisconnReq", pvalue->data.u.obj_PDNDisconnReq);
         break;
      }
      /* obj_CtrlPlaneSvcReq */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_CtrlPlaneSvcReq:
      {
         asn1PrtToStrm_TS24301Msg_CtrlPlaneSvcReq (pctxt, "obj_CtrlPlaneSvcReq", pvalue->data.u.obj_CtrlPlaneSvcReq);
         break;
      }
      /* obj_ESMDataTransport */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ESMDataTransport:
      {
         asn1PrtToStrm_TS24301Msg_ESMDataTransport (pctxt, "obj_ESMDataTransport", pvalue->data.u.obj_ESMDataTransport);
         break;
      }
      /* obj_ServiceAccept */
      case T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ServiceAccept:
      {
         asn1PrtToStrm_TS24301Msg_ServiceAccept (pctxt, "obj_ServiceAccept", pvalue->data.u.obj_ServiceAccept);
         break;
      }
      default:;
   }

   rtPrintToStreamCloseBrace (pctxt);

   rtPrintToStreamIndent (pctxt);
   rtxPrintToStreamNull (pctxt, "eom");

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_Notification (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_Notification* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "length", pvalue->length);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "value", pvalue->value);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24301Msg_RemoteUEReport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_RemoteUEReport* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.remoteUECtxtConnPresent) {
      asn1PrtToStrm_TS24301IE_RemoteUECtxtList (pctxt, "remoteUECtxtConn", &pvalue->remoteUECtxtConn);
   }

   if (pvalue->m.remoteUECtxtDisconnPresent) {
      asn1PrtToStrm_TS24301IE_RemoteUECtxtList (pctxt, "remoteUECtxtDisconn", &pvalue->remoteUECtxtDisconn);
   }

   if (pvalue->m.proSeKeyMgmtFuncPresent) {
      asn1PrtToStrm_TS24301IE_PKMFAddress (pctxt, "proSeKeyMgmtFunc", &pvalue->proSeKeyMgmtFunc);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

