/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.A, Date: 24-Oct-2012.
 */
#include "AllTypes.h"
#include "rtxsrc/rtxCommon.h"

/*
 * Randomly generated test file: seed = 1351110507
 */
PersonnelRecord* asn1Test_PersonnelRecord (OSCTXT* pctxt)
{
   PersonnelRecord* pvalue = rtxMemAllocType (pctxt, PersonnelRecord);
   asn1Init_PersonnelRecord (pvalue);

   /* Start SEQUENCE or SET 1 */

   pvalue->m.iPresent = 1;
   /* Populate the Integer type */
   pvalue->i = 573725232;

   pvalue->m.i2Present = 1;
   /* Populate the Integer type */
   pvalue->i2 = 2131738418;

   pvalue->m.ePresent = 1;
   /* Populate the Enumerated type */
   pvalue->e = a_1;

   pvalue->m.e2Present = 1;
   /* Populate the Enumerated type */
   pvalue->e2 = a;

   pvalue->m.bPresent = 1;
   /* Populate the Boolean type */
   pvalue->b = 0;

   pvalue->m.bs0Present = 1;
   /* Populate BIT STRING variable */
   pvalue->bs0.numbits = 7;
   {
      OSOCTET* bitData = (OSOCTET*) rtxMemAlloc (pctxt,1);
      bitData[0] = 0x72;
      pvalue->bs0.data = (const OSOCTET*)bitData;
   }

   pvalue->m.bsPresent = 1;
   /* Populate BIT STRING variable */
   pvalue->bs.numbits = 4;
   {
      OSOCTET* bitData = (OSOCTET*) rtxMemAlloc (pctxt,1);
      bitData[0] = 0x6b;
      pvalue->bs.data = (const OSOCTET*)bitData;
   }

   pvalue->m.bs1Present = 1;
   /* Populate BIT STRING variable */
   pvalue->bs1.numbits = 14;
   {
      OSOCTET* bitData = (OSOCTET*) rtxMemAlloc (pctxt,2);
      bitData[0] = 0x64;
      bitData[1] = 0x47;
      pvalue->bs1.data = (const OSOCTET*)bitData;
   }

   pvalue->m.bs2Present = 1;
   /* Populate BIT STRING variable */
   pvalue->bs2.numbits = 8;
   {
      OSOCTET* bitData = (OSOCTET*) rtxMemAlloc (pctxt,1);
      bitData[0] = 0x46;
      pvalue->bs2.data = (const OSOCTET*)bitData;
   }

   pvalue->m.bs3Present = 1;
   /* Populate BIT STRING variable */
   pvalue->bs3.numbits = 9;
   {
      OSOCTET* bitData = (OSOCTET*) rtxMemAlloc (pctxt,2);
      bitData[0] = 0x31;
      bitData[1] = 0x6d;
      pvalue->bs3.data = (const OSOCTET*)bitData;
   }

   pvalue->m.csPresent = 1;
   /* Populate the Character String */
   pvalue->cs = "rM_BU";

   pvalue->m.cs1Present = 1;
   /* Populate the Character String */
   pvalue->cs1 = "OsZd54VbQd";

   pvalue->m.cs2Present = 1;
   /* Populate the Character String */
   pvalue->cs2 = "@A4VS5";

   pvalue->m.cs3Present = 1;
   /* Populate the Character String */
   pvalue->cs3 = "0h";

   pvalue->m.osPresent = 1;
   /* Populate OCTET STRING variable */
   pvalue->os.numocts = 14;
   pvalue->os.data = (OSOCTET*) rtxMemAlloc (pctxt, 14);
   {
      static const OSOCTET testdata[] = {
      0x64, 0x29, 0xc2, 0x2f, 0xa7, 0x42, 0xa6, 0x65, 
      0x96, 0x10, 0x85, 0x47, 0x79, 0x86 };
      OSCRTLMEMCPY ((void*)pvalue->os.data, testdata, 14);
   }

   pvalue->m.os1Present = 1;
   /* Populate OCTET STRING variable */
   pvalue->os1.numocts = 13;
   pvalue->os1.data = (OSOCTET*) rtxMemAlloc (pctxt, 13);
   {
      static const OSOCTET testdata[] = {
      0x04, 0xac, 0xb3, 0xbd, 0x55, 0xcb, 0x5f, 0xe2, 
      0x32, 0x3c, 0x84, 0x29, 0xa6 };
      OSCRTLMEMCPY ((void*)pvalue->os1.data, testdata, 13);
   }

   pvalue->m.os2Present = 1;
   /* Populate OCTET STRING variable */
   pvalue->os2.numocts = 6;
   pvalue->os2.data = (OSOCTET*) rtxMemAlloc (pctxt, 6);
   {
      static const OSOCTET testdata[] = {
      0xac, 0xf4, 0x6b, 0x55, 0x37, 0x1a };
      OSCRTLMEMCPY ((void*)pvalue->os2.data, testdata, 6);
   }

   pvalue->m.os3Present = 1;
   /* Populate OCTET STRING variable */
   pvalue->os3.numocts = 9;
   pvalue->os3.data = (OSOCTET*) rtxMemAlloc (pctxt, 9);
   {
      static const OSOCTET testdata[] = {
      0xf8, 0xc0, 0x63, 0x8f, 0xd0, 0x69, 0x56, 0xc9, 
      0xef };
      OSCRTLMEMCPY ((void*)pvalue->os3.data, testdata, 9);
   }

   pvalue->m.os4Present = 1;
   /* Populate OCTET STRING variable */
   pvalue->os4.numocts = 4;
   pvalue->os4.data = (OSOCTET*) rtxMemAlloc (pctxt, 4);
   {
      static const OSOCTET testdata[] = {
      0x4e, 0x9c, 0xc7, 0xc };
      OSCRTLMEMCPY ((void*)pvalue->os4.data, testdata, 4);
   }

   pvalue->m.oidPresent = 1;
   /* Populate OBJECT IDENTIFIER */
   {
      OSUINT32 ui;
      pvalue->oid.numids = 5;
      for(ui =0; ui<5; ui++)
         pvalue->oid.subid[ui] = ui;
   }

   pvalue->m.roidPresent = 1;
   /* Populate OBJECT IDENTIFIER */
   {
      OSUINT32 ui;
      pvalue->roid.numids = 5;
      for(ui =0; ui<5; ui++)
         pvalue->roid.subid[ui] = ui;
   }

   pvalue->m.nulPresent = 1;

   pvalue->m.nul2Present = 1;

   pvalue->m.vidsPresent = 1;
   /* Populate the Character String */
   pvalue->vids = "n:ZbPQ9GaM";

   pvalue->m.vissPresent = 1;
   /* Populate the Character String */
   pvalue->viss = "k";

   pvalue->m.grasPresent = 1;
   /* Populate the Character String */
   pvalue->gras = "V";

   pvalue->m.gensPresent = 1;
   /* Populate the Character String */
   pvalue->gens = "Ld8";

   pvalue->m.unisPresent = 0;
   pvalue->m.unis2Present = 0;
   pvalue->m.unis3Present = 0;
   pvalue->m.unis4Present = 0;
   pvalue->m.unis5Present = 0;

   pvalue->m.bmpsPresent = 1;
   /* Populate the BMPString */
   pvalue->bmps.data =(OSUNICHAR*) rtxMemAllocZ(pctxt, 8*sizeof(OSUNICHAR));
   pvalue->bmps.nchars = 8;
   {
      static const OSUNICHAR testdata[] = {50, 66, 85, 72, 68, 70, 99, 81 };
      OSCRTLMEMCPY((void*)pvalue->bmps.data, testdata, 8*sizeof(OSUNICHAR));
   }

   pvalue->m.bmps2Present = 1;
   /* Populate the BMPString */
   pvalue->bmps2.data =(OSUNICHAR*) rtxMemAllocZ(pctxt, 4*sizeof(OSUNICHAR));
   pvalue->bmps2.nchars = 4;
   {
      static const OSUNICHAR testdata[] = {111, 64, 84, 95 };
      OSCRTLMEMCPY((void*)pvalue->bmps2.data, testdata, 4*sizeof(OSUNICHAR));
   }

   pvalue->m.bmps3Present = 1;
   /* Populate the BMPString */
   pvalue->bmps3.data =(OSUNICHAR*) rtxMemAllocZ(pctxt, 1*sizeof(OSUNICHAR));
   pvalue->bmps3.nchars = 1;
   {
      static const OSUNICHAR testdata[] = {72 };
      OSCRTLMEMCPY((void*)pvalue->bmps3.data, testdata, 1*sizeof(OSUNICHAR));
   }

   pvalue->m.bmps4Present = 1;
   /* Populate the BMPString */
   pvalue->bmps4.data =(OSUNICHAR*) rtxMemAllocZ(pctxt, 5*sizeof(OSUNICHAR));
   pvalue->bmps4.nchars = 5;
   {
      static const OSUNICHAR testdata[] = {75, 73, 57, 81, 98 };
      OSCRTLMEMCPY((void*)pvalue->bmps4.data, testdata, 5*sizeof(OSUNICHAR));
   }

   pvalue->m.bmps5Present = 1;
   /* Populate the BMPString */
   pvalue->bmps5.data =(OSUNICHAR*) rtxMemAllocZ(pctxt, 2*sizeof(OSUNICHAR));
   pvalue->bmps5.nchars = 2;
   {
      static const OSUNICHAR testdata[] = {51, 64 };
      OSCRTLMEMCPY((void*)pvalue->bmps5.data, testdata, 2*sizeof(OSUNICHAR));
   }

   pvalue->m.utf8Present = 1;
   /* Populate the Character String */
   pvalue->utf8 = OSUTF8("A");

   pvalue->m.gtPresent = 1;
   /* Populate the Character String */
   pvalue->gt = "19971118045233.3141Z";

   pvalue->m.utPresent = 1;
   /* Populate the Character String */
   pvalue->ut = "070507224500Z";

   pvalue->m.r1Present = 1;
   /* Populate the Real type */
   pvalue->r1 = 1.96634e+09;

   pvalue->m.biPresent = 1;
   /* Populate the Integer type */
   pvalue->bi = 1574864679;

   pvalue->m.bi2Present = 1;
   /* Populate the Integer type */
   pvalue->bi2 = 1209054496;

   pvalue->m.choiceSeqPresent = 1;
   /* Start SEQUENCE OF 2 */
   {
      OSRTDList* plist = &pvalue->choiceSeq;
      BiometricSyntax* pdata;
      rtxDListInit (plist);

      pdata = rtxMemAllocTypeZ (pctxt, BiometricSyntax);
      pdata->t = 0;
      OSCRTLMEMSET (&pdata->u, 0, sizeof(pdata->u));
      /* Start CHOICE 3 */
      pdata->t =  T_BiometricSyntax_int_;
      /* Populate the Integer type */
      pdata->u.int_ = 515688386;
      /* End CHOICE 3 */

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, BiometricSyntax);
      pdata->t = 0;
      OSCRTLMEMSET (&pdata->u, 0, sizeof(pdata->u));
      /* Start CHOICE 4 */
      pdata->t =  T_BiometricSyntax_name;
      pdata->u.name = rtxMemAllocTypeZ (pctxt, Name);
      /* Start SEQUENCE or SET 5 */

      /* Populate the Character String */
      pdata->u.name->givenName = "QERfqsSL";

      /* Populate the Character String */
      pdata->u.name->initial = "oDN";

      /* Populate the Character String */
      pdata->u.name->familyName = "V";
      /* End SEQUENCE or SET 5 */
      /* End CHOICE 4 */

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, BiometricSyntax);
      pdata->t = 0;
      OSCRTLMEMSET (&pdata->u, 0, sizeof(pdata->u));
      /* Start CHOICE 6 */
      pdata->t =  T_BiometricSyntax_ch;
      pdata->u.ch = rtxMemAllocTypeZ (pctxt, BiometricSyntax_ch);
      /* Start CHOICE 7 */
      pdata->u.ch->t =  T_BiometricSyntax_ch_a;
      /* Populate the Integer type */
      pdata->u.ch->u.a = 577577112;
      /* End CHOICE 7 */
      /* End CHOICE 6 */

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, BiometricSyntax);
      pdata->t = 0;
      OSCRTLMEMSET (&pdata->u, 0, sizeof(pdata->u));
      /* Start CHOICE 8 */
      pdata->t =  T_BiometricSyntax_child;
      pdata->u.child = rtxMemAllocTypeZ (pctxt, ChildInformation);
      /* Start SEQUENCE or SET 9 */

      /* Start SEQUENCE or SET 10 */

      /* Populate the Character String */
      pdata->u.child->name.givenName = "67h6T";

      /* Populate the Character String */
      pdata->u.child->name.initial = "YB0";

      /* Populate the Character String */
      pdata->u.child->name.familyName = "HrP";
      /* End SEQUENCE or SET 10 */

      /* Populate the Character String */
      pdata->u.child->dateOfBirth = "M";

      pdata->u.child->m.chPresent = 1;
      /* Start CHOICE 11 */
      pdata->u.child->ch.t =  T_ChildInformation_ch_initial;
      /* Populate the Character String */
      pdata->u.child->ch.u.initial = "U57BUL7";
      /* End CHOICE 11 */
      /* End SEQUENCE or SET 9 */
      /* End CHOICE 8 */

      rtxDListAppend (pctxt, plist, (void*)pdata);

   }
   /* End SEQUENCE OF 2 */

   pvalue->m.primSeqPresent = 1;
   /* Start SEQUENCE OF 12 */
   {
      OSRTDList* plist = &pvalue->primSeq;
      OSINT32* pdata;
      rtxDListInit (plist);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 965536382;

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 459841751;

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 701440874;

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 288541620;

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 515934229;

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 2007520937;

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 973259276;

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 874114855;

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, OSINT32);
      /* Populate the Integer type */
      *pdata = 1234214535;

      rtxDListAppend (pctxt, plist, (void*)pdata);

   }
   /* End SEQUENCE OF 12 */

   pvalue->m.primSeqStPresent = 1;
   /* Start SEQUENCE OF 13 */
   pvalue->primSeqSt.n = 2;
   /* Populate the Integer type */
   pvalue->primSeqSt.elem[0] = 250282050;

   /* Populate the Integer type */
   pvalue->primSeqSt.elem[1] = 312310658;

   /* End SEQUENCE OF 13 */

   pvalue->m.choicePresent = 1;
   /* Start CHOICE 14 */
   pvalue->choice.t =  T_PersonnelRecord_choice_name;
   pvalue->choice.u.name = rtxMemAllocTypeZ (pctxt, Name);
   /* Start SEQUENCE or SET 15 */

   /* Populate the Character String */
   pvalue->choice.u.name->givenName = "N";

   /* Populate the Character String */
   pvalue->choice.u.name->initial = "t";

   /* Populate the Character String */
   pvalue->choice.u.name->familyName = "Xj8";
   /* End SEQUENCE or SET 15 */
   /* End CHOICE 14 */

   pvalue->m.childPresent = 1;
   /* Start SEQUENCE or SET 16 */

   /* Start SEQUENCE or SET 17 */

   /* Populate the Character String */
   pvalue->child.name.givenName = "pdJHOf2b";

   /* Populate the Character String */
   pvalue->child.name.initial = "6Zt@Y";

   /* Populate the Character String */
   pvalue->child.name.familyName = "j53c6Bc45";
   /* End SEQUENCE or SET 17 */

   /* Populate the Character String */
   pvalue->child.dateOfBirth = "I5ACPYn";

   pvalue->child.m.chPresent = 1;
   /* Start CHOICE 18 */
   pvalue->child.ch.t =  T_ChildInformation_ch_initial;
   /* Populate the Character String */
   pvalue->child.ch.u.initial = "QmKO8:";
   /* End CHOICE 18 */
   /* End SEQUENCE or SET 16 */

   pvalue->m.bioSetPresent = 1;
   /* Start SEQUENCE OF 19 */
   {
      OSRTDList* plist = &pvalue->bioSet;
      BiometricSyntax* pdata;
      rtxDListInit (plist);

      pdata = rtxMemAllocTypeZ (pctxt, BiometricSyntax);
      pdata->t = 0;
      OSCRTLMEMSET (&pdata->u, 0, sizeof(pdata->u));
      /* Start CHOICE 20 */
      pdata->t =  T_BiometricSyntax_int_;
      /* Populate the Integer type */
      pdata->u.int_ = 776908811;
      /* End CHOICE 20 */

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, BiometricSyntax);
      pdata->t = 0;
      OSCRTLMEMSET (&pdata->u, 0, sizeof(pdata->u));
      /* Start CHOICE 21 */
      pdata->t =  T_BiometricSyntax_name;
      pdata->u.name = rtxMemAllocTypeZ (pctxt, Name);
      /* Start SEQUENCE or SET 22 */

      /* Populate the Character String */
      pdata->u.name->givenName = "tKT8";

      /* Populate the Character String */
      pdata->u.name->initial = "n116i";

      /* Populate the Character String */
      pdata->u.name->familyName = "oh5IXseUXL";
      /* End SEQUENCE or SET 22 */
      /* End CHOICE 21 */

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, BiometricSyntax);
      pdata->t = 0;
      OSCRTLMEMSET (&pdata->u, 0, sizeof(pdata->u));
      /* Start CHOICE 23 */
      pdata->t =  T_BiometricSyntax_ch;
      pdata->u.ch = rtxMemAllocTypeZ (pctxt, BiometricSyntax_ch);
      /* Start CHOICE 24 */
      pdata->u.ch->t =  T_BiometricSyntax_ch_a;
      /* Populate the Integer type */
      pdata->u.ch->u.a = 1824492737;
      /* End CHOICE 24 */
      /* End CHOICE 23 */

      rtxDListAppend (pctxt, plist, (void*)pdata);

      pdata = rtxMemAllocTypeZ (pctxt, BiometricSyntax);
      pdata->t = 0;
      OSCRTLMEMSET (&pdata->u, 0, sizeof(pdata->u));
      /* Start CHOICE 25 */
      pdata->t =  T_BiometricSyntax_child;
      pdata->u.child = rtxMemAllocTypeZ (pctxt, ChildInformation);
      /* Start SEQUENCE or SET 26 */

      /* Start SEQUENCE or SET 27 */

      /* Populate the Character String */
      pdata->u.child->name.givenName = "U7G";

      /* Populate the Character String */
      pdata->u.child->name.initial = "A";

      /* Populate the Character String */
      pdata->u.child->name.familyName = "m";
      /* End SEQUENCE or SET 27 */

      /* Populate the Character String */
      pdata->u.child->dateOfBirth = "r";

      pdata->u.child->m.chPresent = 1;
      /* Start CHOICE 28 */
      pdata->u.child->ch.t =  T_ChildInformation_ch_givenName;
      /* Populate the Character String */
      pdata->u.child->ch.u.givenName = "GCQn5Jm";
      /* End CHOICE 28 */
      /* End SEQUENCE or SET 26 */
      /* End CHOICE 25 */

      rtxDListAppend (pctxt, plist, (void*)pdata);

   }
   /* End SEQUENCE OF 19 */

   pvalue->m.bioSet2Present = 1;
   /* Start SEQUENCE OF 29 */
   /* zero elements */
   /* End SEQUENCE OF 29 */
   /* End SEQUENCE or SET 1 */
   return (pvalue);
}

Set* asn1Test_Set (OSCTXT* pctxt)
{
   Set* pvalue = rtxMemAllocType (pctxt, Set);
   asn1Init_Set (pvalue);

   /* Start SEQUENCE or SET 30 */

   /* Populate the Character String */
   pvalue->dateOfBirth = "o";
   /* End SEQUENCE or SET 30 */
   return (pvalue);
}

