/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2.3, Date: 10-Sep-2020.
 */
#include "NGAP-CommonDataTypes.h"
#include "rtxsrc/rtxCommon.h"

EXTERN int asn1PE_Criticality (OSCTXT* pctxt, Criticality value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "Criticality");

   RTDIAGSTRM2 (pctxt, "asn1PE_Criticality: start\n");

   if (value >= 3) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
   stat = pe_ConsUnsigned (pctxt, value, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_Criticality: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1PE_Presence (OSCTXT* pctxt, Presence value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "Presence");

   RTDIAGSTRM2 (pctxt, "asn1PE_Presence: start\n");

   if (value >= 3) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
   stat = pe_ConsUnsigned (pctxt, value, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_Presence: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1PE_ProcedureCode (OSCTXT* pctxt, ProcedureCode value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ProcedureCode");

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureCode: start\n");

   stat = pe_ConsUnsigned (pctxt, value, 0, 255);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureCode: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1PE_ProtocolExtensionID (OSCTXT* pctxt, ProtocolExtensionID value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ProtocolExtensionID");

   RTDIAGSTRM2 (pctxt, "asn1PE_ProtocolExtensionID: start\n");

   stat = pe_ConsUnsigned (pctxt, value, 0, 65535);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_ProtocolExtensionID: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1PE_ProtocolIE_ID (OSCTXT* pctxt, ProtocolIE_ID value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ProtocolIE-ID");

   RTDIAGSTRM2 (pctxt, "asn1PE_ProtocolIE_ID: start\n");

   stat = pe_ConsUnsigned (pctxt, value, 0, 65535);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_ProtocolIE_ID: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1PE_TriggeringMessage (OSCTXT* pctxt, TriggeringMessage value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "TriggeringMessage");

   RTDIAGSTRM2 (pctxt, "asn1PE_TriggeringMessage: start\n");

   if (value >= 3) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
   stat = pe_ConsUnsigned (pctxt, value, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_TriggeringMessage: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1PE_PrivateIE_ID (OSCTXT* pctxt, PrivateIE_ID* pvalue)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "PrivateIE-ID");

   RTDIAGSTRM2 (pctxt, "asn1PE_PrivateIE_ID: start\n");

   /* Encode choice index value */

   RTXCTXTPUSHELEMNAME (pctxt, "t");
   PU_NEWFIELD (pctxt, "<choice-index>");

   stat = rtxEncBits (pctxt, pvalue->t - 1, 1);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   PU_SETBITCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* Encode root element data value */

   switch (pvalue->t)
   {
      /* local */
      case 1:
         RTXCTXTPUSHELEMNAME (pctxt, "local");

         stat = pe_ConsUnsigned (pctxt, pvalue->u.local, 0, 65535);
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         RTXCTXTPOPELEMNAME (pctxt);
         break;

      /* global */
      case 2:
         RTXCTXTPUSHELEMNAME (pctxt, "global");

         stat = pe_ObjectIdentifier (pctxt, pvalue->u.global);
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         RTXCTXTPOPELEMNAME (pctxt);
         break;

      default:
         return LOG_RTERR (pctxt, RTERR_INVOPT);
   }

   RTDIAGSTRM2 (pctxt, "asn1PE_PrivateIE_ID: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

