/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.6.0, Date: 15-Feb-2022.
 */
#include "TS24007L3.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

/*
 * Randomly generated test file: seed = 1644926504
 */
TS24007L3_EPSBearerIdentity*
    asn1Test_TS24007L3_EPSBearerIdentity (OSCTXT* pctxt)
{
   TS24007L3_EPSBearerIdentity* pvalue = rtxMemAllocType (pctxt, TS24007L3_EPSBearerIdentity);

   *pvalue = TS24007L3_EPSBearerIdentity_id14;
   return (pvalue);
}

TS24007L3_L3HdrOptions* asn1Test_TS24007L3_L3HdrOptions (OSCTXT* pctxt)
{
   TS24007L3_L3HdrOptions* pvalue = rtxMemAllocType (pctxt, TS24007L3_L3HdrOptions);
   asn1Init_TS24007L3_L3HdrOptions (pvalue);

   pvalue->t =  4;
   pvalue->u.secHdr = 1;
   return (pvalue);
}

TS24007L3_ProtoDiscr* asn1Test_TS24007L3_ProtoDiscr (OSCTXT* pctxt)
{
   TS24007L3_ProtoDiscr* pvalue = rtxMemAllocType (pctxt, TS24007L3_ProtoDiscr);

   *pvalue = TS24007L3_ProtoDiscr_extPduInd;
   return (pvalue);
}

TS24007L3_SecHdrType* asn1Test_TS24007L3_SecHdrType (OSCTXT* pctxt)
{
   TS24007L3_SecHdrType* pvalue = rtxMemAllocType (pctxt, TS24007L3_SecHdrType);

   *pvalue = TS24007L3_SecHdrType_secHdrForSvcReq;
   return (pvalue);
}

TS24007L3_Header* asn1Test_TS24007L3_Header (OSCTXT* pctxt)
{
   TS24007L3_Header* pvalue = rtxMemAllocType (pctxt, TS24007L3_Header);
   asn1Init_TS24007L3_Header (pvalue);

   pvalue->l3HdrOpts.t =  1;
   pvalue->l3HdrOpts.u.skipInd = 6;

   pvalue->protoDiscr = TS24007L3_ProtoDiscr_sms;

   pvalue->msgType = 227;
   return (pvalue);
}

TS24007L3_MsgType_MM_CC_SS* asn1Test_TS24007L3_MsgType_MM_CC_SS (OSCTXT* pctxt)
{
   TS24007L3_MsgType_MM_CC_SS* pvalue = rtxMemAllocType (pctxt, TS24007L3_MsgType_MM_CC_SS);

   pvalue->sendSeqNum = 2;

   pvalue->value = 60;
   return (pvalue);
}

TS24007L3_SecProtMsgHeader* asn1Test_TS24007L3_SecProtMsgHeader (OSCTXT* pctxt)
{
   TS24007L3_SecProtMsgHeader* pvalue = rtxMemAllocType (pctxt, TS24007L3_SecProtMsgHeader);

   pvalue->secHdrType = TS24007L3_SecHdrType_secHdrForSvcReq;

   pvalue->protoDiscr = 12;

   pvalue->msgAuthCode = 1145314383;

   pvalue->seqNumber = 138;
   return (pvalue);
}

