/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.6.B, Date: 01-Jan-2022.
 */
#include "InfoObject.h"
#include "rtxsrc/rtxCommon.h"

#include "rtxsrc/rtxPrint.h"
#include "rtxsrc/rtxStreamFile.h"

int main (int argc, char** argv)
{
   Cause cause;
   Iu_ReleaseCommand_protocolIEs_element elem;
   Iu_ReleaseCommand pdu;
   OSCTXT     ctxt;
   int        i, stat;
   OSBOOL     trace = TRUE;
   OSBOOL     verbose = FALSE;
   const char* filename = "message.json";

   /* Process command line arguments */
   if (argc > 1) {
      for (i = 1; i < argc; i++) {
         if (!strcmp (argv[i], "-v")) verbose = TRUE;
         else if (!strcmp (argv[i], "-o")) filename = argv[++i];
         else if (!strcmp (argv[i], "-notrace")) trace = FALSE;
         else {
            printf ("usage: writer [-v] [-o <filename>]  [-notrace]\n");
            printf ("   -v  verbose mode: print trace info\n");
            printf ("   -o <filename>  write encoded msg to <filename>\n");
            printf ("   -notrace  do not display trace info\n");
            return 1;
         }
      }
   }

   /* Initialize context structure */
   stat = rtInitContext (&ctxt);
   if (stat != 0) {
      rtxErrPrint (&ctxt);
      return stat;
   }
   rtxSetDiag (&ctxt, verbose);

   /* populate pdata with test data */
   cause.t = T_Cause_radioNetwork;
   cause.u.radioNetwork = condition_violation_for_guaranteed_bit_rate;

   elem.id = ASN1V_id_Cause;
   elem.criticality = ignore;
   elem.value.t = T_InfoObject_Iu_ReleaseCommandIEs_id_Cause;
   elem.value.u._Iu_ReleaseCommandIEs_id_Cause = &cause;
   
   asn1Init_Iu_ReleaseCommand (&pdu);
   rtxDListAppend(&ctxt, &pdu.protocolIEs, &elem);

   if (trace) {
      printf ("The following record will be encoded:\n");
      asn1Print_Iu_ReleaseCommand ("pdu", &pdu);
      printf ("\n");
   }

   /* Create file output stream */
   stat = rtxStreamFileCreateWriter (&ctxt, filename);
   if (stat < 0) {
      printf ("Create file output stream failed\n");
      rtxErrPrint (&ctxt);
      rtFreeContext (&ctxt);
      return stat;
   }

   /* Encode */
   stat = asn1JsonEnc_Iu_ReleaseCommand (&ctxt, &pdu);
   if (stat < 0) {
      printf ("Encoding failed\n");
      rtxErrPrint (&ctxt);
      rtFreeContext (&ctxt);
      return stat;
   }
   else if (trace) {
      printf ("Output file written successfully.\n");
   }

   rtFreeContext (&ctxt);

   return 0;
}
