Po$(OBJ): Po.c Po.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h XSD.h
PoDec$(OBJ): PoDec.c Po.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h XSD.h
PoEnc$(OBJ): PoEnc.c Po.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h XSD.h
PoPrint$(OBJ): PoPrint.c Po.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h XSD.h \
 ../../../rtsrc/rtPrint.h ../../../rtxsrc/rtxPrint.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h
PoTest$(OBJ): PoTest.c Po.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h XSD.h
XSD$(OBJ): XSD.c XSD.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h
XSDDec$(OBJ): XSDDec.c XSD.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h
XSDEnc$(OBJ): XSDEnc.c XSD.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h
XSDPrint$(OBJ): XSDPrint.c XSD.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h \
 ../../../rtsrc/rtPrint.h ../../../rtxsrc/rtxPrint.h \
 ../../../rtxsrc/rtxHexDump.h ../../../rtsrc/rtBCD.h \
 ../../../rtxsrc/rtxTBCD.h
XSDTest$(OBJ): XSDTest.c XSD.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h
reader$(OBJ): reader.c Po.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h XSD.h \
 ../../../rtxsrc/rtxStreamFile.h ../../../rtxsrc/rtxStream.h
writer$(OBJ): writer.c Po.h rtkey.h ../../../rtsrc/asn1type.h \
 ../../../rtxsrc/rtxExternDefs.h ../../../rtxsrc/rtxSList.h \
 ../../../rtxsrc/rtxContext.h ../../../rtxsrc/rtxDList.h \
 ../../../rtxsrc/osSysTypes.h ../../../rtxsrc/rtxCommonDefs.h \
 ../../../rtxsrc/osMacros.h ../../../rtxsrc/rtxStack.h \
 ../../../rtxsrc/rtxUTF8.h ../../../rtsrc/asn1tag.h \
 ../../../rtsrc/asn1ErrCodes.h ../../../rtsrc/rtExternDefs.h \
 ../../../rtxsrc/rtxBitString.h ../../../rtsrc/rtContext.h \
 ../../../rtsrc/asn1CEvtHndlr.h ../../../rtxsrc/rtxError.h \
 ../../../rtxsrc/rtxErrCodes.h ../../../rtxsrc/rtxMemory.h \
 ../../../rtxmlsrc/asn1xml.h ../../../rtxmlsrc/osrtxml.h \
 ../../../rtxsrc/rtxCommon.h ../../../rtxsrc/rtxBigInt.h \
 ../../../rtxsrc/rtxBuffer.h ../../../rtxsrc/rtxCharStr.h \
 ../../../rtxsrc/rtxDateTime.h ../../../rtxsrc/rtxDiag.h \
 ../../../rtxsrc/rtxEnum.h ../../../rtxsrc/rtxFile.h \
 ../../../rtxsrc/rtxPattern.h ../../../rtxsrc/rtxReal.h \
 ../../../rtxsrc/rtxUtil.h ../../../rtxmlsrc/rtSaxDefs.h \
 ../../../rtxsrc/rtxMemBuf.h ../../../rtxmlsrc/rtXmlExternDefs.h \
 ../../../rtxmlsrc/rtXmlErrCodes.h ../../../rtxmlsrc/rtXmlNamespace.h \
 ../../../rtxsrc/rtxDynPtrArray.h ../../../rtxsrc/rtxXmlQName.h XSD.h
